### ISSUE TITLE
No se logra crear base de datos (Ubuntu)

### ISSUE THREAD

**Issue by CrisHD935** [IIC2143/Syllabus#1]
Hola! Me pasa que sigo la guía de setup y llego hasta el paso 11, luego intento hacer rails db:create y no funciona y me manda el siguiente error
<img width="879" alt="image" src="https://github.com/IIC2143/Syllabus/assets/133688044/5db09a02-6aff-4b68-aef2-ae0e7547dfac">
Si intento lo que me dice no funciona, y revisé y postgresql esta corriendo, así que no sé cual puede ser el error.

**Comment by tomastrivino** [comment]
teni que cambiar los datos de tu usuario, contraseña y db **de postgresql** en `config/database.yml`. está fallando la conexión por esa parte

**Comment by CrisHD935** [comment]
Que datos del db tengo que cambiar ahi?

**Comment by TomasRiquelme** [comment]
> teni que cambiar los datos de tu usuario, contraseña y db **de postgresql** en `config/database.yml`. está fallando la conexión por esa parte
A que te refieres especificamente?
Ahora lo tengo como username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
hay que cambiar <%= ENV["DB_USER"] %> por mi nombre de usuario por ejemplo?
y a que te refieres con cambiar db :c ???

estoi desesperado . - .

**Comment by dgolzm** [comment]
Hola, yo tuve un problema similar con la base de datos, pero me indica esto:
![Captura de pantalla 2024-03-12 122245](https://github.com/IIC2143/Syllabus/assets/141859631/cad64df1-fefe-470d-b042-0076fd6a0184)

Como podria solucionarlo?
