### ISSUE TITLE
Nombres esperados atributos TeamA y TeamB en Match

### ISSUE THREAD

**Issue by k0rval4n** [IIC2143/Syllabus#10]
¡Hola! Los atributos de un match que hagan referencia a sus dos equipos deben ser textualmente "teamA" y "teamB", o pueden aparecer en el formato "teamA_id" y "teamB_id"?

¡Muchas gracias!

![image](https://github.com/IIC2143/Syllabus/assets/141952843/dc58b643-23fd-4567-9126-242cfabe8031)
![image](https://github.com/IIC2143/Syllabus/assets/141952843/fc3b9299-cd30-48ad-8dea-a557731ff3e1)

**Comment by BenjaMartinezV** [comment]
Hola! yo tengo la misma pregunta, investigue un poco y descubri dos metodos para modificar el json del response body, una es utilizando ActiveModel::Serializer para modificar el nombre de los atributos en el response pero se tiene que instalar una gem serializer y la otra opcion es utilizando la función map. Pero no se que tan permitidos estan estos metodos en la tarea.
Saludos

**Comment by FelipeMunozMoraga** [comment]
Hola! Se espera que efectivamente los atributos sean teamA y teamB, tal y como indica Benjamín existen múltiples maneras de modificar el JSON response. En particular su solución debe poder ejecutarse en un computador externo al suyo, por lo que funciones como map, definir métodos de clase y utilizar gemas como la mencionada está permitido. Parte del objetivo del curso es que aprendan a investigar y buscar soluciones a los problemas que surgen al desarrollar software, los felicito por ya contar con esa capacidad!
Éxito en la tarea y mucha suerte!
