### ISSUE TITLE
Probemas parte 3 instalación

### ISSUE THREAD

**Issue by FelipeMunozMoraga** [IIC2143/Syllabus#10]
Hola, estuve intentando de instalar RVM y no me funcionó el segundo comando, leí la issue anterior en la que solucionaban el problema sin embargo eso tampocó me resultó.
Dejo una captura de lo que hicé
![Captura](https://user-images.githubusercontent.com/101280597/184457097-839612e3-ec36-4894-b892-8f34704ea248.PNG)

**Comment by aurmeneta** [comment]
Hola!

Intenta con este comando: `gpg --keyserver keys.openpgp.org --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1C
F37B13E2069D6956105BD0E739499BDB`

**Comment by FelipeMunozMoraga** [comment]
Gracias!
