### ISSUE TITLE
[Tarea] Expected output - Precios de ventas

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2143/Syllabus#10]
Hola! 

Al realizar el output de la tarea, no logro entender los precios que aparencen en `expected_output.txt`. Esto se debe a que los valores son distintos de los que esperaría:

- en `objetos.csv` el trigo tiene un _preciobase_ de 10, pero en el texto tiene un valor de 6. Es decir, un 40% menos.

Y así, todos los precios estan ponderados por los descuentos de cada aldeano. Es decir, como el Bibliotecario tiene un descuento de 35% los valores de los productos que vende son `preciobase * descuento`. Entonces, en el caso hipotético de que un aldeano tenga un descuento del 100% en sus productos, estos valdrían `preciobase` y no 0 como uno esperaría.

Muchas gracias!

**Comment by aplaza2** [comment]
Me quiero sumar a la pregunta y hacer otra relacionada. 

En el enunciado se dice que `precio final = precio base * (1 - reputacion) * (1 - descuento)`, pero al usar esta fórmula en el método `realizar_intercambios()` el output de los precios de rubies es diferente al del `expected_output.txt`. No sé si esta diferencia sea por un error en mi código o si la forma de obtener el precio final en los intercambios es diferentes en el output esperado al mostrado en el enunciado. 

Gracias de antemano.

**Comment by Nicolasramos411** [comment]
@aplaza2 Me pasó lo mismo, pero los precios son los correctos. Fijate que el descuento solo se aplique si el aldeano tiene la capacidad de ofrecer descuento, por ejemplo, un Herrero no puede ofrecer descuento al vender Trigo.

**Comment by Artaudd** [comment]
@Nicolasramos411 Aún así, recuerda que el expected_output incluye solo los objetos que tienen descuento segun cada tipo de aldeano, por lo que todos los precios del expected_output deberían tener el descuento aplicado. Ahora, si te vas al primer ejemplo que aparece, tienes a un Granjero cuyo primer producto es "Trigo" con precio base 10, luego aplicando el descuento de 60% debería costar 4 rubíes, pero en el expected_output aparece con un precio de 6 rubíes. Por eso, creo que deben haber cometido un error en la fórmula que ocuparon para el expected_output.

**Comment by maggiemunoz** [comment]
Hola! Recuerden que el precio final depende no solo del descuento del aldeano, pero también de la reputación del jugador, la que va cambiando con cada interacción (y que, además, se redondea al entero más cercano). 

Importante mencionar que no todos los intercambios se hacen con un aldeano que ofrece descuento, en el primer caso del expected output, se intercambia un trigo (precio base 10) con un herrero (el precio se mantiene), y como el jugador que hace el intercambio tiene una reputación de 0.5, el precio queda en 5 rubíes.

Revisen que están actualizando la reputación de los jugadores, probablemente sea por eso que les están dando valores distintos :) Pero puedo confirmar que la formula usada es la correcta

**Comment by Artaudd** [comment]
@maggiemunoz Pero al mostrar la información de los aldeanos no tenemos un jugador específico con quien verificar reputación :thinking:

**Comment by maggiemunoz** [comment]
Para mostrar la información de los aldeanos solo es necesario el descuento aplicado por el aldeano. El info_aldeanos tenía un error con los precios justamente, voy a subir la version corregida con unas aclaraciones en el enunciado :)

**Comment by mpmunoz13** [comment]
@maggiemunoz cuando se actualiza la reputacion del jugador? al finalizar todos sus intercambios o despues de cada uno? Tengo el mismo error con el descuento aplicado en un par de casos.
