### ISSUE TITLE
Error Testing

### ISSUE THREAD

**Issue by Crisax234** [IIC2143/Syllabus#103]
Hola, cuando inicio el comando rspec, me aparece que mi usuario de ubuntu no existe, es el mismo error que me daba en el setup de rails y tuve que realizar muchos pasos guiados por un ayudante para resolverlo, por qué podría estar ocurriendo nuevamente? Adjunto pantallazo del error en la consola de ubuntu:
![image](https://user-images.githubusercontent.com/88630837/193358316-57698aed-1ef6-4871-a30c-808de0386176.png)

**Comment by fvalenzuelg** [comment]
Pudiste solucionarlo? nos pasa lo mismo

**Comment by Crisax234** [comment]
todavía no :(

**Comment by fvalenzuelg** [comment]
> todavía no :(

A nosotros nos resultó porque ahora lo intentó correr el que creó la base de datos:/ a lo mejor si cambian de persona les funcione.
