### ISSUE TITLE
Problema sudo apt-get update

### ISSUE THREAD

**Issue by PedroDP99** [IIC2143/Syllabus#105]
Hola, al momento de correr sudo apt-get update se me queda pegado mucho tiempo de la siguiente manera: 
![Captura](https://user-images.githubusercontent.com/80767669/194187019-9df25873-b754-4ccb-bca2-3f57cec71cfb.PNG)
Luego de un rato (bien largo) llega a lo siguiente:
![Captura2](https://user-images.githubusercontent.com/80767669/194187072-9c0eb8c9-10c9-44a1-acdf-2e56732b35fb.PNG)
Llevo intentado de todo lo que encuentro en internet, y todavía no logro que funcione, quedo atento

**Comment by CarloGauss33** [comment]
Hola @PedroDP99. ¿Que version de ubuntu tienes? 18, 20 ó 22?

**Comment by PedroDP99** [comment]
@CarloGauss33, perdón la demora.
He probado en todas las versiones y no he podido avanzar. Creo que debe ser un problema de DNS.
