### ISSUE TITLE
index.html error: "undefined method `each' for nil:NilClass"

### ISSUE THREAD

**Issue by piriabud** [IIC2143/Syllabus#108]
hola, cuando intento crear la tabla para ver desde `Movies#index` como se muestra en la ayudantía 05.CRUD, el servidor me arroja el siguiente error.

ActionView::Template::Error (undefined method `each' for nil:NilClass):

`<% @movies.each do |movie| %>`

Necesito instalar algo para poder utilizar le método `each`?
Gracias de antemano :p

**Comment by meretamal** [comment]
Eso, pasa que `@movies` está retornando `nil`. Están creando esa variable en el método `index` de su controlador?

**Comment by JupaOlivares** [comment]
Hay 2 errores muy comunes: 
- La primera es que @movies no se este definiendo en el controlador (la idea es que en el metodo index hagas algo como @movies = Movie.findAll() para definirlo).
- Y lo segundo pasa cuando no hay instancias del modelo movie por lo que @movies es null por lo que tira ese error (basta con crear una instancia de movie o hacer un if en caso de que sea vacio)
