### ISSUE TITLE
Creación de submodule INBORRABLE en repositorio

### ISSUE THREAD

**Issue by Ferlopa** [IIC2143/Syllabus#109]
Hola,

Accidentalmente subí el repositorio del proyecto DENTRO de la carpeta del repositorio de la tarea, esto hizo que se creará una "submodule" en mi tarea que resulta inborrable, he buscado ya por horas en internet, y no hay caso, no logro borrarlo. Adjunto imagen (me refiero a las carpetas azules con flecha).

<img width="1156" alt="image" src="https://github.com/IIC2143/Syllabus/assets/106124817/d9e106d3-fd2d-4352-bc5d-114b5127627f">

Agradecería:
- Saber como puedo "wipe/nuke/clean" el repositorio dado "2024-1-grupo-32" para empezar de nuevo
- Como eliminar submodules (NO APARECEN EN EL REPOSITORIO LOCAL por lo que no consto de sus paths, y en el visualizador web no hay una opción para borrarlos)
- Un abrazo

Saludos

**Comment by meretamal** [comment]
Hola 😁 .
Lo que puedes hacer es moverte dentro de la app, borrar la carpeta `.git` y mover todo el contenido restante a la raiz del repositorio:

```bash
cd proyecto_software
rm -rf .git
mv $(ls -a) ..
```

Debería salir un warning, pero debería funcionar igual.

**Comment by meretamal** [comment]
Ah, pero que no te salgan en local es raro. Puedes mandar el output al corre `ls` dentro de tu repositorio?

**Comment by Ferlopa** [comment]
Hola, aquí el resultado de:
1) Hacer git clone en una nueva carpeta
2) Hacer "ls"
<img width="779" alt="image" src="https://github.com/IIC2143/Syllabus/assets/106124817/ec8f0771-9927-414e-a2fa-0e1d4bef3743">

Cabe destacar que las dos carpetas asociadas a repositorios "submodules" estan vacias :(

**Comment by meretamal** [comment]
Ah, perfecto. La persona que subió el proyecto como submodule debe hacer lo que mandé en la primera respuesta y después pushear

**Comment by Ferlopa** [comment]
Hice lo pedido, sale esto:
<img width="572" alt="image" src="https://github.com/IIC2143/Syllabus/assets/106124817/1797042a-9649-468b-af32-c7fea4dddf15">

**Comment by Ferlopa** [comment]
Solamente el readme y una carpeta vacia "proyecto_software"
