### ISSUE TITLE
Heroku: Application Error

### ISSUE THREAD

**Issue by josetomasacuna** [IIC2143/Syllabus#109]
Hola. Para la entrega pasada no pudimos subir la app a heroku. Al ingresar a la página mediante el navegador, nos sale "Application Error".  
![app](https://user-images.githubusercontent.com/89480922/196263408-247951c3-16ee-4766-b857-a84042093093.PNG)
Al revisar los logs nos sale lo siguiente: 
![error](https://user-images.githubusercontent.com/89480922/196263440-e6a219ab-708a-49d7-8224-b395eef06d92.PNG)
![error2](https://user-images.githubusercontent.com/89480922/196263445-c4907f5a-4fbf-4a77-babd-0d8196862eb6.PNG)
He revisado stack over flow y otras páginas pero no he podido resolver el problema. Gracias.
![error3](https://user-images.githubusercontent.com/89480922/196306729-5cac415f-a03b-48e0-b48e-af5bd356ef50.PNG)

**Comment by JupaOlivares** [comment]
Hola!

Podrias mandar mas logs, pareciera que el verdadero error no se está mostrando, al parecer el error se da cuando se trata de iniciar la app.

**Comment by josetomasacuna** [comment]
Hola. Gracias por responder. Acá está el resto del log 

![log1](https://user-images.githubusercontent.com/89480922/196554043-bcb026dd-87a2-43ca-be89-8b03da4808ba.PNG) 
![log2](https://user-images.githubusercontent.com/89480922/196554049-12909ad0-bdfd-432e-887e-58aceae830fc.PNG)
![log3](https://user-images.githubusercontent.com/89480922/196554053-e4d34689-289f-4e50-99fb-fb42db7cf4f4.PNG)
![log4](https://user-images.githubusercontent.com/89480922/196554055-d22f2c2b-dfae-4dd1-a6a4-c7d6af435600.PNG)
