### ISSUE TITLE
Problemas Parte 5 Instalación: error running '__rvm_make -j8'

### ISSUE THREAD

**Issue by ivannateresa** [IIC2143/Syllabus#11]
Hola! Tengo un problema con la instalación de ruby. Al correr 'rvm install 2.6' me sale esto en la terminal. Estuve tratando de buscar alguna solución en google y aun me sigue tirando ese error. 

![imagen](https://user-images.githubusercontent.com/69605531/184465396-d6ac229f-44d0-4b10-b7de-4d63d1422af2.png)

De antemano muchas gracias c:

**Comment by meretamal** [comment]
Hola 😁 , podrías mandar el contenido de los logs que te generó? Al final de error sale el path donde se guardó el archivo.

**Comment by ivannateresa** [comment]
Hola! Encontre el archivo, ahí esta :D
[make.log](https://github.com/IIC2143/Syllabus/files/9331884/make.log)
Gracias!

**Comment by danielmeridacastro** [comment]
Hola, tengo el mismo problema, en un mac M1 😱

**Comment by meretamal** [comment]
Si es que intentan instalar otro _release_ de ruby 2.6.x les levanta el mismo error? Pueden ver las versiones disponibles corriendo `rvm list known`

**Comment by ivannateresa** [comment]
Hola!. Intente instalar otro ruby 2.6.x, pero en todos me sigue dando el mismo error. :c

**Comment by meretamal** [comment]
Si es que tienen un mac con m1, podrían intentar seguir la guía de setup usando rosetta.

Si es que no tienen un mac con m1 (o no quieren usar rosetta, podrían instalar ruby corriendo:
```bash
rvm install 2.6.6 --with-out-ext=fiddle
```
con esto, si corren `rvm list`, les saldrá `[broken]` al lado de la versión que instalaron. No sabemos que implicancias tendrá esto, pero a simple vista todo corre normalmente.

La última solución que podrían intentar, es instalar algún _release_ de ruby 2.7.x, lo cual todo su grupo de proyecto tendría que hacer y tendrían que tener ojo con la tarea que se les subirá, ya que es posible que se corrija usando ruby 2.6, para que eviten usar cosas que no son compatibles entre cada versión.

**Comment by Franbelen** [comment]
Hola buenas me sale un error parecido dice **Error running '__rvm_make -j16',**

**Comment by meretamal** [comment]
@Franbelen intentaste con alguna de las soluciones de arriba?

**Comment by Franbelen** [comment]
Hola buenas intente todo lo anterior y aun sale el mismo error

**Comment by Franbelen** [comment]
hola me ayudaron y funciono esto https://github.com/rvm/rvm/issues/5209#issuecomment-1134927685

**Comment by emolaba** [comment]
Hola buenas! Intenté solucionar el error running '__rvm_make -j8' usando todas las soluciones sugeridas y ninguna funcionó, todavía me sale el mismo error, incluso instalando ruby 2.7.x.
¿Que podría hacer?
Muchas gracias de antemano

**Comment by Amandasandov** [comment]
Hola, yo tambien intenté solucionar el error con todas las sugerencias dadas y nada ha funcionado. 
¿Tienen alguna otra idea de lo que se podría hacer para solucionar el problema?
De cualquier manera, muchas gracias por la disposición y ayuda que ya han proporcionado.

**Comment by isidoraabumohors** [comment]
Hola!

Tenía el mismo error, y al final pude instalar la versión 2.7.2 de Ruby. Sirve esa versión, o tiene que ser 2.6?

**Comment by Cinaraa** [comment]
estoy teniendo el mismo error, he probado con todas las versiones y opciones que han propuesto. Aun nada me funciona
