### ISSUE TITLE
[Tarea] nivel de aldeanos

### ISSUE THREAD

**Issue by cadaeic314** [IIC2143/Syllabus#11]
Hola!, tengo una consulta respecto a la cantidad de experiencia con que sube de nivel un aldeano. En específico, el aldeano Carlos tiene inicialmente una experiencia de 40 xp y es granjero, por lo que según el enunciado entiendo que debería subir a nivel 3, ya que según el enunciado alcanzan dicho nivel con 40 xp, pero en el output esperado aparece con nivel 2. Entonces significa que se sube de nivel a la cantidad de experiencia necesaria + 1 o el output esperado está mal?

Gracias de antemano y un ameno fin de semana.

**Comment by Nicolasramos411** [comment]
Misma duda.

**Comment by maggiemunoz** [comment]
Hola! Tienes toda la razón, efectivamente es un >=, por lo que tener 40 de xp debería subirlo al nivel 3, actualizaré el archivo de aldeanos para que el aldeano Carlos comience con 39 xp, para no variarles mucho el expected output. Gracias por avisar!
