### ISSUE TITLE
Sripts de Rails en los PPT de la seccion 2

### ISSUE THREAD

**Issue by vichoassadi** [IIC2143/Syllabus#11]
Hola!
Tengo una duda más general sobre dónde se escriben los scripts en los ppt's (adjunto una foto de ejemplo).

![image](https://github.com/IIC2143/Syllabus/assets/133837937/363ba714-36b4-4b03-88f2-6e47f4723332)

Entiendo los códigos de SQL se realizan en la terminal de rails, haciendo en la consola ``rails db``, y las migraciones en wsl; pero este tipo de scripts que interactuan directamente con los modelos, dónde se escriben?
Muchas gracias.

**Comment by meretamal** [comment]
Hola 😁 .

En clases mostramos estos comandos utilizando la consola de Rails, la cual se abre ejecutando `rails c`. Esta permite utilizar todas las cosas que existen dentro de tu proyecto (como los modelos), con tal de debuggear y hacer pruebas rápidas
