### ISSUE TITLE
Problemas Set-Up Mac

### ISSUE THREAD

**Issue by nicoolivaresm** [IIC2143/Syllabus#11]
Hola, todavía no logro hacer el setup, estoy teniendo problemas con la instalación de Postgresql. Todavía no puedo empezar la tarea por este problema.

<img width="564" alt="Captura de pantalla 2023-03-18 a la(s) 16 03 34" src="https://user-images.githubusercontent.com/106032490/226139983-78f6b9d3-e0f7-437c-98c0-0bdec569684e.png">

**Comment by jpsandoval** [comment]
Hola, vimos contigo este problema en clase, en mac, tienes que poner la version de postgresql a instalar, idealmente puedes utilizar la 15, o 14. Un saludo,
