### ISSUE TITLE
Error al eliminar una cancha que tiene reseñas relacionadas

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#110]
Hola! en mi proyecto manejo canchas, con reservas y reseñas. Estaba tratando de borrar una cancha, pero me tiró el siguiente error:
![Captura de Pantalla 2022-10-18 a la(s) 15 04 19](https://user-images.githubusercontent.com/89275951/196509538-4b05c968-c10b-48a2-906a-67c5d560b168.png)

**Comment by simonmb12** [comment]
El problema es que la cancha tiene una reseña creada. Las canchas que no tienen reseñas me deja borrarlas sin problema.

**Comment by meretamal** [comment]
Hola 😁 , si es que las reseñas y reservas no pueden "existir" sin una cancha, podrías agregarle el flag `dependent :destroy` a la asociación. Este es un ejemplo de la documentación:

```ruby
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

class Book < ApplicationRecord
  belongs_to :author
end
```
