### ISSUE TITLE
Heroku: we're sorry, but something went wrong

### ISSUE THREAD

**Issue by rdgonzalez1** [IIC2143/Syllabus#111]
Hola, seguimos con problemas para que nuestra app se vea bien en Heroku, probamos literalmente todo, "heroku run rails db:migrate" , "heroku run rake db:migrate" y derivados de ese comando ya que vimos una issue en que a varios les paso lo mismo y se les solucionaba con eso. Nuestra app funciona bien de forma local por los que nos dijeron que probablemente era un problema de la base de datos pero no hemos podido solucionarlo.
<img width="494" alt="Captura de Pantalla 2022-10-18 a la(s) 18 21 46" src="https://user-images.githubusercontent.com/69658236/196548615-0a01ab28-8754-41a3-bdfc-36b576b64614.png">
<img width="1040" alt="Captura de Pantalla 2022-10-18 a la(s) 18 21 51" src="https://user-images.githubusercontent.com/69658236/196548623-c7a7e95f-3e70-4bfb-808c-f4ec85efa83c.png">

**Comment by meretamal** [comment]
Hola 😁 , puede ser por distintos motivos. Podrías mandar el contenido de tus logs al caerse tu app?
