### ISSUE TITLE
Problema cambiando link_to a button_to

### ISSUE THREAD

**Issue by piriabud** [IIC2143/Syllabus#119]
Hola, actualmente estamos usando un link para pasar desde /index con una tabla que muesta las peticiones del usuario a la opción de crear una nueva petición en /new. El código usando link es el siguiente:

`<%= link_to 'Upload a new petition', petitions_new_path %>`

Con el código anterior la página fluye y no genera ningún error

Queremos cambiar estos links azules por botones usando bootsrtap. Leí en algunos stackoverflow que se puede cambiar el `link_to` por un `button_to` y agregar clases utilizando un código como este:

`<%= button_to 'Upload a new petition', petitions_new_path, {class: 'btn btn-success'}%>`

Sin embargo, con este código nuevo, la página se cae y arroja el siguiente error: **No route matches [POST] "/petitions/new"**

Ambos métodos llevan al mismo path, por lo que no entiendo por qué con uno se cae y con el otro no. ¿Alguna ayuda/recomendación?

**Comment by meretamal** [comment]
Hola, eso es porque `link_to` por defecto hará un request con GET, cuando `button_to` lo hará con POST, por lo que termina levantándose el error que mencionas.

Para arreglarlo puedes especificar el método a utilizar de la misma forma como se hace en un `link_to`.
