### ISSUE TITLE
Error al crear la BDD (db:migrate)

### ISSUE THREAD

**Issue by m9use** [IIC2143/Syllabus#12]
![Captura de pantalla 2024-03-15 164502](https://github.com/IIC2143/Syllabus/assets/111007927/9c79fcf0-5691-4908-885f-027ff9463312)

Este error me sale cuando uso el comando rails db:migrate 

rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?

Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?

Tasks: TOP => db:migrate

No encuentro la solución en ningún foro. Ayuda pls

**Comment by noamsito** [comment]
Lo más probable es que no haya encendido el postrgresql. Así que prueba iniciando el postgresql y ejecuta nuevamente el comando de rails "db:migrate".

En caso de que no sea eso, podría ser que no haz creado la base de datos correspondiente al proyecto en el que estás trabajando.

**Comment by m9use** [comment]
Gracias
