### ISSUE TITLE
Problemas parte 12 instalación: role does not exist

### ISSUE THREAD

**Issue by Crisax234** [IIC2143/Syllabus#12]
Hola, tengo un problema al momento de abrir la página local host luego de correr el servidor con el comando ```rails s```,  me aparece el error que adjuntare y que el nombre de usuario que cree al instalar ubuntu no existe, he intentado cambiar varias cosas pero no logro solucionarlo, que podría ser?

![image](https://user-images.githubusercontent.com/88630837/184559083-bdca88a3-e202-4499-be68-b00a3bc3b51b.png)

**Comment by meretamal** [comment]
Hola 😁 , podrías adjuntar el error que te sale al abrir la página?  Es la parte que sale arriba de la sección a la que le sacaste el _screenshot_.

**Comment by Crisax234** [comment]
Aqui esta
![image](https://user-images.githubusercontent.com/88630837/184559423-a6839d0a-8fe5-4790-a0e6-59d900482da6.png)

**Comment by meretamal** [comment]
Ese error dice que no existe un usuario llamado así en tu servicio de postgres (no es tu usuario de ubuntu) En el [paso 7](https://github.com/IIC2143/Syllabus/wiki/Setup-Ubuntu---Windows#7-postgresql-superuser) de la guía de _setup_ se explica cómo crearlo.

**Comment by Crisax234** [comment]
Si si ya realicé ese paso y me funcionó, cree el usuario con el mismo nombre que tiene mi usuario de sistema, no he vuelto a colocar el nombre de usuario de ubuntu luego de instalar ubuntu, por eso no entiendo entonces por qué toma ese nombre de usuario

**Comment by meretamal** [comment]
Podrías ingresar a una consola de psql, correr `\du` y mandar lo que te sale?

**Comment by Crisax234** [comment]
![image](https://user-images.githubusercontent.com/88630837/184560224-1bcf3329-166b-4f0d-a182-47c95cb6122c.png)

**Comment by meretamal** [comment]
Si te fijas, el usuario es que creaste se llama crist, mientras que en tu proyecto estás intentando usar uno que se llama crisaxhola

**Comment by Crisax234** [comment]
en el archivo env efectivamente coloque el nombre de usuario crist y no el de ubuntu, por eso no entendia que apareciera ese nombre en la pagina web

**Comment by meretamal** [comment]
Y el .env está en la raiz de tu proyecto (al mismo nivel que tu Gemfile). Lo que pasa es que, si es que no se está leyendo tu .env, `ENV["DB_USER"]` va a retornar `nill` y postgres, por defecto, intentará usar un usuario con el mismo nombre que el usuario de tu sistema (crisaxhola), entonces puede pasar que no se esté leyendo correctamente tu archivo .env.

**Comment by Crisax234** [comment]
Parece que logré solucionar el problema anterior sin embargo al entrar a la pagina ahora me sale este error : 
![image](https://user-images.githubusercontent.com/88630837/185007231-fb697abd-23fc-4d26-bc6d-79687318e220.png)

**Comment by meretamal** [comment]
Eso es porque no está corriendo tu servicio de postgres (o si lo está, no lo está haciendo en el puerto 5432, que es en el que corre por default).

**Comment by Crisax234** [comment]
Corri el comando para iniciar postgres y me salio el mismo error de antes tengo el archivo .env de esta forma (imagen abajo) también lo intenté cambiar a la otra carpeta app pero tampoco funciona. 
![image](https://user-images.githubusercontent.com/88630837/185010151-eb00c25a-90fb-4a43-b333-e3639e9377dc.png)

**Comment by meretamal** [comment]
Dentro de una consola de psql podrías correr `\conninfo` y mandar qué te sale?

**Comment by Crisax234** [comment]
![image](https://user-images.githubusercontent.com/88630837/185012735-a70861c1-7a3b-4b45-81f4-5549606be9ed.png)

**Comment by meretamal** [comment]
Podrías intentar agregar lo siguiente a tu Gemfile, luego correr `bundle install` y después ver si se lee bien tu archivo .env?
```ruby
gem 'dotenv-rails', groups: [:development, :test]
```

**Comment by Crisax234** [comment]
Hice todo lo que dijiste pero aun así me sigue saliendo el mismo error :(
![image](https://user-images.githubusercontent.com/88630837/185017320-add485ff-fa68-4088-aeb7-3fdc9b9ce13e.png)

**Comment by meretamal** [comment]
Te parece si coordinamos una pequeña llamada por meets y lo vemos directamente por ahí? Creo que así será más fácil para cachar el error. Te dejo mi telegram por si apañas @meretamal. De todos modos, debería haber una sesión de troubleshooting la próxima semana para ayudarlos con errores que sigan teniendo con el setup.

**Comment by meretamal** [comment]
Hola 😁 , para los que tengan un problema similar y no les haya funcionado ni una de las soluciones anterior, el problema era que no se había configurado bien el archivo **database.yml** con el código de la guía y por algún motivo tampoco se leían bien las variables de entorno, para lo cual se siguió [este setup](https://github.com/bkeepers/dotenv#note-on-load-order) de dotenv.
