### ISSUE TITLE
Problema con base de datos Tarea

### ISSUE THREAD

**Issue by vickyvd** [IIC2143/Syllabus#12]
Hola! 
Estaba siguiendo los pasos que aparecen en la setup-guide para empezar la tarea y al hacer db:create o db:migrate me tiraba el siguiente error:
![Captura de pantalla 2024-08-14 220715](https://github.com/user-attachments/assets/6a0349d6-2bbf-4f71-8374-d83ba04f0b5f)
Desinstalé y volví a instalar postgresql pero el error persistía. Por lo que entiendo del error, se esperaba correr psql en un directorio tmp pero este no existía.
Buscando en internet, encontré la siguiente solución: agregar en el archivo database.yml host: /var/run/postgresql
Y eso lo arregló. Como se puede ver en la imagen después si pude crear la basa de datos y podido crear los modelos y agregar objetos sin problemas.
Mi pregunta, ¿es esta solución valida? porque lo que entiendo es que en el archivo de database agregé el path a donde tengo instalado postgresql, pero me entra la duda de si funcionará al momento de la revisión ya que puede ser que ese no sea el path correcto en otro computador. ¿Existe alguna otra forma de solucionar el problema?
Muchas gracias!

**Comment by FelipeMunozMoraga** [comment]
Hola, en el error que muestra sale que tu BDD se llama <GamersAPI>_development. Probaste a crearla sin <> en el nombre? Igualmente si deseas saber si tu solución está ok, ya está disponible el tester para que ustedes puedan probar si las solicitudes conectan con su solución.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> Hola, en el error que muestra sale que tu BDD se llama _development. Probaste a crearla sin <> en el nombre? Igualmente si deseas saber si tu solución está ok, ya está disponible el tester para que ustedes puedan probar si las solicitudes conectan con su solución.

Holaa perdón pero donde está el tester? Que no lo he podido encontrar :c

**Comment by FelipeMunozMoraga** [comment]
El tester está en github 😄 si vas a la organización del curso deberías poder encontrarlo, igualmente el link es https://github.com/IIC2143/Tester-Tarea-2024-2

**Comment by VicenteIgnacioSotoGonzalez** [comment]
> El tester está en github 😄 si vas a la organización del curso deberías poder encontrarlo, igualmente el link es https://github.com/IIC2143/Tester-Tarea-2024-2

Ahhh perfecto, pensé que estaba en el Syllabus, por eso no lo pillaba, muchas gracias!

**Comment by vickyvd** [comment]
> Hola, en el error que muestra sale que tu BDD se llama _development. Probaste a crearla sin <> en el nombre? Igualmente si deseas saber si tu solución está ok, ya está disponible el tester para que ustedes puedan probar si las solicitudes conectan con su solución.

Hola! Probé los tests y mi solución funciona ya que corrieron, pero seguía con la duda de si mi código correría en otro pc que tenga instalado postgres en otro path. Fui el viernes a la ayudantía y uno de los ayudantes bajó mi tarea e intentó correrla en su pc y no le corría. Al borrar la línea de código le corrió pero los test no salieron buenos mientras que en mi pc si salían buenos. 

Hoy día respalde mi tarea y borré todo (postgres, ruby, rvm, etc) y volví a instalarlos siguiendo los pasos de la setup guide y volví a crear la tarea. Esta vez le puse a mi bdd un nombre sin <> pero el error persistía y solo logré solucionarlo con la línea de código que mencioné antes host: /var/run/postgresql en database.yml. La tarea funciona bien en mi pc (los test corren), pero no se si en algún otro lo haga. La verdad es que sigo sin estar segura el porqué del problema ya que seguí los pasos de la guía y no he sabido de nadie más con ubuntu que haya tenido el problema. No se si tienen alguna recomendación de que hacer.

Muchas gracias!

**Comment by FelipeMunozMoraga** [comment]
Se conversó este tema con la alumna por correo
