### ISSUE TITLE
Ayudantía arquitectura

### ISSUE THREAD

**Issue by ValeeRamirez** [IIC2143/Syllabus#120]
Hola, podrían subir la grabación de la ayudantía del viernes pasado? No alcance a procesar todo.
Gracias!

**Comment by meretamal** [comment]
Hola 😁, el plan original del semestre era no subir las ayudantías, dado que ya se están haciendo por zoom para facilitar la asistencia, tomando en cuenta que el horario que tenemos no es el mejor. De todos modos, se tomó la decisión de empezar a subirlas, con la condición de que se mantuviera la buena asistencia que había hasta el momento, lo cual se informó en un anuncio.

A la ayudantía pasada fueron 15 alumnos de cerca 250, razón por la cual, siendo consistente con la información que les dimos, no se ha subido el video (pero sí el material utilizado).
