### ISSUE TITLE
Duda respecto a contenido de estimaciones en la i1

### ISSUE THREAD

**Issue by FabriRandon** [IIC2143/Syllabus#121]
Estimados,
Tengo una duda respecto a la pauta de la i1 en la pregunta 3 parte b. Nos piden que cuantifiquemos el tamaño y duración del proyecto, sin embargo en la pauta se nos pide calcular esfuerzo (semanas hombres), siendo que este es un contenido que corresponde a la materia de estimaciones y tenía entendido que dicho contenido quedó afuera de la i1 y que por ello es que va a entrar en la i2 del día Jueves.
Saludos y muchas gracias.

**Comment by ValeeRamirez** [comment]
Hola, yo tenía la misma duda!

**Comment by ealv-nms** [comment]
significaría que se puede recorregir por esto?

**Comment by isufan** [comment]
> Hola 😁 , sobre la pregunta 3, toda esa materia, a excepción del cálculo del esfuerzo, se vio en clases que entraban para la I1.
> 
> En la sección 1:
> 
> * En los apuntes del profesor se encuentran explicados los tipos de ajustes.
> * En la presentación 9, se encuentra explicada toda esa materia, incluyendo story points y estimaciones.
> * En la slide 32 se hizo un ejemplo similar al de la prueba.
> 
> En la sección 2:
> 
> * Se mostró un ejemplo de planificación en la slide 43,44, 45, 008-Planeación.
> * Asimismo, en la slide 49  (008-Planeación), se explicó la negociación por alcance y por tiempo.
> * Además, esas preguntas también se vieron en el repaso para la I1, como se ve en la slide 32,33,34,35.
> * Finalmente, en la clase de repaso para la I1, se hizo un ejercicio adicional sobre planificación y negociación por alcance y tiempo.
> 
> En el caso de que hubieran tenido un **descuento en el cálculo del esfuerzo** en la 3.b, pueden mandar a recorregir.
> 
> Por último, tomen en consideración que la materia es acumulativa, por lo que se podría llegar a preguntar materia de la I1 en la I2, haciendo énfasis en lo que no se ha evaluado.

En caso de mandar a recorregir la 3.b, ¿qué determinación se tomará? ¿Se coloca puntaje completo, se elimina la pregunta u otra?

**Comment by meretamal** [comment]
La pregunta como tal no se aleja de los contenidos de la I1. Parte del puntaje asignado es por cuantificar el tamaño y duración del proyecto, lo cual se puede hacer sin calcular las horas hombre, por lo que no se debería eliminar la pregunta.

Como les dije, si es que se les hizo un descuento por no calcular el esfuerzo, pueden mandar a recorregir, pero esto no implica que obtendrán el total de la pregunta, ya que justamente esta hubiera sido solo una parte de esta.
