### ISSUE TITLE
Problema con el testing

### ISSUE THREAD

**Issue by martina-abello** [IIC2143/Syllabus#121]
La página de mi grupo está bien, pero cuando trato de correr cualquier test me sale siempre este error:
![imagen](https://github.com/IIC2143/Syllabus/assets/128489585/da5a88d5-54a0-4ea0-bc38-7c93ba498e3e)
y cuando digo cualquier test me refiero a que pasa aunque esté testeando esto:
![imagen](https://github.com/IIC2143/Syllabus/assets/128489585/936b4af1-5805-47f5-bdc4-29f2273b0d1e)

Si alguien me pudiera ayudar lo agradecería mucho :(

**Comment by vice-rosas99** [comment]
a mi me pasa exactamente lo mismo, pudiste arreglarlo?

**Comment by martina-abello** [comment]
Siii, revisa las fixtures! Se me habían creado unas de actividades automáticamente y eran. well. estaban mal hechas. No tenían todos los atributos, otros no tenían valores válidos...  las borré y me resultó

**Comment by vice-rosas99** [comment]
buena, hice lo mismo y me resultó. Marditas fixtures xd. Gracias
