### ISSUE TITLE
Solicitud extensión de plazo Sprint 3

### ISSUE THREAD

**Issue by victoriaatria** [IIC2143/Syllabus#123]
Hola,
Quería saber si existe la posibilidad de extender el plazo del sprint 3 del proyecto, ya que el plazo para desarrollarlo ha calzado con varias interrogaciones de otros ramos, además de que se piden implementar varios aspectos complejos.

Gracias de antemano!

Saludos

**Comment by OrregoSilva** [comment]
¡Hola! Estoy redactando un anuncio al respecto, en unos minutos les deberá salir en Canvas

**Comment by victoriaatria** [comment]
Muchas gracias!
