### ISSUE TITLE
SetUp Mac - Error en comando gem install rails -v 6.0

### ISSUE THREAD

**Issue by naderhadweh** [IIC2143/Syllabus#13]
Holaa, cuando ingreso al setup de mac en la wiki del curso no aparece nada. Fuera de eso seguí los pasos de instalación del semestre pasado (https://github.com/IIC2143-2021-2/Syllabus/tree/main/Gu%C3%ADas/Setup) pero cuando intento instalar rails con gem install rails me tira este error, que puedo hacer?

Gracias!!

![Captura de Pantalla 2022-03-18 a la(s) 23 04 05](https://user-images.githubusercontent.com/89283382/159135822-cc5035bb-d975-4812-bd01-0c95bd54e861.png)
?

**Comment by cadaeic314** [comment]
Hola!, no soy ayudante, pero si no me equivoco el error proviene de tratar de instalar la versión 7.0 de rails, la cual no es compatible con ruby 2.6. Debes de instalar la versión 6.0 que es la del curso, con el comando

`gem install rails -v 6.0`

**Comment by naderhadweh** [comment]
Buenaa muchas gracias, ahora lo intenté pero me tira otra cosa

![Captura de Pantalla 2022-03-19 a la(s) 19 58 20](https://user-images.githubusercontent.com/89283382/159141251-e5386d09-a0ac-46ed-a9c8-4321b482d319.png)

**Comment by JosefaPaz** [comment]
¡Hola! @naderhadweh 

Primero, recuerda ser más descriptivo con el nombre de la issue, para que podamos ayudarte de manera más fácil (le cambiaré el nombre para que veas un buen ejemplo de nombre!)

Acabo de subir la guía actualizada a la wiki, para que sigas trabajando con esa!

Respecto a tu error, puede que haya quedado mal instalado el `rvm`, te recomiendo intentar instalarlo de nuevo, cerrar la consola y correr nuevamente el comando.

¡Quedo atenta! :)
