### ISSUE TITLE
Parte 3 rutas de acceso: URL errónea

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2143/Syllabus#13]
Hola ! En el 3.1 se nos pode que la ruta sea en base a "/player", mientras que para el resto se nos pide "/players", esto es intencional o es un error de tipeo?

**Comment by FelipeMunozMoraga** [comment]
Hola, muchas gracias por hacernos notar el error! durante el día de mañana revisaremos nuevamente y en detalle el enunciado para cambiar todo posible error de tipeo, afortunadamente no se trata de un error significativo por lo que espero que no haya sido de mucha inconveniencia!
Nuevamente gracias y saludos!
