### ISSUE TITLE
Problemas Para Instalar Ubuntu (Windows Home)

### ISSUE THREAD

**Issue by ignaciaurrutia** [IIC2143/Syllabus#13]
Hola, no me deja instalar Ubuntu como corresponde porque me dice que necesita unos requisitos de Hyper-V. Investigando un poco me di cuenta de que solo se puede ajustar esta función con Windows Pro. ¿Qué hacemos si solo tenemos Windows 10 Home Single Language? (Tanto en el video como en la guía tutorial que subieron se necesita Pro)

**Comment by OrregoSilva** [comment]
Hola! Que te dice la consola (PowerShell) si ejecutas `wsl --status`?

**Comment by ignaciaurrutia** [comment]
Tuve que comprar Windows Pro, así que ya no es problema. Gracias de todas formas.

**Comment by Juancagp** [comment]
hola! yo estoy teniendo los mismo problemas y cuando ejecuto wsl --status me aparece lo siguiente:

Versión predeterminada: 2
Habilita la característica Plataforma de máquina virtual de Windows y asegúrate de que la virtualización esté habilitada en el BIOS.
Para obtener más información, consulta https://aka.ms/wsl2-install

**Comment by Juancagp** [comment]
logré habilitar lo que me pedían y al parecer ya me funciona ubuntu.
