### ISSUE TITLE
problema para clonar repositorio

### ISSUE THREAD

**Issue by catalinaortegacalderon** [IIC2143/Syllabus#14]
hola! 

al tratar de clonar mi repositorio con mi usuario y mi personal access token me sale el siguiente error en consola:

remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/IIC2143/2023-1-Tarea-Catalinaortegacalderon.git/': The requested URL returned error: 403

Mi personal access token lo configuré con acceso a todo. Que estoy haciendo mal?

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! Es posible que no dieras ese permiso al crear la token, intenta crear una nueva token y chequear todas las cajitas. 

Avísame si te resulta 😄

**Comment by catalinaortegacalderon** [comment]
estaba creando un beta token en vez de uno normal, ahora me funcionó, gracias!
