### ISSUE TITLE
[Tarea] Nombres de Archivos

### ISSUE THREAD

**Issue by 0DASAC** [IIC2143/Syllabus#14]
hola, leyendo el ítem 8 del enunciado no me quedo claro cual debe ser el nombre de las carpetas y los archivos.

**Comment by maggiemunoz** [comment]
Hola! Los nombres pueden ser cualquier cosa, ya que los ayudantes ejecutarán el comando según los nombres que le pongas. Lo único que importa es que el archivo a ejecutar se llame main.rb, y que la estructura del repositorio sea la mostrada en el enunciado (es decir, una carpeta con los csv, y los otros archivos sueltos.)
