### ISSUE TITLE
Qué hacer si ya tengo Ubuntu?

### ISSUE THREAD

**Issue by Dafnemami** [IIC2143/Syllabus#14]
Hola!,

Si ya tengo ubuntu y windows en el pc (disco particionado). Debo seguir este manual[https://github.com/IIC2143/Syllabus/wiki/Setup-Ubuntu---Windows#1-instalar-wsl] desde el paso 2? 

Saludos!!🐧

**Comment by meretamal** [comment]
Hola 😁 . Sí,  esa guía es para que hagan el _setup_ en ubuntu (o en wsl si es que tienen windows).
