### ISSUE TITLE
Error tabla duplicada

### ISSUE THREAD

**Issue by santiago3c** [IIC2143/Syllabus#14]
Hola, al intentar hacer el migrate al crear los modelos, me aparecía el error:
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR: relation "teamAs" does not exist

Intenté hacerlo como decían en otra issue, pero no me funcionó. Entonces eliminé la carpeta SoccerApi de mis carpetas y creé una nueva. Después creé el modelo de Team, y luego intenté hacer el migrate, pero me sale el siguiente error:
santiago@Santiago-hp:~/SoccerApi$ rails db:migrate                                                                      == 20240316190111 CreateTeams: migrating ======================================                                         -- create_table(:teams)                                                                                                 rails aborted!                                                                                                          StandardError: An error has occurred, this and all later migrations canceled:                                                                                                                                                                   PG::DuplicateTable: ERROR:  relation "teams" already exists                                                             /home/santiago/SoccerApi/db/migrate/20240316190111_create_teams.rb:3:in `change'                                                                                                                                                                Caused by:                                                                                                              ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "teams" already exists                             /home/santiago/SoccerApi/db/migrate/20240316190111_create_teams.rb:3:in `change'                                                                                                                                                                Caused by:                                                                                                              PG::DuplicateTable: ERROR:  relation "teams" already exists                                                             /home/santiago/SoccerApi/db/migrate/20240316190111_create_teams.rb:3:in `change'                                        Tasks: TOP => db:migrate                                                                                                (See full trace by running task with --trace) 

hice rails destroy migration CreateTeams y también rails destroy model Team pero me sigue pasando lo mismo y no sé cómo solucionarlo...

**Comment by santiago3c** [comment]
parece que ahí me funcionó usando dropdb para SoccerApi_development y SoccerApi_test, y luego haciendo rails db:create

**Comment by jrodriguezluna** [comment]
Otra opción es usando `rails db:reset` así no tienes que volver a crear la database !

**Comment by santiago3c** [comment]
gracias, para la próxima!
