### ISSUE TITLE
Problemas parte 12: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by fsazo** [IIC2143/Syllabus#15]
Holaa, tengo un problema con el paso 12. Al correr el servidor me sale el siguiente error.
<img width="776" alt="image" src="https://user-images.githubusercontent.com/80927077/184793456-542f52aa-14c2-4bfb-ab1b-c59590a155a4.png">

Pero si pongo mis credenciales directamente en database.yml si me funciona. También revise la issue numero 12 y si estaba usando el user correcto. Como podría arregarlo?
Gracias de antemano

**Comment by meretamal** [comment]
Hola, es probablemente porque no se está leyendo correctamente tu archivo .env o que las variables de tu archivo no se llamen igual a las que estás usando en tu database.yml.

Por favor revisa que todo lo anterior este bien, incluyendo que el archivo donde tienes tus credenciales se llame **.env** y esté en la raíz de tu proyecto.

**Comment by fsazo** [comment]
Ahora me funcionó al instalar la gema dotenv por algo que encontré en internet. Era necesario?
