### ISSUE TITLE
Setup Mac

### ISSUE THREAD

**Issue by jtvaldivia** [IIC2143/Syllabus#15]
Hola,
No me sale nada en la pagina de setup para mac en la wiki. Pueden revisarlo para saber si es error de mi computador o si no hay nada todavia en la wiki. 
Gracias

**Comment by JosefaPaz** [comment]
¡Hola! @jtvaldivia 

Ya está el setup arriba, se le estaban haciendo algunas modificaciones. El lunes mandaré anuncio comentando que todo está disponible :)
