### ISSUE TITLE
Error en request al querer crear vacuna

### ISSUE THREAD

**Issue by Lexiesm** [IIC2143/Syllabus#15]
Hola buenas! en el postman al querer crear la primera vacuna me sale esto:
![imagen](https://user-images.githubusercontent.com/101207522/226958037-2e52ce84-0a7d-47cb-963b-eb6f72e53214.png)
![imagen](https://user-images.githubusercontent.com/101207522/226958133-e1d090cc-0891-4193-9ed6-df242a810823.png)

a que podría deberse?

gracias!

**Comment by OrregoSilva** [comment]
Una opción es que no estás ejecutando los tests en el orden que corresponde o pides un usuario que no existe, los tests están pensados en que pueden crear información que será pedida más adelante por otro test.

**Comment by Juan-Carlos-Ferrer-Barros** [comment]
Estoy teniendo el mismo problema, pero me sale error 500. No he podido solucionar el problema. Las personas se me están creando bien, pero me di cuenta que cada vez que corro el Request, se eliminan todas las personas de la base de datos pero el :id no se "reinicia" (la siguiente persona que creo parte desde la última eliminada +1, no desde el id 1). Tendrá esto algo que ver con el error? O es irrelevante para el problema?

Gracias!

**Comment by Lexiesm** [comment]
@OrregoSilva si, al final lo solucioné el viernes en la sala ayuda, gracias!
