### ISSUE TITLE
Response body

### ISSUE THREAD

**Issue by tomastrivino** [IIC2143/Syllabus#16]
Hola!
Me confunde un poco lo sgte:
<img width="539" alt="image" src="https://github.com/IIC2143/Syllabus/assets/98418205/c5eb5e04-74bf-49bd-9c1d-e6ccf1767bba">

Ocurre que los response body son distintos en ambos casos. Dicho esto, no sé si usar `response json: {}`, `response json: []` o `head :no_content` (este último hace que no se reciba ni `[]` ni `{}`). ¿El que esos response body sean distintos es intencional? ¿Me podrían aclarar esto por favor?

**Comment by tomastrivino** [comment]
A todo esto, `GET /matches/:team` y `GET /teams/:team_id/matches` son lo mismo?

**Comment by noamsito** [comment]
Efectivamente es intencional que sean distintos las responses, por lo tanto debes retornar [] y {} en sus casos respectivos.

**Comment by FelipeMunozMoraga** [comment]
con respecto a la segunda pregunta, GET matches/:team busca en base a el nombre de el equipo, si te fijas en el ejemplo :team es Cobreloa, mientras que GET teams/:team_id/matches usa el id
