### ISSUE TITLE
Llamado de Métodos

### ISSUE THREAD

**Issue by 0DASAC** [IIC2143/Syllabus#17]
hola, no me queda claro si nosotros debemos llamar a los métodos en el main. y de ser así que valor debemos darle al parámetro criterio. además si nosotros llamamos a los métodos, ¿podemos agregar parámetros a los métodos?

**Comment by maggiemunoz** [comment]
Hola! Si, ustedes deben llamar a los métodos según lo indicado en instructions.txt, el valor del parámetro criterio justamente depende de la instrucción. 

Pueden agregar todos los parámetros extra que consideren necesarios siempre y cuando al ejecutarse el archivo se logre el output indicado, aunque no debería ser necesario.
