### ISSUE TITLE
Problema parte 5 instalación: Error running '__rvm_make -j4'

### ISSUE THREAD

**Issue by lcamusm** [IIC2143/Syllabus#17]
![Captura de pantalla (73)](https://user-images.githubusercontent.com/89416249/185231264-d71a3a74-fad4-4e22-9365-47a0e8e79e09.png)
Hola! Al tratar de instalar Ruby, me tira este error y no se que significa ni como solucionarlo :/

**Comment by kunafuego** [comment]
Hola! Te dejo links a otras issues que tratan el mismo problema y tienen muchas posibles soluciones, para que veas si te sirve alguna!
[Issue 1](https://github.com/IIC2143/Syllabus-2022-1/issues/21)
[Issue 2](https://github.com/IIC2143/Syllabus/issues/11)

Avísame si sigues con el problema!

**Comment by lcamusm** [comment]
Hola! Trate de ocupar brew doctor, pero me aparece que no existe. No se que más se puede hacer.

**Comment by Franbelen** [comment]
estoy en las mismas :(
