### ISSUE TITLE
[PARTE 3 p.7] Error ForeignKeyViolation tras intentar eliminar el equipo

### ISSUE THREAD

**Issue by mon-b** [IIC2143/Syllabus#17]
Hola! En la 7 de la parte 3, qué pasa con los partidos en las que participa el equipo que se desea eliminar? tb se eliminan?

![Screenshot 2024-03-17 at 07 29 53](https://github.com/IIC2143/Syllabus/assets/125843723/ea6d4f2f-d72a-446e-924d-95d6c53deaf0)
 
Pregunto porque me sale este error (que tiene sentido ya que estoy intentando eliminar un equipo que está siendo referenciado en la tabla de partidos):

ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "teams" violates foreign key constraint "fk_rails_694543d19c" on table "matches"
DETAIL:  Key (id)=(6) is still referenced from table "matches".
):

por lo mismo, no sé de qué manera debería manejar este delete. 

Muchas gracias de antemano!

**Comment by mon-b** [comment]
De hecho, ahora que lo veo bien, los métodos DELETE de la parte 1 me dejaron de funcionar debido al mismo error :( –entiendo por qué pasa pero no sé cómo se espera que manejemos estos casos ya que no lo dice en el enunciado–

**Comment by danilarco** [comment]
Hola! Efectivamente si se borra un equipo, se deben eliminar todos los partidos asociados a este. Para esto debes fijarte en las dependencias en los archivos de los modelos.

**Comment by mon-b** [comment]
Solo para confirmar, los jugadores asociados al equipo tb se eliminarían?

**Comment by danilarco** [comment]
Así es!

**Comment by tomastrivino** [comment]
Hola, @danilarco , si elimino un jugador debería eliminar el equipo al que está asociado?

**Comment by danilarco** [comment]
@tomastrivino en este caso no, ya que un equipo puede tener varios jugadores (has many) pero un jugador solo pertenece a un equipo (belongs to one). Yo recomiendo pensar estos casos lógicamente, por ejemplo acá no tiene sentido que haya un jugador que pertenezca a un equipo que no existe, pero un equipo perfectamente puede existir si se borra un jugador asociado a él. En todo caso, recomiendo enfocarse más que nada en hacer bien las dependencias entre los modelos en sus respectivos archivos en la carpeta models ya que con eso basta!
