### ISSUE TITLE
Problemas con el nombre 'Vaccine'

### ISSUE THREAD

**Issue by Vjyhgv** [IIC2143/Syllabus#17]
Cuando cree la api, le puse "rails new vaccine --api", por lo que ahora al crear el model Vaccine, me esta poniendo problemas porque el nombre "Vaccine" ya esta ocupado. Voy a ocupar como model vaccine1, ¿es un problema eso para la corrección?, si es así ¿que debería hacer?

**Comment by OrregoSilva** [comment]
No debería ser un problema, lo importante es que las rutas puedan devolver el resultado que les pedimos en el enunciado.
