### ISSUE TITLE
Inconsistencia nombre de atributos

### ISSUE THREAD

**Issue by tomas-jackson** [IIC2143/Syllabus#18]
En la descripcion de los modelos se describe que el model Player debe tener lo siguiente:
<img width="870" alt="image" src="https://github.com/IIC2143/Syllabus/assets/127408636/d45ee134-f8e6-4b54-9686-68f4f8f4dc5e">
Pero en el ejemplo de la parte 3.1, los atributos aparecen como:
<img width="797" alt="image" src="https://github.com/IIC2143/Syllabus/assets/127408636/63fa4a16-ba88-49d9-8d01-5301fdba1cd2">
Con cual nombre para el atributo del equipo debemos quedarnos? team o team_id?
Espero su respuesta

**Comment by jrodriguezluna** [comment]
creo que sería team porque el modelo y el body response pueden ser distintos :thinking: (no estoy seguro, pero antes mencionaron algo parecido en relación al modelo Match y el body response que da al hacer consultas, creo que en ese caso el body response debería decir por ej teamA mientras que el modelo lo tiene como teamA_id)

**Comment by FelipeMunozMoraga** [comment]
Hola! Efectivamente pueden tener nombres distintos, como consejo te diría que la revisión de la tarea mira los response body, por lo que si estos se salen iguales a los esperados, está todo ok! 😄
