### ISSUE TITLE
Problemas parte 12: peer authentication failed for user "felip"

### ISSUE THREAD

**Issue by Felopo** [IIC2143/Syllabus#18]
Holaa, tengo un problema cuando abro la página que me sale el siguiente error: 

FATAL: peer authentication failed for user "felip"  (en la típica pantalla roja de los errores de PG::ConnectionBad)

Uso windows con WSL2 y seguí todo el tutorial de la wiki.
He estado tratando varias cosas que vi en internet, pero ninguna ha funcionado. 
Gracias de antemano.

**Comment by meretamal** [comment]
Hola 😁. Eso se debe a que postgres tiene distintos tipos de autenticación. Los más típicos son:

1. `trust`: no es necesario que le pases una contraseña al ingresar con un usuario
2. `md5`: es necesario que le pases una contraseña al ingresar con un usuario
3. `peer`: es necesario que ingreses con un usuario que se llame igual al usuario de tu sistema

En ubuntu por lo general puede venir configurado `md5` o `peer` (el último debe ser tu caso).

Prueba creando en postgres un usuario con con el mismo nombre que el usuario de tu sistema y usa ese para configurar tu base de datos del proyecto.

**Comment by Felopo** [comment]
Ahí funcionó!! Gracias!
