### ISSUE TITLE
Formato de Entrega Tarea 1

### ISSUE THREAD

**Issue by aboehmg** [IIC2143/Syllabus#18]
¡Hola!
Tengo una duda respecto a cómo se entrega la tarea. ¿Es suficiente con que tenga todos los archivos de rails dentro del repositorio 
Me entra la duda porque cuando creamos un nuevo proyecto le ponemos un nombre a la carpeta donde queremos que estén contenidos todos los archivos. ¿Subo toda la carpeta y todos sus contenidos? ¿O elimino la carpeta y que aparezcan de forma inmediata cuando se entra al repositorio?
¡Gracias de antemano!

**Comment by OrregoSilva** [comment]
Puedes guiarte por el [proyecto ejemplo](https://github.com/IIC2143/Proyecto-Ejemplo) para saber como se entrega. Si tu proyecto quedo dentro de otra carpeta, tienes que mover todo su contenido para que quede afuera de esta
