### ISSUE TITLE
SetUp Windows - Error en comando gpg2 --keyserver hkp://keys.gnupg.net --recv-keys

### ISSUE THREAD

**Issue by ArielGoldzweig** [IIC2143/Syllabus#18]
Hola! Seguí los pasos de la guía de instalación para Windows pero cuando corro el comando ```gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB``` me aparece este error:

![image](https://user-images.githubusercontent.com/80789622/159183293-219d7c95-fcbc-41f6-9caf-2ac57c6b462e.png)

Que puedo hacer?

**Comment by felipefuentesporras** [comment]
keyserver.ubuntu.com
keys.openpgp.org
pgp.mit.edu

Intenta reemplazando "hkp://keys.gnupg.net" por cualquiera de las opciones anteriores.
Ej:  gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

**Comment by MaxWhiting** [comment]
hola me paso esto mismo pero en mac, es la misma solución?

**Comment by ElTioAndresCabezas** [comment]
@MaxWhiting Debería
(Nota: No soy ayudante)
