### ISSUE TITLE
Error en test 2 al crear vacuna

### ISSUE THREAD

**Issue by franco-anfossi** [IIC2143/Syllabus#19]
Holaa, he estado pegado con este problema buscando como solucionarlo pero no lo logro encontrar. Lo que pasa es que se crean todas las vacunas bien (esto juzgando por la response que tira), de hecho luego me deja usar el show también. Pero me ocurre un problema con el test dos de crear que dice _**First vaccine for first person | TypeError: Cannot read properties of undefined (reading 'vaccine_type')**_ y no puede saber como solucionarlo si todo esta saliendo bien, solo que este error al parecer no me permite hacer el update ni el destroy. 

Entonces me gastaría saber que estoy haciendo mal o como solucionarlo. 

![image](https://user-images.githubusercontent.com/106122557/227097426-84e8ef45-3fd6-4895-b130-6005a8afe262.png)
![image](https://user-images.githubusercontent.com/106122557/227097755-75da8241-1885-4c18-8002-0ae1479bf7d7.png)

**Comment by Lexiesm** [comment]
tengo la misma duda :(

**Comment by Juan-Carlos-Ferrer-Barros** [comment]
Estoy con el mismo problema, y no sé ni donde puede estar

**Comment by Balison** [comment]
Hola, para ayudarte primero quisiera saber (i) si todos los tests previos a ese request pasaron y (ii) si estas seguro que la implementacion de tu metodo create esta bien. 

Por favor, nota que el método create, a parte de crear la vacuna, renderiza en json todas las vacunas de la persona con el id igual a params[:person_id]. Por lo que tu body response deberia ser una lista de vacunas y no solo la vacuna recien creada. Si tienen problemas, por favor avisen.

**Comment by franco-anfossi** [comment]
Hola! Muchas gracias, no me había dado cuenta de que tenia que mostrar todas las vacunas, había leído mal inicialmente, ahí lo cambie y ya no tengo ningún problema :)
