### ISSUE TITLE
Problema parte 8: crear proyecto

### ISSUE THREAD

**Issue by ivannateresa** [IIC2143/Syllabus#19]
Hola!. Tengo un problema al momento al iniciar el prouecto. Al correr 'rails new project --database=postgresql' en la terminal me aparece el siguente error.
![imagen](https://user-images.githubusercontent.com/69605531/185514980-0b0f9bf7-b54c-4c3f-8916-670fda434ae9.png)
De antemano muchas gracias c:

**Comment by kunafuego** [comment]
Hola! Lo primero que debes chequear es si tienes Rails instalado o no. Para esto, reinicia tu consola y corre el comando `rails- v`. Te debería aparecer Rails 6.0.4 como respuesta. En caso de que te aparezca un error, vuelve a la parte 5 del tutorial.

Si te aparece la respuesta correcta, lo que debes hacer es indicarle a la consola que el proyecto que quieres crear debe estar en esa específica versión. Para esto, deberás correr el comando `rails _6.0.4_ new <nombre proyecto> --database=postgresql`. Es el mismo comando de antes, pero le agregas `_6.0.4_`, para indicarle que quieres que el proyecto utilice esa versión de la gema Rails.

Avísame si esto resuelve tu problema!

**Comment by ivannateresa** [comment]
Hola!, la version del rails que me salio es 6.1.4.1, ¿esta bien si utilizo esa?. SIn embargo utilice el comando que me indicaste y me aparecio esto. 
![imagen](https://user-images.githubusercontent.com/69605531/185700312-ac212e8a-cdeb-443a-92d6-b50716dc0d91.png)

De antemano muchas gracias c:

**Comment by kunafuego** [comment]
Te recomiendo descargar la que aparece en el tutorial (6.0.4). Una vez que la descargues, puedes revisar todas las versiones de la gema *rails* que tienes descargadas con el comando `gem list rails`. Ahí te deberían aparecer como mínimo las versiones 6.1.4.1 (que ya la tienes descargada), y la 6.0.4 (la que tienes que descargar).

Para crear un proyecto con una versión determinada, debes ocupar el comando de la imagen que me mandaste. 

Lo que te apareció en la imagen que mandaste pasó porque ya tenías un proyecto creado en esa carpeta con ese mismo nombre!

De todas formas, claramente ya quedó solucionado tu problema inicial, porque el proyecto se creó sin problemas! Cualquier otra cosa me avisas!

**Comment by ivannateresa** [comment]
Hola!, es que intente descargar rails 6.0.4 me aparecia este error 
![imagen](https://user-images.githubusercontent.com/69605531/185705465-1935991b-a642-4472-9e81-15fcd541d2f0.png) y aun me sigue saliendo el mismo error cuando creo otro proyecto con otro nombre.

**Comment by kunafuego** [comment]
Para descargar la versión, intenta con `sudo gem install rails -v 6.0.4`.

Sobre lo de crear otro proyecto, el comando lo estás corriendo desde dentro de la carpeta /project, que ya es un proyecto en sí, por lo que no te va a dejar. 

Por último, es importante notar que el mensaje que te aparecía por el conflicto del .gitignore no es un error! Es la consola haciéndote una pregunta. De hecho, [Ynaqdhm] es un [acrónimo](https://stackoverflow.com/questions/56300613/meaning-of-ynaqdhm) de todas las posibles respuestas que puedes dar.

**Comment by ivannateresa** [comment]
hola, nose si tengo que hacer otra issue, porque instale rails -v 6.0.4 , pero me sigue saliendo otra version y la habia tratado de desintalar. 
![imagen](https://user-images.githubusercontent.com/69605531/185713036-b3163754-af54-4031-9ddf-eeeeb79277af.png)

Muchas gracias por la ayuda.

**Comment by meretamal** [comment]
Hola, eso es porque por defecto se intentará usar la versión más actualizada. Si quieres usar la 6.0.4, intenta una de las siguientes opciones:

* Opción 1: correr `rails _6.0.4_ new app --database=postgresql`
* Opción 2: desinstala rails y railties 6.1.4 (`gem uninstall rails -v 6.1.4` y `gem uninstall railties -v 6.1.4`)

**Comment by ivannateresa** [comment]
Hola! Muchasss graciasss!. Me funciono perfecto con la opción 1. Gracias por la ayuda :smile:.
