### ISSUE TITLE
No puedo hacer push de la Soccer Api a mi repositorio de la tarea

### ISSUE THREAD

**Issue by Josefinafp** [IIC2143/Syllabus#19]
Hola! Estoy teniendo problemas al subir el proyecto a mi repositorio. Traté creando la api dentro y fuera de la capeta y en ninguno de los casos lo pude subir. Me podrían ayudar por favor?
Aca muestro mi error:

![Captura de pantalla 2024-03-18 a la(s) 12 10 27](https://github.com/IIC2143/Syllabus/assets/110868198/be7bb77a-8d0f-4ca4-b27e-11a3ded38043)

**Comment by TomasRiquelme** [comment]
me pasa lo mismo; me tira error :c

**Comment by Osiries1111** [comment]
Me pasa lo mismo

![image](https://github.com/IIC2143/Syllabus/assets/130408574/4d787872-c692-48e0-bc32-485c324fc23e)

intenté subir los archivos que tenias dentro de la api a ver si pasaba algo, pero tampoco me deja, me tira este error y no me deja hacer git reset --hard HEAD~1 para quitar el commit

**Comment by Josefinafp** [comment]
no me aparece ningún archivo .git y dentro de la carpeta tampoco
![image](https://github.com/IIC2143/Syllabus/assets/110868198/674bf479-0c19-4059-8dd7-6221e516fbae)

**Comment by rocimarquez** [comment]
me pasa lo mismo, y no encuentro ningún archivo .git
