### ISSUE TITLE
Consulta nivel aldeanos

### ISSUE THREAD

**Issue by Cartterr** [IIC2143/Syllabus#19]
Hola, quería consultar si el nivel del aldeano sube cuando alcanza la experiencia necesaria, o cuando la pasa? Ya que el expected_output.txt dice que el granjero carlos es lvl 2, pero según aldeanos.csv el tiene 40 de experiencia, lo cual es suficiente para pasar al nivel 3.

Gracias de antemano

**Comment by maggiemunoz** [comment]
Hola! Esto fue resuelto en la #11
