### ISSUE TITLE
Problema SetUp

### ISSUE THREAD

**Issue by monesti** [IIC2143/Syllabus#2]
Tuve problemas en el paso 4 del setup para macOs.
Al correr `rvm install 3.1.0` obtengo
<img width="628" alt="Screenshot 2024-03-10 at 19 05 12" src="https://github.com/IIC2143/Syllabus/assets/127237693/958b5f77-8498-4903-95a0-14144498b68b">
Mi computador tiene procesador M1 Ventura y si estoy usando la consola con Rosseta.

**Comment by tomastrivino** [comment]
Qué tal si pruebas `sudo rvm install 3.1.0`?

**Comment by monesti** [comment]
Muchas gracias por la ayuda Tom <3 Probamos con sudo también pero parece ser que homebrew no permite utilizar sudo. Adjunto captura
<img width="649" alt="Screenshot 2024-03-10 at 19 18 00" src="https://github.com/IIC2143/Syllabus/assets/127237693/73c388df-1743-4e77-ad64-ecfa787ec641">

**Comment by Josefinafp** [comment]
Hola!! Estoy con el mismo problema. Tampoco se corrige con sudo. Tengo ventura 13.5.1 y mi procesador es 2,9 GHz Intel Core i7 de dos núcleos. Llevo mucho rato tratando con chat gpt tmb y el problema persiste

**Comment by Josefinafp** [comment]
Holaa! Me pasaba lo mismo, tampoco me resultaba sudo y tampoco pude resolverlo con chat gpt. Al final pude hacerlo, lo corrí muchas veces hasta que resultara!

**Comment by monesti** [comment]
rvm install 3.1.0 --with-openssl-dir=$(brew --prefix openssl)

Encontré esto y pude hacerlo, para quién le sirvaa

**Comment by Vicente9** [comment]
Hola, tengo un problema en el paso 5. No he podido solucionarlo.
<img width="563" alt="Screenshot 2024-03-11 at 6 31 00 PM" src="https://github.com/IIC2143/Syllabus/assets/101224081/ba4e4395-01c6-467d-9e70-da4c464024f9">
