### ISSUE TITLE
Duda sobre creación de user (PostgreSQL: superuser)

### ISSUE THREAD

**Issue by ValeeRamirez** [IIC2143/Syllabus#2]
Hola, quede en esta parte de la guía de instalación y no se porque no me funciona. Tiene algo que ver que ya tenga usuario en ubuntu? O como lo soluciono?
Gracias!
![Captura de pantalla (212)](https://user-images.githubusercontent.com/89212922/184237790-aeaa06a7-0b39-4f2e-8614-4585997bdd87.png)

**Comment by meretamal** [comment]
Hola, el comando `sudo -u postgres psql` te permite entrar a tu servicio de postgresql usando el usuario que se crea por defecto (postgres). El resto de las entradas que salen en tu terminal son del servicio corriendo, por lo que está todo bien.

Lo que debes hacer ahora, es correr el comando que se indica en la guía para crear a tu superuser (y luego salir con `\q`)

**Comment by ValeeRamirez** [comment]
Esque después no me deja usar el comando create y no puedo crear el usuario, por lo que pensé que en esta parte estaba el error. Porque en verdad se quedaba justo antes del help, y lo escribí para ver que decía.

**Comment by meretamal** [comment]
Podrías mandar el error que te sale al correr `CREATE USER myuser WITH SUPERUSER PASSWORD 'mypassword';`? (siendo `myuser` y `mypassword` las credenciales que quieres usar)

**Comment by ValeeRamirez** [comment]
Ya cache cual era el problema, gracias igual!! :)

**Comment by meretamal** [comment]
Ya buenísima, si puedes comentarlo por acá igual, sería genial. Así alguien con un problema similar puede ver tu solución 😁

**Comment by ValeeRamirez** [comment]
Era que, yo pensaba que cuando decia type help tenia que escribir help si o si y despues como que me salia del service postgresql y por eso no funcionaba el comando de create. Enverdad fue de pava y era algo muy simple jaja
