### ISSUE TITLE
Versión Ruby a usar en el curso

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2143/Syllabus#2]
Hola!

Quisiera saber si el curso se debe realizar con una versión de Ruby en específico,

Gracias!

**Comment by maggiemunoz** [comment]
Hola! Usaremos la version 2.6

**Comment by naderhadweh** [comment]
Holaa, tengo una duda. Cuando intento instalar rails me sale esto, que puedo hacer?

![Captura de Pantalla 2022-03-18 a la(s) 23 04 11](https://user-images.githubusercontent.com/89283382/159102581-2ada883a-a4b7-46c5-a004-bf4a52466001.png)
o

**Comment by cadaeic314** [comment]
Holaa, y hay problema con usar una versión posterior?, yo estoy trabajando con ruby 3.1

**Comment by JosefaPaz** [comment]
@naderhadweh 

Hola! Te recomiendo que sigas la [guía de instalación](https://github.com/iic2143/syllabus/wiki/Setup-Ubuntu) para que no tengas problemas. Si tienes problemas nuevamente con instalar rails por favor crea una nueva issue, ya que esta no está relacionada a ese problema.

Éxito!

**Comment by JosefaPaz** [comment]
@cadaeic314 

Hello! Recomendamos fuertemente usar la versión 2.6, ya que puede que con ruby 3.1 hayan comandos diferentes y cuando el ayudante revise tu tarea esta no corra correctamente en su computador.

Éxito! :)
