### ISSUE TITLE
Valdacion de atributos

### ISSUE THREAD

**Issue by martineyz** [IIC2143/Syllabus#20]
Estaba viendo el los test case que hay atributos que no pueden ser nulos, pero en el enunciado no se habla nunca de que atributos pueden o no ser nulos. Me gustaría una aclaracion respecto a que atributos deben tener validacion de nulidad y caules no. Tambien si algun atributo debe tener otro tipo de restriccion. Gracias de antemano.

**Comment by jtvaldivia** [comment]
Hola,
puedes suponer que toda la informacion de los post(los ejemplos del enunciado integran esa informacion) no debe ser nula, por temas logicos (un jugador no puede no tener nombre o un partido jugado no puede no tener resultado.

**Comment by jtvaldivia** [comment]
La informacion que se manda en los post y que esta es la que se verifica. Lo puedes ver en los ejemplos de json mandados que se ven en el enunciado

**Comment by abtamayo** [comment]
Si hay datos nulos, que deberia retornar?

**Comment by SantiagoDLCB** [comment]
en ese caso tambien debemos validar que el formato del texto recibido en resultados tenga sentido?

**Comment by jtvaldivia** [comment]
@abtamayo  al revisar con los test case vas a ver que deberia retornar un error(estilo 422), si haces bien las asociaciones y el modelo retornara por defecto esto.

**Comment by jtvaldivia** [comment]
@SantiagoDLCB  no, solamente que no sean vacios. Por ejemplo que un partido no tenga un estado que no sea nada o que no exista un jugador sin nombre.
