### ISSUE TITLE
Duda enunciado método Update

### ISSUE THREAD

**Issue by jadelanoa** [IIC2143/Syllabus#22]
Tengo una duda con respecto al método `update` del **Controller Vaccines**. Dado el id de una persona y el id de la vacuna, cual de las dos acciones hay que realizar:

1. Modificar los datos de esa vacuna para esa persona, es decir cambiar los datos guardados.
2. Crear una nuevas dosis de esa vacuna para esa persona con la fecha entregada. 

Yo realice lo primero, y revise muy bien que estuviera correcto pero el test case no lo pasa. 
Del test case me aparece: _**Updated date of first vaccine for first person | AssertionError: expected '2022-07-20' to deeply equal '2022-01-01'**_

**Comment by OrregoSilva** [comment]
Lo que hay que hacer es el punto 1, ya que si quisiera agregar una nueva dosis, llamaríamos al método create. Sobre el test. Revise tu repositorio y hay un pequeño paso que no estás realizando al actualizar una vacuna, también te recomiendo usar los métodos de la asociación (@person.vaccines por ejemplo).

**Comment by jadelanoa** [comment]
Sigo sin encontrar el error. Lo extraño es que en la base de datos todo funciona como debería.
