### ISSUE TITLE
Consulta sobre el schema

### ISSUE THREAD

**Issue by martina-abello** [IIC2143/Syllabus#23]
Cuando se creó mi schema me dejó automáticamente los atributos 'teamA' y 'teamB' como  'teamA_id' y  'teamB_id'.
Eso está bien, mal, afecta los test cases, o cómo? Si está mal, cómo se arregla?

Gracias de antemano.

**Comment by aerotecnia99** [comment]
Hola @martina-abello ! Sí, está bien. En Rails, es común que cuando se crea un esquema para una relación de pertenencia a través de una asociación, los nombres de los atributos de las llaves foráneas se generen automáticamente con el sufijo "_id". Esto es parte de la convención de nomenclatura que sigue Rails para las asociaciones. 🌵

**Comment by FelipeMunozMoraga** [comment]
Para complementar, a la hora de retornar los json puedes definir funciones o métodos que modifiquen el nombre de los atributos solo en el json, así tu controller y código en general puede seguir la convención de agregar _id e igualmente retornar los nombres pedidos en el enunciado!
