### ISSUE TITLE
[TAREA] - Criterios para poder vender

### ISSUE THREAD

**Issue by kalarconvl** [IIC2143/Syllabus#23]
Hola! De la página 4 del enunciado entiendo que los aldeanos pueden vender un objeto cuando su nivel es mayor o igual al nivel indicado en la subcategoría del ítem (única condición). Pero en la aclaración del método ```información_aldeanos``` dice que "_Para que un item sea considerado en esta lista, el aldeano debe poder venderlo con descuento (es decir, calzan los tipos) y además, tener un nivel lo suficientemente alto para hacerlo_". Mi duda es: los ítems que el aldeano sí puede vender porque su nivel lo permite pero que vende sin descuento, ¿(a) solo no se deben considerar para el output, pero sí puede venderlos, o (b) no puede venderlos porque para poder vender un item tiene que poder venderlo con descuento?

**Comment by maggiemunoz** [comment]
Hola! La opción correcta de lo que mencionas es la a :) 

Si puede vender esos items en caso de hacerse un intercambio, pero como no los vende con descuento, no se verán reflejados en el output del método ´´´informacion_aldeanos´´´.
