### ISSUE TITLE
Error 'rvm' not found

### ISSUE THREAD

**Issue by agustinbc7** [IIC2143/Syllabus#23]
Hola, en la parte 3 del setup, los 3 comandos funcionaron sin problema, pero luego de reiniciar la consola y usar el comando rvm -v, me dice: Comman 'rvm' not found, but there are 19 similar ones. No se si al igual que en las issues anteriores debo modificar el segundo comando o no. 
Gracias de antemano.

**Comment by meretamal** [comment]
Hola, qué sistema operativo estás usando?

**Comment by agustinbc7** [comment]
Ya lo logré solucionar, debía cambiar el segundo comando. Gracias igualmente

**Comment by FranciscoPinto1138** [comment]
Holaa ¿me podrías decir exactamente lo que hiciste por favor? Tuve el mismo problema

**Comment by agustinbc7** [comment]
Hola, hice lo que pusieron en la issue 3, remplacé el segundo comando por uno de los 3 que sugirieron, no recuerdo bien cuál usé, creo que el segundo. Osea, usé gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB, pero reemplazando hkp://pool.sks-keyservers.net por una de las opciones que sugerían. Eso sí empecé el paso 3 desde cero.
