### ISSUE TITLE
Duda carpeta proyecto - git

### ISSUE THREAD

**Issue by catalinacarter** [IIC2143/Syllabus#23]
Hola! Tengo una duda con las carpetas del proyecto. Tengo mi proyecto en una carpeta llamada **tarea** y por otro lado, tengo otra carpeta que se llama **entrega_tarea** (la cual corresponde al repositorio clonado con git clone url alias). Para entregar el proyecto basta con copiar todos los archivos que tengo en **tarea** y pegarlos en **entrega_tarea**? Además de hacer el git push obviamente.

Pregunto porque en su momento en **config/database.yml** reemplace el contenido con:

`default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: nombre proyecto_development

test:
  <<: *default
  database: nombre proyecto_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
`

Lo que sale en la guía del set up. En el código **nombre proyecto** lo reemplace por **tarea**, ya que es la carpeta en donde cree el proyecto. La cosa es que no se si basta con copiar y pegar como mencioné arriba y si afecta en algo que en **config/database.yml** al pegar en **entrega_tarea** aparezca **tarea** y no **entrega_tarea**. Sorry lo enredado jajaja y muchas gracias de antemano :)

**Comment by OrregoSilva** [comment]
Hola!
Sobre los nombres de la base de datos da lo mismo, y sobre la forma de entregar, revise tu repositorio y está como debería estar, así que no debería haber problemas en eso.

**Comment by catalinacarter** [comment]
Super, gracias!!
