### ISSUE TITLE
No me corren los codigos de Ruby en Visual Studio Code

### ISSUE THREAD

**Issue by SebaValenzuela** [IIC2143/Syllabus#24]
Cuando quiero correr un codigo de ruby en el visual studio code me sale el siguiente error: "'ruby' is not recognized as an internal or external command, operable program or batch file.". No se si tengo mal instalado ruby en mi computador, vsc o simplemente lo estoy corriendo mal.

![image](https://user-images.githubusercontent.com/89088201/185814413-5871188b-e1ee-4456-b6c8-5b201336d552.png)
![image](https://user-images.githubusercontent.com/89088201/185814430-244a9241-88f5-46f3-9adb-662d917a14c5.png)

Gracias de antemano

**Comment by elbosco** [comment]
Pon la extension code runner en vsc

**Comment by kunafuego** [comment]
Hola! Creo que lo que te está pasando es que descargaste Ruby en WSL y ahora lo estás intentando correr en un terminal de Windows.  

Intenta [descargar Ruby para Windows](https://rubyinstaller.org/downloads/) (Recuerda agregar el PATH) y luego podrás correr código Ruby desde ese mismo terminal. 

Otra opción es abriendo el terminal de Ubuntu en esa misma carpeta y corriendo el archivo.


Prueba si esto soluciona tu problema y me avisas!

**Comment by SebaValenzuela** [comment]
Muchas gracias ahora si me funciona!!!
