### ISSUE TITLE
[Ruby][Tarea] Setter de un atributo

### ISSUE THREAD

**Issue by cncosta** [IIC2143/Syllabus#24]
Estoy tratando de hacer que mi setter de alguna clase impida que  una atributo tome ciertos valores (Ej: que no pueda ser menor a 0). El setter funciona bien cuando se hacen operaciones afuera de la clase, pero cuando inicializo la clase con un valor invalido este no funciona.

```ruby
class Clase
    def initialize (atributo)
        @atributo = atributo
    end

    def atributo
        @atributo
    end

    def atributo=(atributo)
        @atributo = [atributo,0].max
    end
end

obj = Clase.new(-1)
puts obj.atributo
obj.atributo -= 1
puts obj.atributo
```
``` shell
-1
0
``` 
Cuando se instancia la clase por primera vez el valor del atributo queda en -1, pero al hacer un cambio en la variable este se ajusta bien con el setter.

**Comment by maggiemunoz** [comment]
Hola! La gracia de los getters y los setters es que actúan para llamar/cambiar los atributos desde afuera de la clase, como al inicializar las instancias lo haces desde el método initialize, que es un método de la clase, no se interactúa con el setter. 

Lo que puedes hacer es esa misma validación dentro de initialize, algo del tipo

```ruby
class Clase
    def initialize (atributo)
        @atributo = [atributo,0].max
    end
``` 

para asegurarte que se cree con un valor correcto. Igual, en este caso particular no vamos a inicializar ninguna instancia con valores incorrectos.
