### ISSUE TITLE
Problema git add

### ISSUE THREAD

**Issue by catalinacifuentes** [IIC2143/Syllabus#24]
Hola! Tengo problemas para subir la tarea al repo. 
Hice la api en una carpeta directo desde mi computador. Y luego clone el repo en mi computador, y copie y pegue la carpeta de la api en el repo. El problema es que al hacer git add tarea/ me aparece el siguiente error. 

error: 'tareafinal/' no tiene un commit checked out
fatal: falló al agregar archivos

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! perdona por la demora en responder, una alternativa que se me ocurre es usar el comando 
git add .         (nótese que tiene un espacio y después un punto)
De esta forma se debería hace add a todos los archivos que estén en el repositorio en el que ejecutes el comando, así que esto podría solucionar tu problema. 

Coméntame si te resulta 😄

**Comment by Juan-Carlos-Ferrer-Barros** [comment]
Estoy teniendo el mismo problema, poniendo `git add .`. Me sale esto 
```
git add .
error: 'tarea_1_people/' does not have a commit checked out
fatal: adding files failed
```
