### ISSUE TITLE
Problema parte 8: bundle install

### ISSUE THREAD

**Issue by patriciavsy** [IIC2143/Syllabus#25]
Al escribir el comando de bundle install me aparece este error y no se como solucionarlo 😅

![error 8](https://user-images.githubusercontent.com/69566646/185976635-db499131-73af-4aec-bba5-795444b05b78.jpg)

Muchas gracias :)

**Comment by meretamal** [comment]
Hola 😁 , podrías intentar instalar capybara por separado (`gem install capybara`) y después correr `bundle install`?

**Comment by patriciavsy** [comment]
te refieres a esto? 😅

![local gems 2](https://user-images.githubusercontent.com/69566646/185985612-fc62ba93-9957-463b-841d-100d8ed892bb.jpg)
![local gems](https://user-images.githubusercontent.com/69566646/185985616-9a1e34a1-e68e-4a32-b53f-e4164babaa4e.jpg)

**Comment by meretamal** [comment]
Y en el archivo Gemfile (no Gemfile.lock) podrías mandar qué te sale para la gema capybara? Debería estar en el bloque:
```ruby
group :test do

end
```

**Comment by patriciavsy** [comment]
Esto es lo que me aparece para la gema capybara:

![gema capybara](https://user-images.githubusercontent.com/69566646/186019648-9c2e19a4-6578-40ea-b031-cc04f3c4868e.jpg)

Y esta es la versión de ruby y rails:

![ruby v](https://user-images.githubusercontent.com/69566646/186019671-e934ad46-ccad-4da3-adb7-2fe9bde4418a.jpg)

**Comment by meretamal** [comment]
🤔 Podrías intentar borrando el archivo **Gemfile.lock** y luego corriendo `bundle install` de nuevo?

**Comment by patriciavsy** [comment]
1. no encontré ese archivo 
2. se solucionó creo, no se como 😅

![bundle complete](https://user-images.githubusercontent.com/69566646/186027934-efc105e4-eb1a-4f5b-81e5-a9e9c46e95ea.jpg)

**Comment by BenediktKd** [comment]
Hola, yo estoy teniendo el mismo problema. No me aparece el archivo Gemfile.lock y no sé como arreglarlo.
