### ISSUE TITLE
Error ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by Ferc28** [IIC2143/Syllabus#25]
Hola, tengo un error en muchas requests donde me aparece:

```JSONError: Unexpected token '<' at 1:1 <!DOCTYPE html> ^```

Intente revisar el código completo, reiniciar todo y buscar en la web pero no logre dar con nada. Utilice también el logger.debug pero creo que no alcanza a mostrarlo o correrlo. Usualmente esto trae fallas en cascada para los otros request ya que por ejemplo no alcanza a crear ninguna instancia o a veces ni correr el método. Adjunto imagen del resultado del postman tests.

![image](https://user-images.githubusercontent.com/89324156/227580084-62e19c11-17eb-464e-8e12-fa4530bb0120.png)

![image](https://user-images.githubusercontent.com/89324156/227580390-f4ce9133-3760-4aad-87e8-781bd7bff436.png)

**Comment by OrregoSilva** [comment]
Una opción que puede estar pasando es que no creaste el proyecto para que funcionara como una API, por lo que te está respondiendo con HTML, al hacer `rails new`, agregaste el parámetro de `--api`? Ejemplo: `rails new my_project --database=postgresql --api`

**Comment by Ferc28** [comment]
Al parecer me falto agregar el parámetro, muchas gracias. ¿Existe la posibilidad de agregarlo incluso después de haber creado el proyecto?

**Comment by OrregoSilva** [comment]
Se puede configurar, pero es un poco lento y complicado, lo más fácil es crearlo de nuevo y copiar y pegar los controladores, regenerar los modelos (mismos comandos) y copiar las rutas.

**Comment by Ferc28** [comment]
Solucionado! Muy Agradecido.
