### ISSUE TITLE
Agregar informacion adicional viaje conductor

### ISSUE THREAD

**Issue by maxo2727** [IIC2143/Syllabus#25]
**Título:** Agregar información/ajuste adicional al viaje
**Descripción:** Yo, como conductor, quiero agregar información opcional de pasajeros que busco y preferencias, para agilizar y ajustar la búsqueda de acompañantes. 
**Condiciones de satisfacción:** Dado que el viaje esté publicado, cuando el conductor solicite agregar/editar información adicional, se abrirá la sección de edición, y los cambios se reflejarán en el motor de búsqueda.

**Comment by OrregoSilva** [comment]
@maxo2727 esta issue fue generada en el Syllabus, no en tu repo del grupo por lo que la cerraré.
