### ISSUE TITLE
Testcase 30, test_3b.py

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2143/Syllabus#25]
Hola! Creo que hay un error en el resultado del testcase 30, test_3b. 
Debuggeando encontre que el testcase estaba evaluando el peor equipo entre 'Universidad Católica' y  'Universidad de Chile', el resultado correcto de dicho testcase supone que este ultimo es el peor equipo y por tanto debe ser eliminado. El problema es que ambos equipos tienen un total de 1 punto ya que empataron, pero 'Universidad Católica' a jugado 1 partido más que 'Universidad de Chile' por lo que segun el enunciado deberia ser  'Universidad Católica' el peor equipo ya que es el jugador con menos puntos y entre los que comparte puntaje es aquel con más partidos.

No se si tal vez me estoy perdiendo de algo o no entendi el enunciado, muchas gracias por adelantado!!

**Comment by jtvaldivia** [comment]
Esta arreglado ahora el test.
