### ISSUE TITLE
Setup mac parte 8

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2143/Syllabus#26]
Hola!!

![Screen Shot 2022-08-22 at 22 12 47](https://user-images.githubusercontent.com/89221305/186053574-c51566d5-7e57-4635-b69e-0c28beb9022d.png)
 
Llegué bien hasta este paso en el setup de mac.
Cree el archivo .env y .env lo puse en el archivo .gitignore

Ahora me queda la duda de qué tengo que escribir dentro de .env
Dice que tengo que poner 

DB_USER=myuser
DB_PASSWORD=mypassword

siendo myuser el paso 7, myuser entonces es el nombre de mi proyecto??? y la contraseña me la tengo que inventar para escribirla?? 

Después me dice que me dirija a  config/database.yml  y reemplace el contenido por 

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <nombre proyecto>_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: <nombre proyecto>_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

en esta parte debo reemplazar <nombre proyecto> por el nombre que elegí? debo cambiar algo más?

Eso es todo por ahora,

Gracias!

**Comment by meretamal** [comment]
Hola 😁 , en el .env debes poner el usuario y la contraseña que creaste en el paso anterior.

En cuanto al archivo database.yml, debes modificar `<nombre proyecto>_development` y `<nombre proyecto>_test` por el nombre de tu proyecto seguido de cada ambiente. Por ejemplo, si tu proyecto se llama app, será app_development y app_test (en teoría puede ser cualquier nombre, pero así mantenemos algo standard.

**Comment by Fernanda1232123** [comment]
Gracias, me queda claro lo de cambiar el archivo database.yml. Pero me queda la duda del archivo .env, en el paso anterior cree el nombre del proyecto pero no dice nada del usuario y contraseña!!

**Comment by meretamal** [comment]
Se refiere a [este paso](https://github.com/iic2143/syllabus/wiki/Setup-Mac#5-postgresql-superuser).

**Comment by Fernanda1232123** [comment]
uff gracias, no lo vi. ¿Como sé cual es el usuario que tengo en mi sistema?

**Comment by meretamal** [comment]
Si abres tu terminal, debería salir ahí. De todos modos, si instalaste postgres con homebrew, ya debería venir creado.
