### ISSUE TITLE
Unpermitted parameters

### ISSUE THREAD

**Issue by martina-abello** [IIC2143/Syllabus#26]
![imagen](https://github.com/IIC2143/Syllabus/assets/128489585/73130bdf-9396-49c7-bdce-d4d598275ff5)
why (╥﹏╥)

**Comment by jtvaldivia** [comment]
Hola Martina, 
Nos podrias dar un mayor contexto del error?

**Comment by martina-abello** [comment]
No sé si sirva, a este punto literal todo lo que hago me tira un error distinto. Básicamente no me deja usar :teamA y :teamB en el match controller, me obliga a usar :matchA_id y :matchB_id, que obviamente no es la idea porque no es como están los parámetros en el enunciado de la tarea.

Agradecería si alguien me dijera cómo/dónde contactar al profe fuera del horario de clases o algo, porque _necesito_ que alguien me ayude 1 a 1, nada me funciona.

**Comment by jtvaldivia** [comment]
Puedes contactar al profesor por correo, y te recomiendo ver las capsulas si estas muy perdida.

**Comment by martina-abello** [comment]
Me puedes dar el correo, y ayuda con esta issue?

**Comment by FelipeMunozMoraga** [comment]
el correo del profesor es juanpablo.sandoval@uc.cl
No se si es exactamente lo que necesitas, pero leyendo lo que comentabas te quería aclarar que no es necesario que los atributos tengan el mismo nombre del enunciado, lo que debe ser igual es el body response en formato JSON, puede ser más sencillo en tu caso resolver la tarea con teamA_id y luego hacer un custom JSON con los nombres que les pedimos
