### ISSUE TITLE
"Internal Server Error"

### ISSUE THREAD

**Issue by mnallark** [IIC2143/Syllabus#26]
El primero test case de destroy all persons tira el siguiente error:     

"error": "Internal Server Error",
"exception": "#<ArgumentError: Rails couldn't find a valid model for Vaccine association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.>"

Lo revisamos con un ayudante y no pudimos descifrar cual es el error en mi código.

**Comment by OrregoSilva** [comment]
Hola! Podrias subir tu codigo al repositorio para ver bien que es lo que pasa? Lo mas probable es que los modelos no tienen los mismos nombres con los cuales los estas llamando.

**Comment by mnallark** [comment]
Hola, ya esta arriba. Graciass
