### ISSUE TITLE
[Tarea] - Archivos CSV tras transferencia

### ISSUE THREAD

**Issue by Ajbarros1** [IIC2143/Syllabus#26]
Hola, tengo una duda sobre los csv. Si se completa exitosamente una transferencia, ¿debemos cambiar los datos de los csv, como la experiencia del aldeano y del jugador, al igual que la reputación y la cantidad de los rubíes de este ultimo?

**Comment by maggiemunoz** [comment]
Hola! No, no deben actualizar los archivos csv :)

**Comment by mpmunoz13** [comment]
@maggiemunoz Si se realizan intercambios correctamente (cambiando el nivel de los aldeanos) y luego se pide la informacion_aldeanos, esta información debe estar con los niveles actualizados?

Me estoy poniendo en caso que las instrucciones sean:
informacion_aldeanos
hacer_intercambios
informacion_aldeanos
