### ISSUE TITLE
Error de formato test 2A.py

### ISSUE THREAD

**Issue by clumsypunch** [IIC2143/Syllabus#27]
Hola tengo un problema con el test del titulo porque realizo esta request por ejemplo: `http://localhost:3000/teams/217/matches` y me retorna: 
```javascript
[
    {
        "id": 70,
        "teamA": 217,
        "teamB": 216,
        "state": true,
        "result": "0-0",
        "created_at": "2024-03-19T16:28:00.523Z",
        "updated_at": "2024-03-19T16:28:00.523Z"
    },
    {
        "id": 71,
        "teamA": 217,
        "teamB": 219,
        "state": true,
        "result": "3-1",
        "created_at": "2024-03-19T16:28:00.539Z",
        "updated_at": "2024-03-19T16:28:00.539Z"
    },
    {
        "id": 68,
        "teamA": 216,
        "teamB": 217,
        "state": true,
        "result": "3-0",
        "created_at": "2024-03-19T16:28:00.492Z",
        "updated_at": "2024-03-19T16:28:00.656Z"
    }
]
``` 
Que es lo que efectivamente se pide en 2.1:
```javascript
1 [
2 {
3 "id": 2,
4 "teamA": 6,
5 "teamB": 4,
6 "state": true,
7 "result": "2-1",
8 "created_at": "2024-03-07T14:12:04.800Z",
9 "updated_at": "2024-03-07T14:12:04.800Z"
10 },
11 {
12 "id": 3,
13 "teamA": 5,
14 "teamB": 6,
15 "state": false,
16 "result": "-",
17 "created_at": "2024-03-07T14:15:44.603Z",
18 "updated_at": "2024-03-07T14:15:44.603Z"
19 }
20 ]

```

**Comment by k0rval4n** [comment]
¡Hola! Me sumo a la duda de formato.
Toqueteando un poco el .py de los test logré observar la diferencia:
![image](https://github.com/IIC2143/Syllabus/assets/141952843/3aa38ce6-75f3-4e61-8da2-c0dff42e648d)
Por lo que aparentemente los testcases tienen un formato distinto al mostrado en el enunciado.
Debemos guiarnos por los testcases o por el enunciado? Gracias.

**Comment by FelipeMunozMoraga** [comment]
Hola! Probé el tester y no me aparece lo mismo que a ustedes. entiendo que están revisando el que corresponde a team/:team_id/matches. 

felipe@LAPTOP-R3V0527R:~/Tester-Tarea-2024-1$ python3 test_2A.py
Response:
{
    "id": 98,
    "teamA": 93,
    "teamB": 94,
    "state": true,
    "result": "2-1"
}
{
    "id": 99,
    "teamA": 93,
    "teamB": 95,
    "state": true,
    "result": "1-1"
}
{
    "id": 100,
    "teamA": 94,
    "teamB": 93,
    "state": true,
    "result": "0-0"
}
{
    "id": 102,
    "teamA": 95,
    "teamB": 93,
    "state": true,
    "result": "1-0"
}

Expected:
{
    "id": 98,
    "teamA": 93,
    "teamB": 94,
    "state": true,
    "result": "2-1"
}
{
    "id": 99,
    "teamA": 93,
    "teamB": 95,
    "state": true,
    "result": "1-1"
}
{
    "id": 100,
    "teamA": 94,
    "teamB": 93,
    "state": true,
    "result": "0-0"
}
{
    "id": 102,
    "teamA": 95,
    "teamB": 93,
    "state": true,
    "result": "1-0"
}
Response:
{
    "id": 98,
    "teamA": 93,
    "teamB": 94,
    "state": true,
    "result": "2-1"
}
{
    "id": 100,
    "teamA": 94,
    "teamB": 93,
    "state": true,
    "result": "0-0"
}
{
    "id": 101,
    "teamA": 94,
    "teamB": 96,
    "state": true,
    "result": "3-1"
}

Expected:
{
    "id": 98,
    "teamA": 93,
    "teamB": 94,
    "state": true,
    "result": "2-1"
}
{
    "id": 100,
    "teamA": 94,
    "teamB": 93,
    "state": true,
    "result": "0-0"
}
{
    "id": 101,
    "teamA": 94,
    "teamB": 96,
    "state": true,
    "result": "3-1"
}
Response:
{
    "id": 99,
    "teamA": 93,
    "teamB": 95,
    "state": true,
    "result": "1-1"
}
{
    "id": 102,
    "teamA": 95,
    "teamB": 93,
    "state": true,
    "result": "1-0"
}
{
    "id": 103,
    "teamA": 95,
    "teamB": 96,
    "state": false,
    "result": "--"
}

Expected:
{
    "id": 99,
    "teamA": 93,
    "teamB": 95,
    "state": true,
    "result": "1-1"
}
{
    "id": 102,
    "teamA": 95,
    "teamB": 93,
    "state": true,
    "result": "1-0"
}
{
    "id": 103,
    "teamA": 95,
    "teamB": 96,
    "state": false,
    "result": "--"
}
1. True
2. True
3. True
4. True
5. True
6. True
7. True
8. True
9. True
10. True
11. True
12. True
13. True
14. True
15. True
16. True
17. True
Total: 17/17

Tienen la versión más actualizada del tester? Quedo atento dado lo extraño de la situación!

**Comment by clumsypunch** [comment]
Yo probe mi codigo original y el tema es que a parte de que no fue evidente para mi lo del parametro show del tester, lo espera ordenado de forma simple, por id en este caso y por otros mas adelante. Asi que con eso en mente me paso el test 2A, 2B, 2C. Gracias.

**Comment by k0rval4n** [comment]
¡Sí! Tengo la versión actualizada del tester. Las responses de los testcases se generan utilizando la API? (¿Si tengo código distinto, podría dar pie a una response esperada distinta?) O las responses esperadas son fijas y establecidas completamente en los testcases? ¡Gracias!

**Comment by jtvaldivia** [comment]
A que te refieres con, ¿Si tengo código distinto, podría dar pie a una response esperada distinta?

**Comment by k0rval4n** [comment]
Si mi código influye en la respuesta esperada de los testcases. Como las responses esperadas que me aparecen a mí no son las mismas que las esperadas de @FelipeMunozMoraga, esa podría ser una causa.

**Comment by jtvaldivia** [comment]
Influye en cierto nivel, debido que a medida que vas creando por ejemplos matches van creandose tambien matches en el tester. Por eso, es distinta al tener ids segun como se a rellenado todo.

**Comment by k0rval4n** [comment]
Y los métodos que utiliza el tester, por ejemplo, match.teamA, los saca de mi API/Base de datos o el mismo tester tiene definido qué debería retornar match.teamA? Muchas gracias.

**Comment by k0rval4n** [comment]
¡Hola! Pude solucionarlo :D Tenía una discrepancia en la definición de las relaciones en el Model de los Matches, la cual había "parchado" modificando la response en el Controller. Sin embargo, como los test consideran directamente la base de datos para tomar la respuesta esperada, generaban la diferencia observada en la imagen que mandé. Cambiando la relación en el Model solucionó la diferencia.
