### ISSUE TITLE
Problema al correr localhost:3000

### ISSUE THREAD

**Issue by Juan-Carlos-Ferrer-Barros** [IIC2143/Syllabus#27]
Después de haber hecho todos los pasos, puse como `root` a "persons#index". Al correr `rails s`, me tira un error que dice "The action 'index' could not be found for PersonsController". Si tengo creado el método index en el controlador. **¿Cuál puede ser el error?**

**Comment by OrregoSilva** [comment]
Como la tarea es una API, no hay necesidad de tener un root, esa línea es solo cuando queremos hacer la página web.

**Comment by Juan-Carlos-Ferrer-Barros** [comment]
Muchas gracias! Tenía un problema al crear el controlador Persons y el `rails db:migrate` me generaba una tabla de people en vez de persons.
