### ISSUE TITLE
Problemas al inscribir grupo

### ISSUE THREAD

**Issue by pepinofdz** [IIC2143/Syllabus#27]
Hola, con mi grupo hicimos varios intentos para registrarmos con el formulario pero no tuvimos ningún intento exitoso.
Incluso intercambiamos correos con la ayudante de proyectos (Jo España) para intentar solucionar el problema pero finalmente no pudimos.

Existe alguna manera en que se pueda registrar el grupo manualmente o algo similar? Tengo los usuarios de github, número de alumno y correo de mis compañeros, por si es de utilidad.

De antemano, muchas gracias

**Comment by JosefaPaz** [comment]
Hello! @pepinofdz 

Me llegó el correo y ya está su grupo creado, para que no se preocupen ^^.

Gracias por la paciencia, que tengan buena semana! :)

**Comment by pepinofdz** [comment]
Muchas gracias!!
