### ISSUE TITLE
Problema parte 5: gem install rails -v 6.0.4

### ISSUE THREAD

**Issue by Dafnemami** [IIC2143/Syllabus#27]
En algún minuto me pidió instalar ruby así que corrí: sudo apt install ruby

Luego al correr la instrucción gem install rails -v 6.0.4, la consola me arroja el siguiente error:
![Captura de pantalla de 2022-08-22 23-10-29](https://user-images.githubusercontent.com/53848830/186061069-22b33dd9-3481-4a24-9866-1be58d56aaa3.png)

Encontré esto pero prefiero esperar a su repuesta: https://stackoverflow.com/questions/37720892/you-dont-have-write-permissions-for-the-var-lib-gems-2-3-0-directory

**Comment by kunafuego** [comment]
Hola! Si ya tienes descargado Ruby y el comando `ruby -v` retorna la versión que descargaste, intenta corriendo:

 `sudo gem install rails -v 6.0.4` para instalar Rails.

Avísame si esto te deja instalarlo bien!

**Comment by Dafnemami** [comment]
Pude instalar ruby 2.7. Hice [otra issue ](https://github.com/IIC2143/Syllabus/issues/30) para explicar eso y preguntar otra duda que necesito sea respondida para poner ocupar `sudo gem install rails -v 6.0.4` y así poder responderte.

**Comment by kunafuego** [comment]
Hola! No es recomendable que usen Ruby 2.7 porque es una versión distinta a la que utilizarán sus compañeros de grupo. Por lo tanto, más que con Heroku directamente, podrías tener problemas de compatibilidad con tus compañeros.
