### ISSUE TITLE
Sobre el test 2A 19

### ISSUE THREAD

**Issue by dvillas28** [IIC2143/Syllabus#28]
Hola, estoy revisando que está pasando con los tests que aún no lo logro pasar en mi tarea, y al analizar el test 19, que es el que revisa el endpoint `PATCH reviews/:review_id`. 

Segun el enunciado este endpoint recibe como request body un json de este estilo 
![image](https://github.com/user-attachments/assets/7632a185-9f21-4d39-b2da-e52b06e4c8ae)

El tema es que en el tester (`test_2A.py`) lo están probando con un json nada que ver, ya que ahi hay un campo `"rating"` que no sale en ningun lado de la tarea 
![image](https://github.com/user-attachments/assets/6cd2b4ac-bba3-4cdb-bba8-e6d37a70a552)

Esto provoca que mi código tiré una excepción ya que está esperando por el campo `"title"` de `"review"`

No estoy seguro de si nuestro código debiera en realidad actuar acorde a recibir un request body invalido?, o es un test case que estara malo quizas?

Quedo atento
Saludos! 🤠

**Comment by jtvaldivia** [comment]
Hola,
si es un typo que se nos paso de cuando estabamos desarrollando el enunciado, lo actualizo ahora.

Igualmente, ojo que le patch es para actualizar cualquier atributo de las reviews, asique igualmente deberia aparecerte como correcto el test. Lo mas probable es que estas haciendo patch solo para title

**Comment by dvillas28** [comment]
Entiendo, es posible que entreguen un request body con mas de un atributo a cambiar? ¿o podemos asumir que es solo un atributo el se va a cambiar?

**Comment by jtvaldivia** [comment]
Sip es posible que entreguemos mas de un atributo a cambiar

**Comment by dvillas28** [comment]
perfecto, gracias!
