### ISSUE TITLE
Error al realizar rails db:migrate

### ISSUE THREAD

**Issue by MaximilianWilke** [IIC2143/Syllabus#28]
Hola tuve que reiniciar el proyecto, y cuando intento hacer la migración me dice:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/101229477/227605516-f68af73a-183d-4524-a544-440c657f4482.png"> , esto es porque debo borrar el anterior proyecto para que no choquen las base de datos

**Comment by OrregoSilva** [comment]
¿Generaste el proyecto con la opción de la base de datos que sale en la guía? La de `--database=postgresql`. Pregunto por qué te dice que la gema que gestiona la conexión al motor de Postgres no está instalada.

**Comment by MaximilianWilke** [comment]
Si, ya lo arregle y era por el motivo que dices, gracias igualmente
