### ISSUE TITLE
Duda acerca de estructura de repositorio individual para subida de T1

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2143/Syllabus#29]
Hola. No me queda claro cómo debe estar estructurado el repositorio que contiene la tarea 1, para evitar posibles complicaciones con la corrección automática.

El repositorio para subir la tarea debe contener el directorio con el proyecto, o es éste repositorio el que contiene los elementos del proyecto.

Para hacer la respuesta más simple, así como lo tengo ahora, estaría bien??

![image](https://github.com/IIC2143/Syllabus/assets/142269948/4045c179-6065-48f8-9fd7-699343866290)

gracias!

**Comment by tsbravo** [comment]
Hola! La forma correcta de subir la tarea es de la siguiente manera:

![tarea_bien_subida](https://github.com/IIC2143/Syllabus/assets/101281351/062b9e11-e49d-4ed9-af42-b59bd1db188e)

Es decir, tienes que subir los archivos que están dentro de tu carpeta SoccerApi al repositorio. Para tu .gitignore, puedes mantenerlo dentro de la carpeta en caso de que te sirva, pero si tienes la carpeta tester fuera de SoccerApi no debiese ser necesario ignorarla (no la estarías subiendo).

**Comment by MathiasPrett** [comment]
@tsbravo gracias!
