### ISSUE TITLE
Problema parte 3 del setup Ubuntu (RVM)

### ISSUE THREAD

**Issue by nolate26** [IIC2143/Syllabus#3]
Hola! 
Cuando intentó correr la segunda línea en la instalación de Ruby Version Manager, me tira error la consola :(.
![image](https://user-images.githubusercontent.com/80768615/184246063-8b1ee312-6848-4987-ab78-08cf8b0039ac.png)

**Comment by OrregoSilva** [comment]
Hola!
Intenta con `gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`, si falla, trata cambiando `hkp://pool.sks-keyservers.net` por alguna de las siguientes opciones:
- `hkp://ipv4.pool.sks-keyservers.net`
- `hkp://pgp.mit.edu`
- `hkp://keyserver.pgp.com`

**Comment by nolate26** [comment]
Gracias! 
Me funcionó con el segundo.

**Comment by FelipeMunozMoraga** [comment]
Hola, tuve el mismo problema que Nicolás, sin embargo ninguna de las opciones que le entregaron como respuesta me funcionó, no se si hice algo mal o cual es el error :(
![Captura](https://user-images.githubusercontent.com/101280597/184456446-b0ea26fb-d1c3-4809-8463-9707b551f9fd.PNG)

**Comment by Chumi-sun** [comment]
Buenas, a mí no me funciona con ninguno :/

**Comment by aurmeneta** [comment]
Hola, mira la respuesta en #10.

**Comment by Chumi-sun** [comment]
tampoco me resulta

**Comment by Chumi-sun** [comment]
hola disculpa, sigo necesitando ayuda con esto :/

**Comment by aurmeneta** [comment]
Prueba con `gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

**Comment by Chumi-sun** [comment]
AHÍ ME FUNCIONÓ POR FIN MUCHAS GRACIAS
