### ISSUE TITLE
Duda sobre la parte de Controller Vaccines del enunciado (Tarea 1)

### ISSUE THREAD

**Issue by gabo1243** [IIC2143/Syllabus#3]
Hola, estaba leyendo el enunciado y en la parte de Controller Vaccines aparece el método update. No entiendo por que es un update si no se cambia nada (según la definición del enunciado). Entonces no sé si ese método es un show o es un update como dice ahí.

Gracias de antemano.

**Comment by OrregoSilva** [comment]
Hola!
Es un error de enunciado, pronto lo arreglaré.
Gracias por tu comentario!
