### ISSUE TITLE
Problema paso 5 setup Mac

### ISSUE THREAD

**Issue by Vicente9** [IIC2143/Syllabus#3]
Hola, tengo un problema en el paso 5. No he podido solucionarlo.
<img width="563" alt="Screenshot 2024-03-11 at 6 31 00 PM" src="https://github.com/IIC2143/Syllabus/assets/101224081/37643e14-7e14-48a2-ba07-352b30c97fe3">

**Comment by jtvaldivia** [comment]
Hola, 
Escribe la issue en el setup porfavor y ahi te respondo.
