### ISSUE TITLE
Error al correr los tests en Python

### ISSUE THREAD

**Issue by BastianCardenash** [IIC2143/Syllabus#30]
Hola, estuve tratando de probar con los nuevos test que mandaron para la tarea, pero me tira un error cuando trato de iniciarlos (solo me pasa con el 1, el 2 y el 3, los 26 test de postman y el test 0 me corren perfectamente). 

![image](https://user-images.githubusercontent.com/93230420/227801022-529ff17f-2b94-4155-8262-c43e3111bb5e.png)

**Comment by gaboaurora** [comment]
Aquí el mismo error, con todos los test desde el 1 hasta el 3 😔

**Comment by Balison** [comment]
Hola, me falta información para ayudarles, asi que me gustaria que me manden un screenshot del codigo de su metodo create del controlador de vacunas.

**Comment by agustind1** [comment]
Hola Balison, por donde te puedo mandar un screenshot del metodo? tengo el mismo error en los test 1 al 3, y el cero me funciona bien.

**Comment by Balison** [comment]
Hola, mandame un correo a afernandb@uc.cl. Necesito screenshot de: (i) controlador de vacunas (método create), (ii) archivo de rutas y (iii) modelo de vacunas.

**Comment by gaboaurora** [comment]
Hola! Resolví el problema colocando `if/else/end` en el `save` de _Create_ en Vaccines y en el _Update_ de _Vaccines_. Este requerimiento, sobre el manejo de errores es pedido en el _Create_ de _Persons_, usando el `errors` para la variable que esta intentando ser guardada. En el anuncio, la parte es _...caso contrario retorna un error_ (`render json: @person.errors, status: :unprocessable entity`). No esta en el enunciado esto para _Vaccines_, pero colocando esto se resuelven los test 1 y 3.
