### ISSUE TITLE
Recordar credenciales de git

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2143/Syllabus#30]
Hola. Quiero que git deje de solicitar mi usuario y token personal cada vez que use el comando `git push`. ¿Alguien sabe como se hace eso? Recuerdo que en programación avanzada funcionaba asi, no sé qué cambió 👀

**Comment by meretamal** [comment]
Hola 😁 , lo que puede hacer es setar git para que use ssh:

* [Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
* [Adding a new SSH key to your GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)

Después de eso te pedirá el token una vez más hasta que expire nuevamente (puedes hacer que no expire)

**Comment by MathiasPrett** [comment]
bacan, gracias!
