### ISSUE TITLE
Typo en expected_output

### ISSUE THREAD

**Issue by Artaudd** [IIC2143/Syllabus#30]
Hola!, noté que en el expected_output, cuando se muestra la informacion aldeanos, la primera línea dice "COMIENZA INFORMACION AlDEANOS" con l minúscula, mientras que en el enunciado se pedía que el mensaje fuera completamente en mayúsculas. ¿Deberíamos modificar nuestro código para que aparezca con l minúscula o en la revisión se utilizará la línea corregida?

**Comment by maggiemunoz** [comment]
Hola! Se utilizará la linea corregida, voy a subir el expected_output corregido :)
