### ISSUE TITLE
Duda sobre archivo de output

### ISSUE THREAD

**Issue by Artaudd** [IIC2143/Syllabus#31]
Hola! Tengo una duda, ¿es necesario que el archivo de output se reinicie si es que el programa principal se ejecuta por una segunda vez? ¿o basta con que el nuevo output se agregue al final del archivo?

**Comment by maggiemunoz** [comment]
Hola! Si, el archivo de output.txt debe reiniciarse y escribirse denuevo cada vez que se ejecuta el código :)

**Comment by mpmunoz13** [comment]
@maggiemunoz Hola, no me queda claro lo que se pide aqui. El código se va a correr más de una vez al ser evaluado? Donde podemos encontrar información sobre eliminar archivos al correr el código? No sabemos el orden de los metodos a ejecutar por lo que no sé como identificar cuando debe partir de cero el output file.
