### ISSUE TITLE
Paso 5 para mac

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#31]
Hola!
En la parte en que hay que hacer un usuario con el nombre del usuario del sistema, dice que si al ejecutar \du no aparece creado, ejecutemos un código para crearlo. Yo al ejecutar \du me apareció una especie de tabla donde aparecía mi usuario y sus atributos.
En ese caso hay que seguir con el paso 6 o hay que crear otro usuario? no dice nada al respecto.

**Comment by simonmb12** [comment]
uno de los atributos es el de superuser

**Comment by meretamal** [comment]
Hola 😁 . Claro, si es que ya está creado, puedes seguir con los pasos siguientes. En mac es común que venga creado junto con la instalación de postgres
