### ISSUE TITLE
PG::ConnectionBad: FATAL: role "*" does not exist

### ISSUE THREAD

**Issue by Franbelen** [IIC2143/Syllabus#32]
Hola buenas, me sale este error al correr rails s , _FATAL: role "fran" does not exist_ , no se si se refiere al usuario creado en los pasos anteriores porque si lo cree y con el mismo nombre

**Comment by meretamal** [comment]
Hola, se refiere al usuario de postgres que debiste haber creado en un paso anterior. Para confirmar esto, podrías ingresar a una consola de psql y ejecutar `\du`? Eso te mostrará un listado de todos los usuarios de postgres creados.

**Comment by Chumi-sun** [comment]
Hey hola, tengo un error similar. 
![imagen](https://user-images.githubusercontent.com/101197947/188227218-0bba8eab-7bf1-4b3a-82c1-bc394bcd7748.png)
Pero me sale root y no recuerdo haber escrito eso nunca.

Si corro el comando \du en mi consola de psql me sale lo siquiente:
![imagen](https://user-images.githubusercontent.com/101197947/188227625-349bb445-78ff-4f7b-aef9-8f09a188f62e.png)

¿Cómo lo puedo solucionar?

**Comment by meretamal** [comment]
Hola, si te fijas el usuario de tu sistema es root. Cuando no le pasas un usurio a la conexión de psql, por defecto intentará usar uno que se llame igual al usuario de tu sistema, entonces probable que no se esté leyendo bien tu archivo .env.

Revisa [esta solución ](https://github.com/IIC2143/Syllabus/issues/12#issuecomment-1218536754)de una issue pasada

**Comment by Chumi-sun** [comment]
Hey buenas, seguí la guía del link que me mandaste.

![imagen](https://user-images.githubusercontent.com/101197947/188230595-faa257d5-288f-4ed1-bba2-580993c36515.png)
Ahora me sale esto, eso solo significa que estoy poniendo la contraseña mal cierto?

**Comment by meretamal** [comment]
Revisa esta issue: https://github.com/IIC2143/Syllabus/issues/18

**Comment by Chumi-sun** [comment]
Pues el nombre de mi usuario es Domingo Veloso. ¿O tiene que ser el de Ubuntu?

**Comment by meretamal** [comment]
Tiene que ser el de ubuntu

**Comment by Chumi-sun** [comment]
![imagen](https://user-images.githubusercontent.com/101197947/188233524-e00a8e61-c620-4795-bee5-8a0b41ba8867.png)
Por fin!!
Muchas gracias!!
