### ISSUE TITLE
Orden de información

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC2143/Syllabus#32]
Hola! Al hacer patch/matches/:id me actualiza la información pero me cambia el orden de los atributos, debo solucionar eso o da lo mismo siendo que estos no son posicionales?
![Captura de pantalla (51)](https://github.com/IIC2143/Syllabus/assets/141789725/45ad79a8-0241-47d4-99e3-63da204892b0)

El response dice que debe ser así:

![Captura de pantalla (52)](https://github.com/IIC2143/Syllabus/assets/141789725/b1c24adf-94ac-4d37-a15f-7da4e7236995)

**Comment by SFCYang** [comment]
Up! Yo también tengo la misma duda :,(

**Comment by AAromero1** [comment]
Hola, puedes probar eso con el test_2A, el resultado 16 es sobre patch.
