### ISSUE TITLE
Orden del response de 3.4 [GET /players/topAssists/:quantity] test [test_3A.py]

### ISSUE THREAD

**Issue by clumsypunch** [IIC2143/Syllabus#33]
Hola,

He notado que mi respuesta al test es correcta en su conjunto, pero parece que están esperando que esté ordenada de alguna manera implícita. Esto ya me ha ocurrido en secciones anteriores, donde los tests aguardaban resultados ordenados de forma específica. Por lo tanto, me gustaría conocer el orden preciso en el que esperan que devolvamos el JSON del request del título. Sugiero que en futuras ocasiones, se incluya una indicación clara sobre el orden que se debe seguir, ya sea mediante un aviso o una instrucción explícita. Esto garantizará una mejor comprensión y cumplimiento de los requisitos del test.

Gracias por tu atención,

```javascript
Response:
{
    "id": 46,
    "name": "Cristian Ruz",
    "goal": 10,
    "assist": 4,
    "card": 0,
    "team_id": 366
}
{
    "id": 52,
    "name": "Chupete Suazo",
    "goal": 12,
    "assist": 1,
    "card": 0,
    "team_id": 368
}
{
    "id": 49,
    "name": "Sebatian Saez",
    "goal": 2,
    "assist": 1,
    "card": 0,
    "team_id": 367
}
{
    "id": 51,
    "name": "Felipe Flores",
    "goal": 3,
    "assist": 2,
    "card": 1,
    "team_id": 367
}

Expected:
{
    "id": 46,
    "name": "Cristian Ruz",
    "goal": 10,
    "assist": 4,
    "card": 0,
    "asist": 4,
    "team_id": 366
}
{
    "id": 49,
    "name": "Sebatian Saez",
    "goal": 2,
    "assist": 1,
    "card": 0,
    "asist": 1,
    "team_id": 367
}
{
    "id": 52,
    "name": "Chupete Suazo",
    "goal": 12,
    "assist": 1,
    "card": 0,
    "asist": 1,
    "team_id": 368
}
{
    "id": 51,
    "name": "Felipe Flores",
    "goal": 3,
    "assist": 2,
    "card": 1,
    "asist": 2,
    "team_id": 367
}
```

**Comment by tomastrivino** [comment]
Apoyo. De todos modos lo arreglé sorteando por ID el resultado final.

**Comment by daniel-finkelstein** [comment]
Como lo hiciste para ver el output asi?

**Comment by clumsypunch** [comment]
Tests `test_3A.py`  con el parametro `show` `25: get_player_top_cards(players, 4, show=True)`, pero todavia estoy esperando respuesta del orden que quieren que los entregemos, si es que lo quieren con orden o no.
