### ISSUE TITLE
Paso 9 en Mac

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#33]
Para crear la base de datos, tengo que poner "cd <nombre proyecto>" antes y después correr "rails db:create"?. Hice el paso 8 y cerré la terminal. Abro una terminal nueva, y al correr "rails db:create" me aparecen hartos pasos y luego este mensaje: Example:
    rails new ~/Code/Ruby/weblog

    This generates a skeletal Rails installation in ~/Code/Ruby/weblog.

Después copio y pego los pasos 10 y 11, pero al ir a la dirección localhost:3000 me sale que safari no pudo conectarse al servidor.

**Comment by meretamal** [comment]
Hola 😁 . Todos los comandos de rails los debes correr en tu proyecto.

Los comandos para ingresar a una consola de psql los puedes correr en cualquier lados.

Dime si con eso se solucionan tus dudas 😉 .
