### ISSUE TITLE
Error que antes no tenía :(

### ISSUE THREAD

**Issue by Lexiesm** [IIC2143/Syllabus#33]
Holaaa!! El viernes terminé la tarea y la subí. Hoy me meti a probar los test .py y me funcionaban 2 de 4, en algún momento hice un un rails db:migrate:reset y me salio este error:
![imagen](https://user-images.githubusercontent.com/101207522/227809568-353f08a4-3b8b-4f3b-831d-a60f462b899d.png)

el problema es que ahora por eso es que no me funciona ninguno request, nisiquiera los de postman que me funcionaban todos :(. Probé eliminando mi API y haciéndola de nuevo y sigue el mismo error :(. 
Ya no se qué hacer :(((

**Comment by OrregoSilva** [comment]
Prueba con `rails db:drop db:create db:migrate`, eso debería reiniciar la base de datos.
