### ISSUE TITLE
Error link plantilla de los grupos

### ISSUE THREAD

**Issue by Simon-Cabrera** [IIC2143/Syllabus#34]
Hola, tengo un problema para acceder a la plantilla de los grupos de proyecto. En la página me aparece que no tengo acceso al recurso al ingresar con el correo UC. También probé con mi correo de GitHub y tampoco funcionó.

**Comment by jtvaldivia** [comment]
Lo acabo de actualizar, intenta ahora

**Comment by Simon-Cabrera** [comment]
Hola, me sigue arrogando el mismo error.

**Comment by jtvaldivia** [comment]
Mandame tu correo para agregarte personalmente

**Comment by Simon-Cabrera** [comment]
Ahora si, gracias 👍🏻
