### ISSUE TITLE
unknow attribute "teamA" for Match

### ISSUE THREAD

**Issue by anticarasosman** [IIC2143/Syllabus#34]
Buenas estoy teniendo problemas creando una nueva match que pertenezca a uno de los equipos
![imagen_2024-03-20_162645314](https://github.com/IIC2143/Syllabus/assets/94928628/67339a0f-18ea-4d9e-9b39-0ff1465a63b1)
Tengo escrito eso pero cuando intento escribir una instancia de matches me sale el siguiente error:
![image](https://github.com/IIC2143/Syllabus/assets/94928628/9092ffde-5370-4120-ac35-e6139a323632)

**Comment by tsbravo** [comment]
Hola! Eso significa que tu tabla no tiene el atributo “teamA”. Tienes que revisar tu schema para ver qué nombre efectivamente tiene esa columna en la tabla Matches (probablemente teamA_id).
