### ISSUE TITLE
Setup Windows: Error al correr el servidor

### ISSUE THREAD

**Issue by miguelsifri** [IIC2143/Syllabus#34]
Hola! Al momento de ingresar al servidor a través del link indicado, me arroja el siguiente error.
![error_setup](https://user-images.githubusercontent.com/89413768/159700868-88414bec-3a99-4385-b1ba-33acba9150a7.png)

**Comment by sebacarrasco** [comment]
Holaa, lo más probable es que sea que no tienes corriendo el servicio de postgres. Corre `sudo service postgresql start` para correr postgres y luego recarga la página.

**Comment by miguelsifri** [comment]
Ahí me funcionó, muchísimas gracias!
