### ISSUE TITLE
Contraseña superuser

### ISSUE THREAD

**Issue by adribastiasm** [IIC2143/Syllabus#35]
Hola! Seguí todos los pasos del setup para Mac pero ahora que intento poner 'sudo service postgresql star't y me pide la contraseña me sale que es incorrecta y busqué en google e intenté cambiar la contraseña pero sigue sin funcionarme.
¿Hay otra forma de cambiar la contraseña? o que puedo hacer al respecto?

**Comment by tomastrivino** [comment]
Cuando haces un comando `sudo` tienes que poner la contraseña de tu usuario del mac!
