### ISSUE TITLE
Problematica al intentar hacer git push heroku 

### ISSUE THREAD

**Issue by benja20029** [IIC2143/Syllabus#35]
Buenas, he estado intentando linkear de alguna manera el repositorio con heroku mediante el tutorial del semestre anterior, tuve varios errores pero los arregle como por ejemplo, que ruby 2.6.6 solo soportaba hasta heroku-20. Sin embargo, no he podido arreglar este error asi que si saben que hacer seria bacan porfas :(. 
![image](https://user-images.githubusercontent.com/81534737/187048796-9872b28c-1982-487e-a841-e21234613d2a.png)

**Comment by benja20029** [comment]
De todas maneras, según vi, heroku dejaba de ser gratis en noviembre por lo que podría traer problemas. No será mejor migrar a otra plataforma?

**Comment by Fernanda1232123** [comment]
¿como resolviste que ruby 2.6.6 solo soporta heroku-20? Estoy teniendo el mismo problema

**Comment by nbarriav** [comment]
Hola, que buildpacks tienes en tu app en heroku? El error puede ocurrir por no tener node en los buildspacks que le pones a tu aplicación en heroku

**Comment by benja20029** [comment]
Buenas, probé añadiendo el buildpack de node js y ruby por default pero tampoco me funciono :(

**Comment by aurmeneta** [comment]
En el root de tu proyecto debería haber un archivo llamado `package.json`. Modifica ese archivo y agrega `"engines": {
    "node": "14"
  },` para que se vea algo así como el siguiente:

```json
{
  "name": "nombre_proyecto",
  "engines": {
    "node": "14"
  },
 ...
}
```

Avísame cómo te va con esto.

**Comment by Fernanda1232123** [comment]
Hola! Tenía el mismo error que quien escribió la issue. Hice lo que @aurmeneta sugirió y tengo otro error, parece que fuera como si no me reconociera el "node": "14". 
Para dar contexto, tengo una carpeta donde están los archivos del proyecto que son los que se bajaron con la instalación inicial. Sobre ese archivo cambié lo que @aurmeneta dijo. Tengo otro archivo llamado heroku, donde copié y pegué lo que tengo en el archivo del proyecto (incluido los cambios). Sobre ese archivo hago git add ., git commit y git push.
 Este es el error
![Screen Shot 2022-09-01 at 14 13 12](https://user-images.githubusercontent.com/89221305/187984974-ccb8bcda-918c-4259-9e0e-f25dcc30ba2a.png)


Además, tengo otras dudas. 
Esta el github projects, además del repositorio privado del grupo. En mi computador tengo una carpeta heroku, una carpeta proyecto que es lo que se instaló en la instalación inicial del ramo y una carpeta con mi repositorio privado. Entiendo como funciona heroku, pero como funciona la carpeta del proyecto, la carpeta del repositorio privado, github repositorio privado del grupo y github projects???

**Comment by Fernanda1232123** [comment]
Hola! Resolví los dos primeros errores con los comandos

heroku buildpacks:add heroku/nodejs
heroku buildpacks:add heroku/ruby

Ahora tengo este error, a pesar de que puse lo que @aurmeneta escribió
![Screen Shot 2022-09-02 at 11 17 37](https://user-images.githubusercontent.com/89221305/188181163-e97bf4a5-7c39-440e-852a-96acbee25709.png)

**Comment by MrBased** [comment]
### @Fernanda1232123 @benja20029 Encontre como solucionar el problema de:
![image](https://user-images.githubusercontent.com/24458834/188247276-5e439ee5-b220-4ce0-9dc6-c7dc2219e533.png)

Deben hacer lo que sale acá en [este comentario que hay en una issue](https://github.com/rails/webpacker/issues/512#issuecomment-804600063)

**Comment by vjimenezs** [comment]
Hola! Nos han aparecido los mismo problemas que mencionan arriba, y no lo hemos logrado resolver. En específico nos aparece lo siguiente

![Screenshot (715)](https://user-images.githubusercontent.com/89430865/188517470-e690e257-a564-48ee-8c8a-d28c247034b3.png)

Hemos intentado todo esto:

"@rails/webpacker": "5.2.1" en dependencies de package.json
sudo apt install webpack
bundle exec rake app:update:bin
heroku buildpacks:add heroku/ruby
heroku buildpacks:add heroku/nodejs
heroku stack:set heroku-20

Nos pueden ayudar por favor?:((

**Comment by MrBased** [comment]
Ojo que el orden en el que estan aplicados los buildpacks también afecta. A algunos se les soluciona el problema poniendo NodeJs sobre Ruby como se muestra en las settings de la app en Heroku. 
Debería verse así:
![image](https://user-images.githubusercontent.com/24458834/188518677-434923f0-afa1-4719-b786-a9783b152d54.png)

Tal vez ya lo hiciste, pero también te recomiendo leer todos los comentarios de la misma issue de la que hablaba antes [(Link a la issue)](https://github.com/rails/webpacker/issues/512#issuecomment-804600063)

**Comment by aurzuav** [comment]
hola, tenía el mismo problema de webpack not found, agregue el "@rails/webpacker": "5.2.1" en dependencies de package.json y los builpacks en heroku. Pero ahora me aparece este error... porfavor ayuda :(

![Screen Shot 2022-09-08 at 15 56 11](https://user-images.githubusercontent.com/62019560/189214601-d9fd1ff7-a8ff-4b47-93fc-b0895565d59b.png)

**Comment by MrBased** [comment]
Intenta esto [Link 1](https://stackoverflow.com/a/52671779) o esto [Link 2](https://stackoverflow.com/questions/70401055/unable-to-build-and-deploy-rails-6-0-4-1-app-on-heroku-throws-gyp-verb-cli-err) (Me tinca que este último es más probable que te ayude)
