### ISSUE TITLE
Error Setup Windows paso 8

### ISSUE THREAD

**Issue by ctoro05** [IIC2143/Syllabus#36]
Hola! En el momento que intento crear el proyecto e instalar bundle me encuentro con el siguiente error: 

Gem::RemoteFetcher::UnknownHostError: timed out (https://rubygems.org/gems/xpath-3.2.0.gem)
An error occurred while installing xpath (3.2.0), and Bundler cannot continue.
Make sure that `gem install xpath -v '3.2.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  capybara was resolved to 3.36.0, which depends on
    xpath

Como puedo resolverlo? Muchas gracias!

**Comment by jadawabe** [comment]
Hola! pudiste solucionarlo?
