### ISSUE TITLE
Cómo subir de manera correcta sin mover contenido de SoccerApi

### ISSUE THREAD

**Issue by rodrigooflores** [IIC2143/Syllabus#36]
Hola, tengo una duda acerca de cómo subir correctamente la tarea a mi repositorio.

Entiendo que deben estar todos los archivos de la carpeta `SoccerApi/` en la raíz de mi repositorio, pero me gustaría saber si hay una mejor forma de subirlos usando `git push` sin tener que mover los contenidos de la carpeta `SoccerApi/` en mi computador. Sé que podría simplemente utilizar `ctrl-x` `ctrl-v` a todos los archivos (o equivalentemente usar `mv -v ~/2024-1-Raiz-de-mi-repositorio/SoccerApi/* ~/2024-1-Raiz-de-mi-repositorio/` en la terminal de wsl), pero me preocupa que afecte a las convenciones que se usan en Ruby y Rails u ocurra un problema similar.
Espero se entienda mi duda, gracias de antemano :smiley:

**Comment by AAromero1** [comment]
Al copiar la carpeta, no exiten problema de compatibilidad, dado que al copiar todos los archivos , la configuracion es la misma asi que de eso no te preocupes, la unica diferencia es que ahora deberas utilizar rails server en la nueva direccion.
Pero si aun asi tienes dudas puedes hacerlo con git
Primero en la direccion SoccerApi/ tienes que iniciarlo como repo de git
`git init`
Luego agregas todo 
`git add .`
**Te recomiendo configurar el .gitignore en SoccerApi antes de hacer todo**
Generas el commit 
`git commit -m "mensaje"`
Y vinculas el repo 
`git remote add origin <URL del repositorio >`
Por ultimo haces el push
`git push -u origin main`
Eso mandara todo a tu rama main, en el repositorio de git. 
Espero que te haya servido ;)

**Comment by esperanzaacevedo** [comment]
Hola, al seguir esos pasos la consola me muestra el siguiente error. 

! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/IIC2143/2024-1-Tarea-esperanzaacevedo.git'

**Comment by AAromero1** [comment]
Ah si, disculpa, Primero tienes que ocupar 
`git pull origin main`
para tener los archivos que estan dentro del repo. "El Readme"
Despues te deberia dejar hacer push dado que ya esta actualizado. Si ya modificaste el readme en tu Aplicacion, te recomendo guardarlo porque se remplazara

**Comment by esperanzaacevedo** [comment]
Hola!. No me funciona :( lo estoy haciendo desde 
esperanzaacevedoroman@MacBook-Air-de-Esperanza SoccerApi %

**Comment by rodrigooflores** [comment]
Hola, a mí tampoco me funciona. 
Al usar el comando `git pull origin main` me aparece el siguiente error:
![Captura de pantalla 2024-03-21 222058](https://github.com/IIC2143/Syllabus/assets/141890277/eea38ca9-c88a-4d80-a875-2ece4713fe04)

Y cuando uso `git status` en la carpeta SoccerApi/ me aparece "On branch main nothing to commit, working tree clean", a pesar de que en la nube de mi repositorio no aparece ningún archivo más que el readme inicial.

**Comment by AAromero1** [comment]
Ese problema es que hay que resolver el conflicto de pull locamente, es decir existen archivos en tu carpeta que están en github y no se sabe cual se mantiene.

Por esos problemas de git , les recomiendo copiar y pegar los archivos en la carpeta y subirlos todos con

Git add .
Git comit -m ""
Git pull

**Comment by rodrigooflores** [comment]
Hola, al final lo que me funcionó fue clonar mi repositorio y crear el proyecto otra vez, y luego borrar la carpeta .git y el README generado por el proyecto y reemplazarlos por los que estaban en la raíz de mi repositorio. Luego en la carpeta SoccerApi/ usé `git add .`, `git commit -m"mensaje"` y `git push` y se subió correctamente a la raíz.
Muchas gracias!
