### ISSUE TITLE
Vincular Github project al repositorio del proyecto

### ISSUE THREAD

**Issue by isufan** [IIC2143/Syllabus#36]
¡Hola! Con mi grupo queríamos saber si hay alguna manera en que se pueda vincular nuestro Github project al repositorio del proyecto en Github. He visto que se puede pero cuando vamos a la pestaña "Projects" dentro del repositorio, aparece un link diciendo "Go to the IIC2143 organization to create a new project" y al pinchar el link, no aparece la opción de crear un nuevo proyecto. 
Por el momento estamos usando un Github project aparte que no está vinculado al repositorio del proyecto, por lo que sería mucho más conveniente si se puede acceder desde el mismo repositorio.
Muchas gracias de antemano.

**Comment by rlabb** [comment]
Estamos con el mismo problema!

**Comment by JupaOlivares** [comment]
Hola! 

Recomiendo crear uno desde el perfil y de ahi ir agregando los links a issues o commits del proyecto: 
https://docs.github.com/es/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects#adding-issues-to-your-project
https://docs.github.com/es/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects#adding-a-board-layout

Esas 2 secciones de la guia de projects podrían ser de ayuda (y la guía en general tambien)

**Comment by gonzaloi21** [comment]
Pero entonces como hacemos para trabajar cada uno desde su computador? Como por ejemplo al escribir los relatos.

**Comment by isufan** [comment]
> Pero entonces como hacemos para trabajar cada uno desde su computador? Como por ejemplo al escribir los relatos.

Se le puede dar acceso a los demás integrantes del grupo para que también puedan editarlo. Estando dentro del project creado para el grupo, en Settings >  Manage access, se pueden configurar los accesos.

**Comment by simonmb12** [comment]
Hola! no entiendo bien cómo va a funcionar esto. Cree un proyecto desde mi perfil, hice issues y traté de enlazarlo con el repositorio del proyecto pero no me aparecía como opción. Después hice una issue directamente en el repositorio de mi grupo, copié el link y lo pegue dentro de mi proyecto. Ahora le hago cambios a esa issue desde mi proyecto pero no se ven reflejados en mi repositorio del grupo.

**Comment by Cinaraa** [comment]
Hola!
Estaba pensando, y para resolver este problema de manera parche, ¿podríamos crear un repositorio público aparte y linkear ese repositorio con el proyect de GitHub, y hacer un issue en el repositorio oficial que dirija directamente al repositorio "Place Holder"?
