### ISSUE TITLE
Ubicación tester

### ISSUE THREAD

**Issue by espeescobar** [IIC2143/Syllabus#36]
Hola, estoy intentando correr el tester pero no ocurre nada. En que parte en relación a la carpeta de GamersApi debe encontrarse los archuvos del tester?

**Comment by Pablo-Gonzalez-Calderon** [comment]
Según yo, no está relacionado con la ubicación de la carpeta GamersApi.

Para correr los tests deberías haber iniciado tu servidor de GamersApi, poniendo (dentro de tu carpeta del proyecto de RoR):
```bash
rails server
```

y luego, en la carpeta del repo de los tests, correr los comandos que salían en el README:
```bash
python3 backend/main.py
python3 -m http.server 8000
```
Y finalmente abrir http://localhost:8000/frontend/test/ para ver un resultado de los tests :)

A fin de cuentas, en tu consola no se debería ver nada porque todo ocurre por detrás, y sólo puedes ver los resultados en el link mencionado.

No sé si a eso te referías 🤧

**Comment by FelipeMunozMoraga** [comment]
Hola! Tal y como indica Pablo, el tester no debe estar relacionado con la carpeta GamersAPI y deben utilizar 2 consolar para correr el tester cuando esté corriendo el server.
Saludos!
