### ISSUE TITLE
Problema subir tarea

### ISSUE THREAD

**Issue by MaximilianWilke** [IIC2143/Syllabus#36]
Hola, trate de subir la tarea realizando el gitclone, la cosa es que cuando intento realizar el git add . en el directorio donde esta el git clone, me dice que he añadido un repositorio dentro del repositorio actual, por lo que me tira error, y no se donde esta este otro repositorio. 
<img width="416" alt="image" src="https://user-images.githubusercontent.com/101229477/228042903-3c838674-6070-4394-b6cd-56bf7ec0130b.png">

**Comment by OrregoSilva** [comment]
Eso es porque tienes un repositorio de git dentro de otro, al clonar el repo, este ya viene con una carpeta .git linkeada al repositorio de entrega, pero, al crear el proyecto, rails genera otro de forma automática.
Trata de dejar todo lo generado por rails al mismo nivel que el repo clonado.
