### ISSUE TITLE
Convertir labls de Github proyects a issues

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2143/Syllabus#37]
Hola! Dentro de la cápsula n°1 de Github Proyects, hay un momento en que el ayudante convierte lables (historias) a issues dentro de un repositorio (minuto 4:25 del video). Mi problema es que al hacer lo mismo no me aparece el repositorio de mi grupo como opción. 

Gracias

**Comment by isufan** [comment]
Hola, a nosotros nos pasó lo mismo y al parecer es porque sólo muestra como opciones los repositorios creados por ti, al haber creado un project desde el perfil. Por eso no muestra el repositorio de tu grupo.  La mejor opción sería hacer lo que se mencionó en la issue #36, de seguir las instrucciones de esta página: https://docs.github.com/es/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects#adding-issues-to-your-project
De todas maneras me gustaría que un ayudante lo confirmara si es posible, quizás haya otra solución.

**Comment by NicoJGutierrez** [comment]
Hola, nosotros tenemos un problema parecido que es que cuando queremos crear un nuevo proyecto nos manda a la página de la organización, donde no podemos crear proyectos.
Página de crear proyectos en mi grupo:
![image](https://user-images.githubusercontent.com/80768621/188339655-8578bea7-0611-4186-bfac-b30f9f26ec0c.png)
Página de la organización:
![image](https://user-images.githubusercontent.com/80768621/188339640-5ba87653-0afb-486d-8502-70b1e97add63.png)

**Comment by JTUnger** [comment]
Algun update de esta issue?

**Comment by Javo2804** [comment]
Creo que la única solución es la que mencionó @isufan de la issue #36. Básicamente crear los issues en el repositorio del grupo, luego copiar los links y pegarlos en el Github Project. [Aquí](https://docs.github.com/es/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects#adding-issues-to-your-project) se indica cómo pegar esos links.
