### ISSUE TITLE
duda subir tarea

### ISSUE THREAD

**Issue by Agustinuc** [IIC2143/Syllabus#37]
hola, es que al intentar copiar el repositorio en mi computador para poder subir la tarea me aparece el siguiente error 
<img width="667" alt="Captura de Pantalla 2023-03-27 a la(s) 21 50 22" src="https://user-images.githubusercontent.com/89665265/228098576-4cd75365-caa3-41d6-aca0-bf404b273802.png">

**Comment by psepulveda99** [comment]
Me pasa lo mismo en Windows
