### ISSUE TITLE
Duda test n19 de 2B y test n29 de 2C

### ISSUE THREAD

**Issue by jorgee02** [IIC2143/Syllabus#38]
Hola! Una pequeña consulta:
El n19 de 2B me falla. Sin embargo, si no me equivoco, sobre lo que se intenta hacer patch es {'id': None, 'teamA': None, 'teamB': None, 'state': True, 'result': '6-0'}, donde el id es None. De esta forma, me parece que no debería encontrar un id de partido?

El n29 de 2C me falla por razones similares, pues se intenta borrar {'id': None, 'name': 'Santiago Wanderers', 'stadium': 'Elías Figueroa Brander', 'capacity': 18000, 'city': 'Valparaíso', 'players': [], 'matches': []}, y nuevamente el id es None, por lo que me parece que no debería encontrar equipo, o sí? Que sale "Deberá eliminar el equipo cuya id coincida con la entregada en la url".

Quedo atento a cualquier comentario, muchas gracias.

**Comment by jtvaldivia** [comment]
Hola, jorge tienes actualizado el tester?

**Comment by jorgee02** [comment]
Creo que síi, cloné el repo dsp del anuncio que mandaron. De todas formas, hice pull recién y ya estaba al día.

**Comment by jtvaldivia** [comment]
Por alguna razon estas recibiendo mal la informacion, el patch se esta haciendo sobre un partido que les hiciste post antes y el delete lo mismo. Probablemente tienes un error haciendo el post

**Comment by jorgee02** [comment]
Ahh me parece, muchas gracias José Tomás!

**Comment by franfonte** [comment]
Hola @jorgee02  al final te funcionaron??? que me fallan justo los dos que te fallan a ti

**Comment by jorgee02** [comment]
Hola! 
Sí, me funcionaron. Tuve que modificar algunos aspectos de los modelos, pero no del post como pensé en su minuto.

**Comment by franfonte** [comment]
Gracias, al final mi problema era que los partidos al borrarse borraban a los equipos
