### ISSUE TITLE
Git Push heroku [heroku-20] [heroku-22] [ruby2.6]

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2143/Syllabus#38]
Hola!

Estoy teniendo un problema con el git push de heroku. El error dice que ruby 2.6.6 solo soporta heroku-20. ¿Qué se hace en este caso? 
Alguien preguntó algo parecido en una issue y le pregunté como resolverlo. Pero no entendí si la respuesta que le dieron fue a él o a mi, por eso lo pregunto de nuevo!

Aquí hay una screenshot del error.
![Screen Shot 2022-08-31 at 15 44 39](https://user-images.githubusercontent.com/89221305/187768526-c80d28ba-48cf-4af7-9b5c-6527b57cf2fb.png)
Gracias!

**Comment by aurmeneta** [comment]
Hola, intenta cambiando el stack de heroku a heroku-20.

Esto lo puedes hacer ejecutando `heroku stack:set heroku-20` en el terminal. Si tu cuenta tiene más de una app de heroku asociada, el comando es `heroku stack:set heroku-20 -a <nombre_app>` Donde `<nombre_app>` es el nombre de la aplicación de heroku que usas para el proyecto.

**Comment by Fernanda1232123** [comment]
funcionó gracias
