### ISSUE TITLE
AssertionError en tests de Postman

### ISSUE THREAD

**Issue by eduesquivel** [IIC2143/Syllabus#38]
Hola, al correr los tests de Postman me aparece el siguiente mensaje:

![image](https://user-images.githubusercontent.com/101527207/228106289-41d31b05-a145-43f0-bf79-f1edfdef2966.png)

Todos los tests anteriores dan el resultado esperado, asi que no se que puede ser. Mi hipotesis es que los tests esperan que vaccine_date tenga el formato "2022-01-20", siendo que el body que envia esta en formato "20/01/2022".

**Comment by FelipeMunozMoraga** [comment]
Hola! Cuando creaste el modelo definiste que vaccine_date fuera un dato del tipo date? Puede que el error sea por no definirlo como fecha

**Comment by eduesquivel** [comment]
Efectivamente, eso arreglo los testcases. Muchas gracias!
