### ISSUE TITLE
Migraciones pendientes en repositorio

### ISSUE THREAD

**Issue by KrishelC** [IIC2143/Syllabus#39]
Hola! Tengo un problema al intentar testear el código subido al repositorio asignado para la tarea.
Para probar si todo fue subido correctamente hice un git clone del mismo repostorio de mi tarea en otra ruta, pero al intentar realizar cualquier acción (get, post, etc.) en consola me aparece el mensaje de la imagen adjunta.
Cabe destacar que ya había ejecutado el comando "rails db:migrate" con anterioridad y el servidor funcionaba correctamente, lo mencionado solo ocurre al testear el proyecto subido al repositorio.
¿Cómo soluciono esto? o ¿dejo escrito en el README que se ejecute el comando "rails db:migrate" antes de correr los tests? (el problema se soluciona de esta manera)
![a](https://user-images.githubusercontent.com/110860026/228113571-e28e9430-4c64-4bcd-95a1-802f3d4dac62.png)

**Comment by OrregoSilva** [comment]
Hola!
Ese comando se ejecutará antes de cada corrección, ya que al final actualiza el esquema de la base de datos a lo requerido por la aplicación, por lo que en ese sentido no es necesario explicitarlo.

**Comment by KrishelC** [comment]
Ok, gracias!
