### ISSUE TITLE
[Tarea] Salto de línea extra en el archivo output_file.txt

### ISSUE THREAD

**Issue by pilarjimenez** [IIC2143/Syllabus#39]
Hola!
En el archivo de output esperado que nos pasaron existe un salto de línea extra luego de todo el contenido. ¿Este está demás o tengo que considerarlo en mi solución?

**Comment by lpalacios1** [comment]
me pasa lo mismo, comento para saber cuando te den la respuesta :)

**Comment by maggiemunoz** [comment]
Hola! No se preocupen, no vamos a considerar esa linea al evaluar sus outputs :)
