### ISSUE TITLE
Heroku: No default language could be detected for this app

### ISSUE THREAD

**Issue by Sebah01a** [IIC2143/Syllabus#39]
Hola, estaba siguiendo los pasos del video capsula 1 git y heroku. Estaba funcionando todo bien pero en el ultimo paso, donde hay que correr $ git push heroku main, me dio este error. Que puedo hacer?

![image](https://user-images.githubusercontent.com/89041986/187827112-63eb7e61-40d7-4659-a941-024f0b4d1903.png)

**Comment by simonmb12** [comment]
Hola! tengo el mismo problema. Este paso se hace cuando ya tenemos la aplicación lista? En la cápsula lo hace justo después de instalar el programa y sin haber hecho ningún cambio

**Comment by JupaOlivares** [comment]
> Hola! tengo el mismo problema. Este paso se hace cuando ya tenemos la aplicación lista? En la cápsula lo hace justo después de instalar el programa y sin haber hecho ningún cambio

La aplicacion debe estar creada para hacer el push heroku, tu error puede ser porque generalmente la aplicacion se crea dentro de una carpeta y no queda a la "vista" en el directorio raiz

**Comment by simonmb12** [comment]
Pero no entiendo dónde hacer la aplicación, si se supone que esta se hace en heroku o no?

**Comment by Sebah01a** [comment]
Y como puedo hacer para que mis archivos de la app  queden sueltos en el inicio de mi repo? Sin estar dentro de la carpeta en la cual se crean

**Comment by MariaBloomfield** [comment]
Tengo este mismo error y no entiendo como solucionarlo :/

**Comment by meretamal** [comment]
Hola, estuve viendo algunos de sus repos y, como dijo @JupaOlivares, tienen su app en una subcarpeta dentro de su repositorio. Cuando ustedes hacen push a heroku, se termina subiendo el repo desde su raiz, razón por la cual luego Heroku no logra determinar qué tipo de proyecto están subiendo. Para esto tienen dos opciones:
1. Mover todos los contenidos de su app a una carpeta anterior, con tal de que quede  en la raiz del repo. Esto no lo hagan simplemente arrastrando los archivos, ya que hay algunos archivos "invisibles" (los que parten con .), sino que háganlo desde su terminal, parándose en la carpeta de su app y luego corriendo:
```bash
mv $(ls -A) ..
```
2. Subir a heroku el subdirectorio, en lugar de todo el repositorio:
```bash
git subtree push --prefix path/to/subdirectory heroku main
```
