### ISSUE TITLE
2c n19

### ISSUE THREAD

**Issue by santiago3c** [IIC2143/Syllabus#39]
Hola, en el test 2C n19, no entiendo por qué no se deberían de actualizar los datos del partido, si me podrían explicar

![image](https://github.com/IIC2143/Syllabus/assets/142272696/9f9d8c53-6e5b-475b-bd3b-177a8660a0bc)

**Comment by jtvaldivia** [comment]
Ese partido ya no existe 👀

**Comment by santiago3c** [comment]
Gracias!
