### ISSUE TITLE
Problema paso 8: creación del nuevo proyecto

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2143/Syllabus#4]
Hola!
Al correr el código descrito en la wiki en el terminal de Ubuntu me aparece este error.
¿Hay que hacer algo antes?, ¿correr la línea en otra terminal?
Intenté de todo y ya hice todos los pasos anteriores...
Gracias
![Captura de pantalla (108)](https://user-images.githubusercontent.com/89171048/184253423-d952d234-4f9c-48ac-b172-c1eb6017af00.png)

**Comment by meretamal** [comment]
Hola 😁 . La idea es que `<nuevo proyecto>` sea el nombre de tu proyecto. Por ejemplo:
```bash
rails new myapp --database=postgresql
```

**Comment by aurmeneta** [comment]
Hola Gonzalo,

`<nuevo proyecto>` lo tienes que reemplazar por el nombre del proyecto que vas a crear.
