### ISSUE TITLE
[Tarea] Experiencia aldeanos

### ISSUE THREAD

**Issue by Ajbarros1** [IIC2143/Syllabus#4]
Tengo una duda sobre la experiencia de los aldeanos. Cuando dicen (por ejemplo) que necesitan 40 de experiencia para subir al nivel 3, significa que necesitan 40 de experiencia en total o 40 de experiencia desde que subió al nivel 2?

**Comment by maggiemunoz** [comment]
Hola! Es 40 puntos de experiencia en total
