### ISSUE TITLE
Directorio de Tarea no abre en github

### ISSUE THREAD

**Issue by benjasaldias** [IIC2143/Syllabus#4]
Creé el directorio SoccerApi dentro del repositorio de github. Usando add, commit y push, el directorio aparece en github pero no puede abrirse. Se muestra de la siguiente manera:

![image](https://github.com/IIC2143/Syllabus/assets/141872703/ebed7473-7478-4764-968a-7acb43e7ff39)

¿Es eso normal? ¿Alguien sabe cómo solucionarlo?

--EDIT--
Leí que eso puede pasar con directorios vacíos, pero el mío fue creado con rails y tiene todos los contenidos dentro del directorio en local.

**Comment by damiangubbins** [comment]
CREO que esto ocurre porque rails genera SoccerApi con un .git adentro de esta, indicando que es un repo aparte. Eliminarlo deberia permitir subir los contenidos de SoccerApi al repo.

Desde adentro de SoccerApi ejecuta
$ rm -rf .git/

**Comment by benjasaldias** [comment]
> CREO que esto ocurre porque rails genera SoccerApi con un .git adentro de esta, indicando que es un repo aparte. Eliminarlo deberia permitir subir los contenidos de SoccerApi al repo.
> 
> Desde adentro del directorio /SoccerApi ejecuta $ rm -rf .git/

Eso era!! Muchas gracias :)
