### ISSUE TITLE
Duda respecto a los controllers en la Tarea 1

### ISSUE THREAD

**Issue by MaxAl100** [IIC2143/Syllabus#4]
Tengo una duda respecto al nombre de los controllers de la primera tarea; es necesario que sean controller "Person**s**" y controller "Vaccine**s**" o se pueden llamar controller Person y controller Vaccine?

**Comment by OrregoSilva** [comment]
Son los recomendados, puede ser cualquier nombre, pero, la idea es que sean en inglés, y describan sobre que son sus métodos
