### ISSUE TITLE
Github projects, invitar compañeros, manejo de acceso

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#40]
Hola! hice un proyecto desde mi perfil, como en la cápsula, y le fui metiendo algunas issues que hice en le repositorio de mi grupo.  Después traté de darle acceso a mis compañeros, pero no les llega la invitación a participar del proyecto. No se si esta es la forma en que hay que hacerlo para trabajar en el semestre o ¿hay que hacer otra cosa?

**Comment by gonzaloi21** [comment]
Tenemos el mismo problema

**Comment by JupaOlivares** [comment]
Si, estas en lo correcto debes añadir a tus compañeros, en otras issues se menciona como se hace, revisen correo no deseado o checkeen los nombres. 

Cualquier duda te recomiendo revisar esta documentación sobre el manejo de accesos a projects:
https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects

**Comment by simonmb12** [comment]
Hice lo mismo que sale en el link de documentación, y cuando reviso los colaboradores me aparecen ambos, pero ellos no ven alguna invitación o acceso al proyecto. Les debería llegar al mail? y en qué parte de ghitub lo pueden encontrar?

**Comment by isufan** [comment]
A nosotros tampoco nos llegó ningún aviso pero lo que hicimos fue acceder al perfil de la persona que lo creó y de ahí ir a sus projects personales. Si se les dio acceso a los demás integrantes, les debería aparecer aunque sea un project privado.

**Comment by 0wulf** [comment]
El project se debe crear como project de la organización para poderl linkearlo al repo del grupo? porque no tengo acceso a crear projects de la organizacion
