### ISSUE TITLE
Definiendo rutas.

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2143/Syllabus#40]
Estimados,

Ya una vez definido el controlador empecé a definir las rutas.

El problema es que al momento de ejecutar bin/rails routes en la consola me aparece lo siguiete:

![image](https://user-images.githubusercontent.com/69652093/228335165-a23ed21d-a7e2-478e-9319-de2cea2dd975.png)

Por qué sería el problema?

Saludos!

**Comment by Balison** [comment]
Hola, para ayudarte necesito más información, asi que podrias adjuntar un screenshot de tu archivo de rutas (config/routes.rb)?

**Comment by lorenzosilva** [comment]
![image](https://user-images.githubusercontent.com/69652093/228575857-728bf368-265d-4964-86a1-e73b8c972453.png)

![image](https://user-images.githubusercontent.com/69652093/228576162-f8c6b2f4-4d15-4551-ae57-f12c885c30ec.png)

**Comment by Balison** [comment]
Hola, lo primero las rutas no deben tener espacios extra. Por ejemplo reemplaza "/pacientes/: id" por "/pacientes/:id" y asi continuamente. Lo segundo, el error menciona que hay un error porque el controlador pacientes no existe. Segun el enunciado de la tarea, se debe crear el controlador Persons. Por favor, revisa atentamente el enunciado.
