### ISSUE TITLE
Undefined column, asociacion entre team y matches

### ISSUE THREAD

**Issue by M-Alva45** [IIC2143/Syllabus#40]
Hola! A la hora de usar Delete en teams, me estorba la asociación entre teams y matches ya que aparece el siguiente error
![imagen](https://github.com/IIC2143/Syllabus/assets/141866513/c5916582-833f-47a1-9b38-85a1f52d71c7)

Y así están las clases match y teams
![imagen](https://github.com/IIC2143/Syllabus/assets/141866513/fbbd1328-b544-4e31-8c2a-f6947efe243f)
![imagen](https://github.com/IIC2143/Syllabus/assets/141866513/dbded805-a016-46e7-8bf1-876d6d57d7a8)
Cual podría ser la causa de esto?

**Comment by jtvaldivia** [comment]
Puede que falle el dependent: :destroy del matches, ahi podrias ver una manera alternativa de hacer el delete sin ocupar esta propiedad.
