### ISSUE TITLE
[Tarea] - Require de otros archivos 

### ISSUE THREAD

**Issue by ferperezh** [IIC2143/Syllabus#40]
Hola les escribo porque tengo problemas cuando intento llamar una clase o metodo de otro archivo con el comando require, ya que me arroja el siguiente error:
![Captura de Pantalla 2022-03-24 a la(s) 11 31 23](https://user-images.githubusercontent.com/69528837/159939289-9df2d76b-b130-476f-ba46-12d785f793f0.png)
y este es mi codigo
![Captura de Pantalla 2022-03-24 a la(s) 11 31 16](https://user-images.githubusercontent.com/69528837/159939341-f3eed027-781e-4d7e-b349-90848d3d6cdb.png)

**Comment by maggiemunoz** [comment]
Hola! Prueba poniendo require 'leer', no require 'leer.rb'
