### ISSUE TITLE
Error con Token Inválido

### ISSUE THREAD

**Issue by FlorenciaOnetto** [IIC2143/Syllabus#41]
Hola! Al correr los test en Postman, me aparece el siguiente error: ActionController::InvalidAuthenticityToken (Can't verify CSRF token authenticity.):

Además en todos los test me aparece lo siguiente: JSONError: Unexpected token ‘<’ at 1:1 <!DOCTYPE html> ^.
Al parecer hay un problema con el token, pero no se como arreglarlo.

**Comment by OrregoSilva** [comment]
Lo más probable es que hayas generado el proyecto de la tarea en el modo default de rails, el cual es monolítico (El que usaran en el proyecto), para la tarea, al hacer `rails new`, es necesario agregar la opción de que sea una API (`rails new my_proyect --database=postgresql --api`), Esto lo menciono, ya que el < viene de que la API te respondió con HTML, no un JSON.
