### ISSUE TITLE
Problema al hacer push heroku main

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#41]
Estaba siguiendo los pasos de la cápsula del semestre pasado, y en la parte final de hacer "git push heroku main" me tira el siguiente error:
![Captura de Pantalla 2022-09-01 a la(s) 13 11 21](https://user-images.githubusercontent.com/89275951/187972942-7aafa024-ccd7-420a-a885-32ebaeb454c0.png)

Vi que había una issue con el mismo problema, pero no entendí cuál era la solución. En estos momentos estoy tratando de crear mi aplicación, por lo que aún no tiene nada adentro.

**Comment by nbarriav** [comment]
Hola, en un issue pasada se resolvió utilizando los comandos:
```
heroku buildpacks:add heroku/nodejs
heroku buildpacks:add heroku/ruby
```

**Comment by Juancagp** [comment]
> Hola, en un issue pasada se resolvió utilizando los comandos:
> 
> ```
> heroku buildpacks:add heroku/nodejs
> heroku buildpacks:add heroku/ruby
> ```

Intenté poniendo esto en el terminal pero como que empeoró, ahora sale esto
![fallo-2](https://user-images.githubusercontent.com/81201399/188278005-04253ee1-dfae-4173-b544-dd869063681a.jpg)

**Comment by Juancagp** [comment]
buscando en internet traté de desintalar el buildpackage de node.sj dado que por lo que vi en la foto anterior que subí la aplicación no soporta el buildpack
use lo siguiente:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/81201399/188278583-06c646b0-20f1-4666-9e4e-b2bb2e9192e7.png">
pero el mismo error de antes sigue apareciendo:(

**Comment by Juancagp** [comment]
logre con heroku buildpacks:remove heroku/nodejs evitar que saliera el gran error de antes, pero ahora intentando hacer git push heroku main aparece lo siguiente:
heroku buildpacks:remove heroku/nodejs
