### ISSUE TITLE
[TAREA] metodo top jugadores, instrucciones

### ISSUE THREAD

**Issue by BenjaLeyton** [IIC2143/Syllabus#42]
hola, en la tarea dice que tenemos que crear el metodo top_jugadores(criterio), pero en las instrucciones para crear el output aparece 
informacion_aldeanos
hacer_intercambios
top_jugadores_rubies
top_jugadores_experiencia
de tal manera que para correrla hay que tener como 2 metodos top_jugadores, y no solo una, de manera que sean llamados top_jugadores_rubies y top_jugadores_experiencia, yo cree un solo metodo de la forma de la tarea top_jugadores(criterio), y ahora me entro la duda de si deberia separarlos para poder correr las instrucciones como se debe, ya que si intentan correr el metodo como top_jugadores_rubies al revisar la tarea en vez de top_jugadores(rubies) nose si se me tome como malo, entonces la duda es, hago dos metodos o lo dejo todo en uno de manera que el ayudante tenga que escribir los criterios al momento de revisar.

**Comment by maggiemunoz** [comment]
Hola, la idea es crear un solo metodo. La idea es que si en instrucciones.txt sale top_jugadores_rubies, ejecutas el metodo con el parámetro "rubíes", y se sale top_jugadores_experiencia, ejecutan el mismo metodo pero con el parámetro "experiencia".
