### ISSUE TITLE
[Setup Windows] Problemas al instalar RVM

### ISSUE THREAD

**Issue by pedropalmav** [IIC2143/Syllabus#43]
Hola! Al ejecutar el segundo comando `gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB` me sale que el servidor me tira error. Qué puedo hacer?
![image](https://user-images.githubusercontent.com/80769811/160015767-8c950165-ec5e-4b25-88a7-78a76d345a09.png)

**Comment by benjaaguila** [comment]
Me pasa lo mismo!

**Comment by felipefuentesporras** [comment]
Hola!! Este problema ya se resolvió resolvió la issue #18 para que la revisen.
