### ISSUE TITLE
[Ubuntu Setup] Problemas con path ruby 2.6.6 al usar rvm

### ISSUE THREAD

**Issue by Dafnemami** [IIC2143/Syllabus#43]
Hola!, 

Cuando ocupo `ruby -v `no me reconoce ninguno, pero rvm ha efectivamente instalado la **versión 2.6.6** así que sospecho es un problema de que rvm no logró configurar bien el path. Encontré una posible solución a mi problema [acá](https://stackoverflow.com/questions/9018598/ruby-on-rails-rvm-path-issue) pero me complico al tener que acceder al .bashrc, que no entiendo qué es, al cual de hecho solo pude acceder usando `vi ~/.bashrc ` y no `source ~/.bashrc`  como indican en esa página, pues no sé donde agregar lo que me dicen.

Además, cuando me metí al bash por no cachar moví cosas y ahora cada vez que me meto denuevo me aparece lo de la imagen:

![modificacion involuntaria bash](https://user-images.githubusercontent.com/53848830/188028393-c0d24a90-5aca-43ba-ba7d-e2844629bbee.png)

Agradecería mucho su guía al respecto :) 

Saludos! 🚗

**Comment by meretamal** [comment]
Hola 😁, parece que cuando estabas editando el archivo, saliste del editor de alguna forma tal que no se guardó bien.

Como dice el mensaje, si ya terminaste de editar el archivo, puedes borrar **.bashrc.swp**. Para eso corre ls -la /home/dafne/.bashrc.swp para asegurarte de el archivo exista y luego corre `rm /home/dasfne/.bashrc.swp`.

Después podrías asegurarte de que estén los cambios que querías en **.bashrc**. Si no están, puedes usar nano o code para editarlo.

**Comment by Dafnemami** [comment]
Elimimé el swap y con `code . .bashrc` accedí al archivo usando vscode para editarlo. Luego, agregué en la línea en la línea 121 (ver foto) lo que me indica el link de stackoverflow que puse en la primera respuesta, [este](https://stackoverflow.com/questions/9018598/ruby-on-rails-rvm-path-issue). Reinstalé ruby 2.6 con rvn con `rvm reinstall 2.6`, pero aún no me reconoce el path (ver segunda foto). Algo que esté haciendo mal? 
![problema_con_path_luego_de_modificar_bash_ruby26](https://user-images.githubusercontent.com/53848830/188283419-456d4c8e-f916-4fe0-95c1-23d4b8c2a58d.png)
![Captura de pantalla de 2022-09-03 14-20-41](https://user-images.githubusercontent.com/53848830/188283451-b88e0974-0005-4de8-9419-78802122e48b.png)

**Comment by meretamal** [comment]
Qué pasa si corres `rvm -v`?

**Comment by Dafnemami** [comment]
Arroja lo siguiente: 

```
dafne@dafne-Lenovo-Legion-Y530-15ICH:~$ rvm -v
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

```

**Comment by Dafnemami** [comment]
Reinstalé ruby con `rvm install 2.6` y me lo detectó. No sé si ahora me funcionó porque el computador necesitaba reiniciarse o algo luego de modificar el bashrc, pero funcionó. gracias! :)
