### ISSUE TITLE
error test 3A

### ISSUE THREAD

**Issue by mayafzt** [IIC2143/Syllabus#43]
<img width="239" alt="image" src="https://github.com/IIC2143/Syllabus/assets/127949556/9345a17f-8524-4390-9c9b-b2d1a5a26365">
en el test 3A.24 la respuesta esperada en los assists es 3 - 1 - 2.
esta mal o yo entendi mal el enunciado?

**Comment by tomastrivino** [comment]
noentendi

**Comment by mayafzt** [comment]
se supone que deberia ordenar a los jugadores por la cantidad de assist de mayor a menor (3 - 2 - 1)

**Comment by tomastrivino** [comment]
<img width="881" alt="image" src="https://github.com/IIC2143/Syllabus/assets/98418205/4812c703-5392-4a82-b974-8a2b47811e4d">


ojo con esto
