### ISSUE TITLE
Problema creando la aplicación

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#44]
Hola, estaba siguiendo los pasos que vimos en clases para crear la primera aplicación en RoR, y me apareció este problema cuando traté de hacer "http://localhost:3000/articles":
![Captura de Pantalla 2022-09-02 a la(s) 10 44 07](https://user-images.githubusercontent.com/89275951/188174907-4c7a84d8-171a-445e-b7a8-0787f81df4c6.png)

**Comment by lfb1206** [comment]
Hola! ¿Intentaste arreglarlo corriendo el comando del paso 11 (en el caso de setup mac)? 

```
npm install --global yarn
rails webpacker:install
```

**Comment by simonmb12** [comment]
Si lo corrí. Cuando corro "http://localhost:3000" me aparece "You are on rails" así que supongo que tengo la instalación bien hecha. El problema es cuando hago el paso de la diapositiva 14 de RoR. Ahí, al cargar la página me tira el error que puse antes.
Acabo de volver a correr "rails webpacker:install" y este es el código que me aparece
![Captura de Pantalla 2022-09-02 a la(s) 15 20 03](https://user-images.githubusercontent.com/89275951/188222858-c175ab27-ad8d-4991-b073-e0b89c120b0a.png)

**Comment by lfb1206** [comment]
Esto es lo que encontre sobre el error que te aparece [https://stackoverflow.com/questions/54113179/rails-webpackermanifestmissingentryerror-in-homeindex#:~:text=The%20Webpacker%3A%3AManifest%3A%3A,as%20what's%20in%20your%20yarn.](url).
