### ISSUE TITLE
problema al escribir output.txt

### ISSUE THREAD

**Issue by jo00** [IIC2143/Syllabus#44]
Hola al intentar escribir en el archivo output.txt me aparece el siguiente mensaje:

ain.rb:154:in `initialize': Permission denied @ rb_sysopen - output.txt (Errno::EACCES) intente buscar que es pero no he logrado solucionarlo :(

**Comment by maggiemunoz** [comment]
Hola! Se que es un poco tarde, si aun no logras solucionarlo puedes mandarme el codigo que usas para escribir el archivo?

**Comment by jo00** [comment]
Holi , era algo como:
———————————————
output = ARGV[2]

File.write(output, “blablablabla”) 

———————————————

Aunque igual probe otras sintaxis y tampoco funcionaba:( segun yo ds como un tema de ubuntu? Como que no tienenacceso al archivo, pero es raro porque lo abri con explorer.exe . y si estaba ahi:(
