### ISSUE TITLE
Error al hacer git add

### ISSUE THREAD

**Issue by benjazuloaga** [IIC2143/Syllabus#44]
Hola tengo un error al hacer git add. No me esta dejando y ni si quiera tira error, sencillamente no funciona.

![image](https://user-images.githubusercontent.com/110860328/228597721-08dde479-1229-49ca-95df-8301b1bd6b5b.png)

**Comment by manearaya** [comment]
Hola!

Trata de usar:

git add -A 
(debería forzar que se agreguen todos los archivos)

git add vaccine/*
(debería añadir todos los archivos dentro de la carpeta)

Avísame como te va!

**Comment by benjazuloaga** [comment]
Ahí lo pude solucionar. Muchas gracias!!


De: Magdalena Araya Mertz ***@***.***>
Enviado el: miércoles, 29 de marzo de 2023 15:31
Para: IIC2143/Syllabus ***@***.***>
CC: BENJAMÍN ANDRÉS ZULOAGA MARÍN ***@***.***>; Author ***@***.***>
Asunto: Re: [IIC2143/Syllabus] Error al hacer git add (Issue #44)


Hola!

Trata de usar:

git add -A
(debería forzar que se agreguen todos los archivos)

git add vaccine/*
(debería añadir todos los archivos dentro de la carpeta)

Avísame como te va!
