### ISSUE TITLE
Vinculación del repositorio del grupo con el github project

### ISSUE THREAD

**Issue by 0wulf** [IIC2143/Syllabus#45]
Hola buenas, en mi grupo estamos teniendo problemas con la vinculación del repositorio con los project. Leí las issues https://github.com/IIC2143/Syllabus/issues/40 y https://github.com/IIC2143/Syllabus/issues/36 pero con las indicaciones no he podido lograrlo. 
Al inigresar a la pestaña projects del repo me aparece un botón tal como en la imagen
![image](https://user-images.githubusercontent.com/101217121/188181118-02320257-001b-45c8-bdd1-4e2d06980a7d.png)
y redirige 
![image](https://user-images.githubusercontent.com/101217121/188181218-713767b9-4e22-46c1-b43e-8d89d42e4230.png)
de modo que no tengo opcion para crear el project.
Por otro lado, al intentar convertir un draft de issue en una issue, no me aparece el repo del grupo pero si otros creados por mi.
Además, al dirigirme a los settings de un project creado por mi para cambiar mi configuración de acceso, no me aparece un baselevel para las cuentas de la organizacion. 
![image](https://user-images.githubusercontent.com/101217121/188183498-e7210cc6-4af7-4bb6-af58-ccc31b8be1c3.png)
por lo que definitivamente no tengo como acceder al repo desde un project. Existirá un problema de acceso? entiendo que acá deberia aparecerme la opcion de ver mis organizaciones y no puedo
![image](https://user-images.githubusercontent.com/101217121/188187723-c8e9abef-0041-4663-b7de-46dbf4895bee.png)
pero efectivamente estoy en la organizacion 
![image](https://user-images.githubusercontent.com/101217121/188188576-d841a056-8ba2-4ccc-9150-1dcf889c94c9.png)
quizás falta un privilegio a outside collaborator o no sé, pero como mencionaba al principio, no puedo crear/linkear un project a tal repo.

**Comment by Cinaraa** [comment]
tengo el mismo problema!!
