### ISSUE TITLE
Duda proyecto que creamos al hacer el setup

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#46]
En el paso 7 de la guía de setup, se crea un proyecto "rails new <nombre proyecto> --database=postgresql". Tenemos que subir esta carpeta que acabamos de crear a nuestro repositorio del grupo? y con este "nombre proyecto" se hace la aplicación en heroku?

**Comment by OrregoSilva** [comment]
Hola!
No es necesariamente ese, en la guía esta incluido ese paso para que se aseguren que funciono la instalación. Para el proyecto basta que 1 integrante lo cree colocándole un nombre respectivo (sean originales acá) y que lo suba a GitHub para que los demás puedan trabajar sobre el mismo. Luego el mismo proyecto deberán linkearlo a Heroku para los deploy.
