### ISSUE TITLE
Error al subir el proyecto al repositorio

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#47]
Hola, estoy tratando de subir el proyecto (app), que se creo en el paso 7 del setup, al repositorio de mi grupo. Pero cuando hago git add . me aparece el siguiente error:
![Captura de Pantalla 2022-09-02 a la(s) 18 40 04](https://user-images.githubusercontent.com/89275951/188244048-7fb450a0-0cc5-4911-af9e-477a0cf38958.png)

**Comment by lfb1206** [comment]
Hola! Podria ser por varias razones, aqui te dejo un link que entregta diversas soluciones al problema. Mucha suerte!

[https://stackoverflow.com/questions/56799562/git-submodule-add-error-does-not-have-a-commit-checked-out](url)

**Comment by simonmb12** [comment]
Hola! estaba viendo este link, pero me aparece que la solución es borrar la carpeta .git
En mi proyecto no tengo esa carpeta, por lo que no me debería estar tirando este problema.

**Comment by lfb1206** [comment]
En el caso de que estes usando mac esa carpeta, en mi caso, se puede visualizar en finder utilizando `Shift + Comando + .`. En el caso de windows puedes visualizarlo de la siguiente forma [https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-97fbc472-c603-9d90-91d0-1166d1d9f4b5](url).

**Comment by simonmb12** [comment]
grandeeee jajajaja eso era. ahí la pude encontrar, y al borrarla me dejó subirla al repositorio.
Gracias!!!
