### ISSUE TITLE
[Proyecto] Duda sobre que hacer despues de setear ubuntu

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2143/Syllabus#48]
¡Hola!, complete ya todos los pasos del setup de ubuntu pero ahora tengo la pregunta de como continuar con Heroku, ¿tengo que meter todos los archivos de la carpeta del proyecto de rails que cree a nuestro repositorio o algo asi?, ¿Y en ese caso como se haria eso? Por que manualmente me dice que no se puede por que son muchos archivos.

¡Muchas gracias!

**Comment by JupaOlivares** [comment]
Una vez seteado todo y creado el repo tienes que hacer el git push a heroku, no se a que te refieres con:

>   manualmente me dice que no se puede por que son muchos archivos.

Pero una vez creado la aplicación deberias poder hacer `git add .` o algo por estilo sin ningun problema y despues commitear y pushear a heroku.

**Comment by tzehnder** [comment]
Hola! tengo una duda relacionada con las carpetas que se crean al crear el servidor con el comando
`rails new <nombre proyecto> --database=postgresql`
Esta carpeta que se crea, llamada nombre proyecto debe ser subida a la repo que tenemos en github? no se me ocurre otra manera de trabajar como equipo en ella, a lo menos que heroku tenga esa caracteristica.
