### ISSUE TITLE
Tarea 1: Destroy.all

### ISSUE THREAD

**Issue by elisahonorato** [IIC2143/Syllabus#48]
Hola, tengo una pregunta. Al destruir todas las personas de la base de datos, también destruyo sus id? Pregunto esto ya que al ejecutar en postman las ultimas requests, no me resulta encontrar una vacuna con id=65, que es el personid que corresponde a la persona creada. Muchas gracias!

**Comment by jpsandoval** [comment]
los test de la bateria de test, deben ejecutarse en secuencia, un test borra las personas, otro test las agrega, y luego otro test agrega vacunas a esas personas... tienes que ejecutar los test en secuencia....

**Comment by elisahonorato** [comment]
Yaa si, lo estaba haciendo mal. Pero igual me queda una duda conceptual... en general los id siempre quedan en la base de datos, a pesar de que se borre el objeto, cierto?
