### ISSUE TITLE
Duda con la interpretación de match.state = false y result ="--"

### ISSUE THREAD

**Issue by diegoftpxd** [IIC2143/Syllabus#49]
Estoy realizando la función de debe eliminar el peor match, por lo que tengo que llegar a contar los partidos ganados, partidos empatados y partidos jugados por cada equipo.

Tengo la duda de que representa el partido state: False y los result "--". Mi duda es si estos partidos deben considerarse en el conteo de partidos jugados o realmente se considera que no han sucedido.

Además no sé si estos partidos son empate o simplemente no se consideran para nada en el conteo de puntos.

**Comment by jtvaldivia** [comment]
Si cuentan como partidos en el caso de empate.

**Comment by rosarioguerreror** [comment]
Hola! Entonces state: False deberia contar como un partido jugado y sumando un punto a ambos equipos? Si lo hago de esta forma me quedan algunos test en la seccion 3B donde me queda la misma cantidad de puntos y partidos para dos equipos. Que se hace en ese caso?  
gracias

**Comment by jtvaldivia** [comment]
no, cuenta como un partido en caso de empate(si hay 2 equipos empatados se eliminaria el con mas partidos contando los False) pero para el puntaje se calcula solo con los jugados.

**Comment by martina-abello** [comment]
Disculpa, no me quedó claro. ¿Los casos que son result: "--" cuentan como empate o no?

**Comment by jtvaldivia** [comment]
No, cuentan solo para calcular el desempate.

**Comment by MatiLaB** [comment]
O sea ¿tendríamos que, por ejemplo, además de contar los puntos y los partidos de cada equipo, tendríamos que tener un contador distinto para saber cuanto partidos en state:false tiene y así poder hacer el desempate? ¿O se refiere a que tenemos que contarlo como cualquier equipo nomás, pero que no aporta puntos?
