### ISSUE TITLE
[Proyecto] Error "The page you were looking for doesn't exist" cuando ya se hizo el deploy.

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2143/Syllabus#49]
Hola, logre hacer deploy a la aplicacion pero cuando intento abrir la app en Heroku me aparece este error, ¿alguna manera de arreglarlo?

![Problema heroku](https://user-images.githubusercontent.com/101432060/188296462-f27626d7-d02a-47cb-8be1-db972c3d5aa0.png)

**Comment by meretamal** [comment]
Hola 😁 , viendo tu app, parece que aún no haz agregado ni una ruta válida. Agrega una vista y su ruta correspondiente y prueba haciendo el _deploy_ de nuevo.
