### ISSUE TITLE
[Tarea] - Valores de la reputacion

### ISSUE THREAD

**Issue by ElMat1** [IIC2143/Syllabus#5]
Hola! La parte 4 del enunciado, dice que la reputacion del jugador toma los valores desde -0.5 a 0.5, pero la parte 5.2 dice que es de -1 a 1. ¿Cuales son los valores correctos?

**Comment by maggiemunoz** [comment]
Hola! Los valores correctos son desde -0.5 a 0.5, voy a corregirlo en el enunciado. Gracias por avisar!
