### ISSUE TITLE
Problema parte 8 del setup: can't find gem railties

### ISSUE THREAD

**Issue by gitlobo** [IIC2143/Syllabus#5]
Hola! cuando intento crear un proyecto me tira este error:
![image](https://user-images.githubusercontent.com/89175825/184258006-9cd19f22-4544-4b83-811b-2cffad5a0c00.png)

**Comment by meretamal** [comment]
Hola 😁 , `railties` es una gema que contiene toda la línea de comandos de rails y debería haberse instalado junto a rails.

Para ir solucionándolo de a poco, podrías correr `rails -v` y mandar qué te sale?

**Comment by gitlobo** [comment]
Esto me sale al correr rails -v
![image](https://user-images.githubusercontent.com/89175825/184411868-a37220ba-8637-4756-9d26-8852e47a1082.png)

**Comment by gitlobo** [comment]
Eso era! corri el gem install rails otra vez y ahora si! gracias!!
