### ISSUE TITLE
No me funciona crear la base de datos para la tarea

### ISSUE THREAD

**Issue by martina-abello** [IIC2143/Syllabus#5]
Ya creé los tres modelos que se piden en el enunciado, pero al correr _rails db:migrate_ en la consola me aparece lo siguiente: 
_rails aborted!
ActiveRecord::NoDatabaseError: We could not find your database: SoccerApi_development. Which can be found in the database configuration file located at config/database.yml._

No sé si es porque son más de un modelos o alguna otra razón; al hacerlo con Student durante la clase no me apareció este problema.

¿Qué procede?

Gracias de antemano.

**Comment by 00nrs** [comment]
Tengo el mismo error

**Comment by noamsito** [comment]
Hola, puede que eso esté ocurriendo porque no creaste una base de datos para el proyecto en el que estás trabajando, es decir, no ejecutaste el comando de "rails db:create", ya que esto lo tienes que hacer para cada proyecto que creas. El otro motivo que puede ser es que simplemente no haz encendido el postgresql. 

En caso de que no te funcione solamente corriendo el comando de "rails db:create" te dejo el siguiente link que te puede ser de ayuda: 
https://stackoverflow.com/questions/74497573/cant-create-a-database-using-postgresql-with-rails

**Comment by martina-abello** [comment]
_rails db:create_ me funcionó, muchas gracias. No había visto ese comando en las diapos.
(Ahora me sale un error distinto ;u;)

**Comment by noamsito** [comment]
qué error te sale?

**Comment by martina-abello** [comment]
Ya hice otra issue al respecto, pero es:
_StandardError: An error has occurred, this and all later migrations canceled:_

_PG::UndefinedTable: ERROR: relation "teamAs" does not exist_

**Comment by 00nrs** [comment]
me ocurre lo mismo x2

**Comment by anticarasosman** [comment]
a mi tambien me sale el mismo error

**Comment by martina-abello** [comment]
me funcionó reemplazar _foreign_key: true_ con _foreign_key: {to_table: :teams}_ en los archivos de /db/migrate

**Comment by anticarasosman** [comment]
> me funcionó reemplazar _foreign_key: true_ con _foreign_key: {to_table: :teams}_ en los archivos de /db/migrate

A mi tambien me funciona, muchas gracias
