### ISSUE TITLE
Errores en 'Controller Vaccines', metodo 'update'

### ISSUE THREAD

**Issue by Dyotson** [IIC2143/Syllabus#5]
Hola, luego de revisar varias veces el metodo 'update' y revisar los tests de postman, pude concluir que hubo una falla en la descripcion del metodo, debido a que dice:

_update – Método que, dado el id de una persona, muestra en formato JSON las vacunas de la persona
con ID igual a params[:person id]._

cuando deberia ser, por lo que induje:

_update – Metodo que, **dado el id de una vacuna (params[:id]) y el id de una persona (params[:person_id]), actualiza la información de la vacuna que se obtiene. Este metodo muestra en formato JSON la vacuna actualizada**_

Ojala lo puedan revisar, saludos.

**Comment by OrregoSilva** [comment]
Hola, efectivamente esta mal, lo estoy arreglando, gracias por avisar!
