### ISSUE TITLE
Discordancia entre Enunciado y ejemplos para "sinopsis" y "arguments"

### ISSUE THREAD

**Issue by VANCOUVERMATU11** [IIC2143/Syllabus#5]
En el enunciado (página 1) cuando describe los modelos dice que Movies tiene el atributo "sinopsis". Luego en el resto de la tarea se ocupa la palabra "argument". ¿Con cual nos debemos quedar para efecto de que los test públicos funcionen?

**Comment by OrregoSilva** [comment]
Hola! Efectivamente, hay un error, el atributo fue modificado a sinopsis y el enunciado ha sido actualizado
