### ISSUE TITLE
Duda con response de ruta: POST /matches

### ISSUE THREAD

**Issue by NachoRinda** [IIC2143/Syllabus#51]
En los test cases de la parte 2 me sale este resultado esperado
Expected:
{
    "id": null,
    "teamA": 60,
    "teamB": 61,
    "state": false,
    "result": "--"
}
En cambio, mi response es
Response:
{
    "id": 63,
    "teamA_id": 60,
    "teamB_id": 61,
    "state": false,
    "result": "--"
}
Mi duda es como cambiar de nombre las columnas para que coincidan los tests. Ya intenté estas dos soluciones en la clase Match: 
 alias_attribute :teamA, :teamA_id
 alias_attribute :teamB, :teamB_id
 alias_attribute :teamA_id, :teamA
 alias_attribute :teamB_id, :teamB]
¿Qué más puedo intentar o hacer para que coincidan?

**Comment by NachoRinda** [comment]
Sip, llegué a lo mismo desde otro post en StackOverflow. Igualmente muchas gracias. Para los que aún necesiten editar eso lo importante es sobreescribir el método as_json() del modelo :D.

**Comment by fvm2** [comment]
Cómo arreglaste para que el id del response sea null?

**Comment by NachoRinda** [comment]
El id no se evalúa en los test cases ya que para cada base de datos diferente este será un número distinto dependiendo de cuantas instancias del modelo se hayan guardado antes, entonces es normal que aparezca null y no debería importar al momento de testear.
