### ISSUE TITLE
[Heroku][webpacker] Error al hacer deploy de la app a heroku

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2143/Syllabus#51]
Hola, al momento de subir la app a heroku obtengo el siguiente error:
![image](https://user-images.githubusercontent.com/62031857/188332718-db5b95d5-1ce1-4f6b-b4c3-71e9d1309e5b.png)

He intentado diversas cosas pero ninguna me ha resultado. Específicamente he intentado agregando los buildpacks de nodejs y ruby a heroku y también probé modificando el archivo package.json.

**Comment by andrescf** [comment]
Me pasa lo mismo, probe todas las respuestas de las otras issues y ninguna funciono.

**Comment by nicogrecod18** [comment]
Lo pude solucionar. Lo que hice fue cambiar mi version de node de v16 a v14 y volver a instalar webpack.

**Comment by andrescf** [comment]
Gracias! Eso tambien me funciono :D

**Comment by Cinaraa** [comment]
mismo problema aqui, no me funciona aun
