### ISSUE TITLE
[Heroku] Error al pushear

### ISSUE THREAD

**Issue by claudiosalvador** [IIC2143/Syllabus#52]
Hola! Al tratar de hacer el deploy a heroku nos sale el siguiente error. Ya tratamos de correr bundle update según lo que vimos en una issue de stackoverflow pero no funcionó. A parte de eso no hemos encontrado nada que nos pueda ayudar.

![image](https://user-images.githubusercontent.com/48532736/188339782-d7c013c8-14f7-47b9-802c-d4bbf5ada3a8.png)

**Comment by josetomasacuna** [comment]
Tengo el mismo problema y no he podido solucionarlo

**Comment by claudiosalvador** [comment]
> Tengo el mismo problema, pudiste solucionarlo?

todavia no

**Comment by claudiosalvador** [comment]
Este link me ayudó a resolverlo! Espero les sirva @amanda1415 @josetomasacuna 

https://stackoverflow.com/questions/72252845/heroku-push-rejected-because-gems-fail-to-install
