### ISSUE TITLE
Error al correr el servidor (PG::ConnectionBad FATAL: role "root" does not exist)

### ISSUE THREAD

**Issue by benitopalaciosm** [IIC2143/Syllabus#52]
Hola, al correr http://localhost:3000/ me aparece este error y no sé de donde proviene.

![image](https://user-images.githubusercontent.com/89422962/160901412-5c840bb6-0efb-4fc2-8ef0-46cc5999689c.png)

**Comment by jadawabe** [comment]
Hola! Creaste el archivo .env con el nombre y contraseña de tu base de datos? Cambiaste el archivo config/database.yml ?

**Comment by benitopalaciosm** [comment]
Hola! Sí, cree el archivo .env y también cambié el archivo config/database.yml
Voy a dejar adjuntada las fotos de cómo los dejé. Mi proyecto se llama "software".

![Software](https://user-images.githubusercontent.com/89422962/161077003-f02e57e6-b480-4aca-b075-42d76f5f78cc.png)
![image](https://user-images.githubusercontent.com/89422962/161077070-aedbd61a-9632-42f2-8056-32ea1951827f.png)
