### ISSUE TITLE
Carpeta proyecto path

### ISSUE THREAD

**Issue by agustindesolminihac** [IIC2143/Syllabus#53]
Hola, hice la instalación de ubuntu y rails y me funcionó y me apareció Yay! You’re on Rails! Pero ahora cuando quiero buscar la carpeta de proyecto que cree, para agregarla a la carpeta del repositorio de mi grupo, no la encuentro en mi computador. Sí la puedo abrir desde vscode y me muestra el path de la foto adjunta. Pero luego, cuando la intento buscar en Red en mi computador no me sale nada.
![Captura de pantalla (47)](https://user-images.githubusercontent.com/49526698/188502694-5725666e-6f5e-4df7-8ce3-864acd8d1086.png)

**Comment by aurmeneta** [comment]
La carpeta de tu proyecto está dentro de ubuntu. Lo más sencillo es copiar los contenidos por el terminal. Esto lo puedes hacer con el siguiente comando:

`cp -r ./capeta_1 ./carpeta_2`

Esto copiará todos los archivos de `carpeta_1` a `carpeta_2`.

**Comment by gecoli** [comment]
¿En cuál terminal se puede poner ese comando? He estado intentando de muchas formas y no puedo copiarlo.

**Comment by kunafuego** [comment]
Hola! Otra opción es hacer el clone del repositorio dentro de la misma carpeta en tu terminal de ubuntu, así vas a poder abrir la consola y tener tu repo ahí mismo siempre.

La otra opción es crear la app directamente dentro de la carpeta local de tu repo, para que así no tengas que mover nada y solo debas hacer el push
