### ISSUE TITLE
Webpacker::Manifest::MissingEntryError in Articles#index

### ISSUE THREAD

**Issue by NatC18** [IIC2143/Syllabus#54]
La semana pasada estaba realizando el ejercicio en clases en donde se crea una vista de artículos, sin embargo al intentar verla en el directorio respectivo esta lanza este error. Antes otros tenían el mismo error, pero las soluciones que le daban no me funcionaron y buscando distintas cosas en stackoverflow tampoco me funcionan.

![Screen Shot 2022-09-05 at 22 50 17](https://user-images.githubusercontent.com/71082128/188530106-719348a4-6225-4fd2-85fb-983a1943f920.png)

![Screen Shot 2022-09-05 at 22 34 34](https://user-images.githubusercontent.com/71082128/188528546-5ea3a655-62ff-46d8-97ac-9807db61170a.png)

Ojalá haya alguna forma de solucionarlo ya que llevo mucho rato intentándolo! Gracias :)

**Comment by camibennett** [comment]
Hola! Con mi grupo estamos intentando hacer la aplicación web del sprint 0 y nos sale el mismo error. Nos funcionó bien hasta "Yay, you'e on rails!", pero al seguir los pasos de la ayudantía para que salga "Hola mundo" en la página nos sale el error mencionado (Webpacker::Manifest::MissingEntryError in Pages#home). También intentamos todo lo que sale en StackOverflow del error e intentamos hacerlo desde otro computador pero nada logra solucionarlo.
Ojalá nos puedan ayudar para seguir avanzando con el proyecto.
Gracias de antemano :)

**Comment by meretamal** [comment]
Hola, podrían revisar [esta respuesta](https://github.com/IIC2143/Syllabus/issues/28#issuecomment-1236231903) y ver si les sirve?

**Comment by camibennett** [comment]
Con eso logramos solucionarlo, muchas gracias!
