### ISSUE TITLE
[Windows] Error al correr paso 8

### ISSUE THREAD

**Issue by spplaza** [IIC2143/Syllabus#56]
Hola,
he tratado de hacer el setup desde la primera semana, también fui a la ayudantía de setup, pero hasta ahora no me funciona, los ayudantes que vieron mi consola tampoco me lo pudieron solucionar por un tema de tiempo. Luego de intentar varias, el primer error que me tira al realizar el setup es el de la imagen y tiene que ver con node, pero node ya lo tengo instalado en su versión más actual. Lo anterior ocurre al correr "rails new <nombre proyecto> --database=postgresql" con el nombre de mi proyecto. No entiendo si sera ese el error principal, pero cuando llego al paso final "rails s" no me tira errores pero en localhost 3000 no me aparece nada. Hasta ahora no me ha servido lo que he encontrado en internet. Quedo atenta.

<img width="960" alt="error node" src="https://user-images.githubusercontent.com/53846022/161171760-077f5a25-e08e-47e8-98c2-e7b5529ac9c6.png">

**Comment by acastill20** [comment]
Hola! Intenta correr 
``nvm use 12``
Y luego repite el paso 11. Te deberia decir de nuevo que actualices yarn pero esta vez debiera funcionar correctamente.

**Comment by spplaza** [comment]
No me funcionó :c Voy a desistalar todo y tratar de nuevo.

**Comment by spplaza** [comment]
Hay algún anti setup para desinstalar todo? ya llevo días tratando de resolver el setup y nada.

**Comment by spplaza** [comment]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/53846022/161865670-3541a19f-f750-4eb6-8542-a01c99e3e8b0.png">
Este es el único warning que me tira cuando corro yarn install --check-files
