### ISSUE TITLE
Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by vicente999** [IIC2143/Syllabus#56]
Holaaa quiero clonar la repo que de dieron en ubuntu>home>usuario y desde ahi correr el rails new . --database=postgresql pero me tira Permission Denied. Como puedo solucionar esto?
Gracias!

**Comment by kunafuego** [comment]
Hola! Puedes adjuntar foto del error?

**Comment by vicente999** [comment]
Ya lo tengo arregladoo
Gracias igual!
