### ISSUE TITLE
[Proyecto] [Yarn] The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by gitlobo** [IIC2143/Syllabus#57]
Holaa, con mi grupo logramos corre rails s en la mañana, y subitamente dejo de funcionar en la tarde, nos arroja el siguiente problema:

![duda rails](https://user-images.githubusercontent.com/89175825/188713238-c6267333-e262-4af9-b6d4-c73ea5e2b840.jpeg)

**Comment by aurmeneta** [comment]
Estas ocupando la versión incorrecta de node. Ejecuta los siguientes comandos.

1. `nvm install 14`
2. `nvm use 14`

Si quieres dejar esta versión como la por defecto en tu computador puedes ejecutar lo siguiente. Pero ojo, si ocupas nodejs en otros proyectos, ésta también será la por defecto para ellos.
`nvm alias default 14`
