### ISSUE TITLE
Consulta slides clase

### ISSUE THREAD

**Issue by diegocostares** [IIC2143/Syllabus#57]
Hola, ¿es posible que se suban los PPTs de ambas secciones al repositorio? Pues nos ayudaría bastante para el estudio tener el material de la otra sección disponible.

**Comment by jnavon** [comment]
He compartido una carpeta en drive con todas mis clases:
https://drive.google.com/drive/folders/1SXUd2nx6ExUJBqIv-MzBDa8lkEEo6DR_?usp=sharing

**Comment by jpsandoval** [comment]
De igual forma, acabo de crear una carpeta drive con mis slides: 
https://drive.google.com/drive/folders/1zKNdt5ymYGnN7vQWxZ0WZaZlytJ-THGM?usp=sharing
Espero que les sirve, salu2,
