### ISSUE TITLE
Error al hacer git push heroku main

### ISSUE THREAD

**Issue by Sebah01a** [IIC2143/Syllabus#58]
Me salio este error que no se como arreglar. Ya tengo los archivos de la app de ruby en la repo y estoy tratando de conectarlos con heroku

![image](https://user-images.githubusercontent.com/89041986/188782352-29e84eb5-1feb-4bc3-85c5-4cf75a40103b.png)

**Comment by kunafuego** [comment]
Hola! La app cuando la corres local no te levanta ningún error?

**Comment by Moisnt** [comment]
hola, yo tengo el mismo error y de manera local me corre bien
