### ISSUE TITLE
Error al borrar node_modules

### ISSUE THREAD

**Issue by benja20029** [IIC2143/Syllabus#59]
Buenas, por diversos motivos, hace poco tuve que borrar el repositorio del proyecto del pc (o esa era la idea), sin embargo, se me hizo imposible borrar la carpeta node_modules, ya probe con rm -rf, sudo rm -rf, rmdir y ninguno funciono. 
Adjunto error: 
![image](https://user-images.githubusercontent.com/81534737/188788386-8994f5e6-7bcd-4cc2-9525-83c34a14023f.png)

Cabe destacar que en un principio este archivo estaba guardado en un backup de onedrive (sincronizacion automatica) que generaba error, ya probe desinstalando onedrive pero sigo teniendo el mismo error.

**Comment by aurmeneta** [comment]
Intenta borrarla directamente desde el explorer de windows.

**Comment by benja20029** [comment]
Si lo intente también pero no me retornaba nada
