### ISSUE TITLE
[Tarea] Confusión sobre descuentos de cada tipo de Aldeano

### ISSUE THREAD

**Issue by JorgeGuzz** [IIC2143/Syllabus#6]
En una parte del enunciado dice que los Bibliotecarios tienen 50% de descuento y los Herreros 35%

![imagen](https://user-images.githubusercontent.com/80768853/159042403-84e7673c-5a55-4c4e-a77f-25771336dba2.png)

Pero en esta otra los valores salen al revés

![imagen](https://user-images.githubusercontent.com/80768853/159042542-ea44931c-bc9e-491b-bb4c-f0a02974ea04.png)

¿Cuál consideramos como correcta?

**Comment by kalarconvl** [comment]
Tengo la misma duda

**Comment by maggiemunoz** [comment]
Hola! Disculpen, los valores correctos son los mencionados en el punto 5.1, es decir, el bibliotecario tiene 35% y el herrero 50%. Voy a corregirlo en el enunciado, gracias por avisar!
