### ISSUE TITLE
Problema parte 12 del setup: database does not exist

### ISSUE THREAD

**Issue by gitlobo** [IIC2143/Syllabus#6]
Hola! cuando ejecuto rails s y abro el link del servidor, obtengo este error:
![image](https://user-images.githubusercontent.com/89175825/184435129-51c82fd2-92aa-4d47-a8e7-7586da0f1dc4.png)

**Comment by OrregoSilva** [comment]
Como dice el error, aun no creas la Base de Datos de tu aplicacion, para esto tienes que ejecutar `rails db:create`, tal como se indica en la guia.

**Comment by gitlobo** [comment]
ahora sii!!! no se porqué no se me habia creado antes con el comando, muchas gracias!
