### ISSUE TITLE
Problema instalación windows

### ISSUE THREAD

**Issue by aruiz19** [IIC2143/Syllabus#6]
Hola, no he podido instalar el programa porque me aparece el siguiente error:
"gpg: keyserver receive failed: Server indicated a failure" cada vez que ejecuto 
"gpg --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB".

**Comment by OrregoSilva** [comment]
Esta duda tiene que realizarse en el repositorio de Setup, aun así [acá](https://rvm.io/rvm/security) salen más opciones
