### ISSUE TITLE
[Tarea] Consulta tarea bonus si se falta a la I1

### ISSUE THREAD

**Issue by TTrincado** [IIC2143/Syllabus#60]
Debido a ciertos motivos no podré rendir la I1 y tendré que rendir el examen recuperativo. Quería saber si podía hacer la tarea bonus de igual manera y sumar las posibles décimas para la nota que reemplazará la de la I1.

**Comment by meretamal** [comment]
Hola, siempre que esté debidamente justificado, contarán para la evaluación recuperativa.
