### ISSUE TITLE
[Windows] Pérdida de contraseña de Ubuntu

### ISSUE THREAD

**Issue by aplaza2** [IIC2143/Syllabus#60]
Hola, una duda. ¿Si se perdiera la contraseña para acceder a Ubuntu, hay alguna manera de recuperarla o en ese caso solo se desinstala todo y se vuelve a instalar?

**Comment by OrregoSilva** [comment]
Hola!
Buscando un poco encontré esta [pagina](https://itsfoss.com/reset-linux-password-wsl/) que tiene un paso a paso de que hacer, si no te funciona una solución fácil (aunque un poco bruta) es la que propones, de desinstalar Ubuntu y partir de 0, lo he hecho un par de veces por otros motivos y no es algo tan terrible, solo trata de ver si tienes algún archivo importante en el root de Ubuntu eso si, porque sino se eliminara también.
