### ISSUE TITLE
Problema con branches Git

### ISSUE THREAD

**Issue by valentin-diaz** [IIC2143/Syllabus#61]
Hola, estaba intentando subir el proyecto al repositorio del grupo, pero me traspapelé y puse `git push -u origin master` en vez de `git push -u origin main`, por lo que creé una rama master completamente nueva, y por algún motivo no me deja hacer Pull Request ni hacer push a main. He investigado e intenté varias cosas distintas que no me funcionaron, por lo que tengo miedo de empeorar la situación aún más. Ayuda por favor 😭 

------------
EDIT: Si intento hacer push a main, me aparece este error
![image](https://user-images.githubusercontent.com/80912149/161408505-65a1986e-9d02-43d6-8f21-570af897b16c.png)

**Comment by OrregoSilva** [comment]
Hola!
Algo que puede que te ayude es tratar de _mergear_ por consola utilizando [`git merge`](https://git-scm.com/docs/git-merge), también revisa en que rama estas parado actualmente en tu computador con `git branch`
