### ISSUE TITLE
Webpacker configuration file not found / Rails aborted

### ISSUE THREAD

**Issue by MartinRosenfeld11** [IIC2143/Syllabus#61]
Seguí los pasos de git en mac, pero me sigue alegando que no existe el archivo "webpacker.yml", lo que es verdad, al abrir vscode no me sale ese archivo. Pero no importa cuantas veces use 

"npm install --global yarn
rails webpacker:install"

, no se me instala.

<img width="566" alt="Captura de Pantalla 2022-09-07 a la(s) 17 26 35" src="https://user-images.githubusercontent.com/101756449/188970752-7b98bf27-b63e-488e-81fb-a4f530cd9e1c.png">

**Comment by aurmeneta** [comment]
¿Qué te aparece al ejecutar `rails webpacker:install`?

**Comment by MartinRosenfeld11** [comment]
Eso hice! Tampoco funcionó! Me sale el mismo error

**Comment by MartinRosenfeld11** [comment]
Espera encontré un error anterior! Me sale :

<img width="565" alt="Captura de Pantalla 2022-09-07 a la(s) 17 55 05" src="https://user-images.githubusercontent.com/101756449/188976967-bb9438d5-f047-483a-b020-08e7e174d7a4.png">

**Comment by aurmeneta** [comment]
¿Qué versión de node estás ocupando? Puedes revisarlo con `node --version`

**Comment by MartinRosenfeld11** [comment]
La versión "v12.22.12"

**Comment by aurmeneta** [comment]
Intenta actualizando a v14. Esto lo puedes hacer con:

`nvm install 14`
`nvm use 14`

Después de esto ejecuta:
`npm install --global yarn`
`rails webpacker:install`

**Comment by MartinRosenfeld11** [comment]
Avanza un poco más, pero me sigue saliendo el mismo error!

<img width="541" alt="Captura de Pantalla 2022-09-07 a la(s) 18 02 53" src="https://user-images.githubusercontent.com/101756449/188978967-0d845b80-53eb-4f7f-ba24-0be856d53083.png">

**Comment by aurmeneta** [comment]
¿Qué versión de ruby estás ocupando?

**Comment by MartinRosenfeld11** [comment]
<img width="431" alt="Captura de Pantalla 2022-09-07 a la(s) 18 09 26" src="https://user-images.githubusercontent.com/101756449/188980547-62c475af-8c61-40e3-b09b-9caf63859aa4.png">

**Comment by aurmeneta** [comment]
Y de rails?

**Comment by MartinRosenfeld11** [comment]
Rails 6.0.5.1 !!

**Comment by MartinRosenfeld11** [comment]
Me ayudaron! Gracias!

**Comment by MartinRosenfeld11** [comment]
Repetí todos los pasos y funcionó!

**Comment by simonmb12** [comment]
E Mac también se hace el comando mvm Install 14? porque me aparece que no encuentra el comando nvm
