### ISSUE TITLE
[Heroku][Build failed] Problema con el node

### ISSUE THREAD

**Issue by rodrigoogalde** [IIC2143/Syllabus#63]
![image](https://user-images.githubusercontent.com/85193399/189010000-43f61b49-4b55-48e0-a462-af335995c90f.png)
![image](https://user-images.githubusercontent.com/85193399/189010008-cffc5d26-b8b7-4eac-8fce-cbfc6c6dd277.png)

Hola!
Me sale este error y trate de solucionarlo con yarn, pero me dice que esperaba "14", pero se tiene "16.17.0"

**Comment by aurmeneta** [comment]
Mira [esta respuesta](https://github.com/IIC2143/Syllabus/issues/57#issuecomment-1239845200).

**Comment by rodrigoogalde** [comment]
> aurmeneta

Crack, Graciaas!

**Comment by Gau04** [comment]
Hola! Tengo el mismo problema e intenté con la solución que linkearon, pero sigue sin funcionarme
