### ISSUE TITLE
[Heroku] No default language could be detected for this app

### ISSUE THREAD

**Issue by nsancha** [IIC2143/Syllabus#64]
![image](https://user-images.githubusercontent.com/69521968/189033944-de3a6cc0-e74a-4cb4-bc2a-4fb2b0129604.png)

Holaa, estamos teniendo problemas con subir la aplicación con heroku
Tenemos este error y no sabemos como solucionarlo

**Comment by meretamal** [comment]
Hola, por favor revisa [esta issue](https://github.com/IIC2143/Syllabus/issues/39#issuecomment-1239527766)
