### ISSUE TITLE
Error node push heroku: the engine node is incompatible with this module

### ISSUE THREAD

**Issue by aurzuav** [IIC2143/Syllabus#66]
Hola, he intentado de hacer el push a heroku desde ayer, primero obtenía el error de "webpack not found", pero usando nvm install 14 y nvm use 14 lo solucioné. Pero al hacer el push a heroku, me tira otro error que dice que busca el node 14.x pero se encuentra con el 16. No se porque se me instala a la fuerza el node v16. luego puse en el package.json que busque un node <=14 y también se cae. Porfavor ayuda. 
![Screen Shot 2022-09-08 at 21 10 25](https://user-images.githubusercontent.com/62019560/189251618-dceb6d78-3911-4335-b7a8-91a9bf9f8b36.png)
![Screen Shot 2022-09-08 at 21 10 34](https://user-images.githubusercontent.com/62019560/189251626-0f6a9bc2-1dec-44bb-9294-ab07fd52d66d.png)
![Screen Shot 2022-09-08 at 21 10 44](https://user-images.githubusercontent.com/62019560/189251629-414eec39-f457-49c1-9268-f085c2dc1bee.png)
![Screen Shot 2022-09-08 at 21 10 51](https://user-images.githubusercontent.com/62019560/189251638-30a44d38-32f7-457e-9f4f-c03ebeceea16.png)
![Screen Shot 2022-09-08 at 21 12 37](https://user-images.githubusercontent.com/62019560/189251686-7025b027-ef4a-46bf-baf7-74c6c895ac2b.png)

**Comment by meretamal** [comment]
Podrías intentar cambiar el engine solo por "14.x" y no ">=14.x"?

**Comment by aurmeneta** [comment]
También asegúrate que hayas añadido los buildpacks de nodejs y ruby a tu app de heroku. En ese orden. Esto lo puedes hacer directamente desde la página de la app en heroku en la pestaña Settings. Debería verse algo como esto:

<img width="1252" alt="Captura de Pantalla 2022-09-08 a la(s) 21 17 20" src="https://user-images.githubusercontent.com/13079881/189252427-dd616cb2-b405-4a55-b24a-d752d4c8b6b9.png">

**Comment by felipefuentesporras** [comment]
Intenten usando  node= v12.22.12 en ves de node>= 14.

**Comment by aurzuav** [comment]
Sigue ocurriendo lo mismo.
![Screen Shot 2022-09-08 at 21 34 38](https://user-images.githubusercontent.com/62019560/189254472-0132297a-5bba-47d6-b012-0db5e6e94f2f.png)
![Screen Shot 2022-09-08 at 21 35 54](https://user-images.githubusercontent.com/62019560/189254480-7
![Screen Shot 2022-09-08 at 21 41 26](https://user-images.githubusercontent.com/62019560/189254486-872ec46f-d0e5-48d2-97f1-d0191572eafd.png)
5c1a7fb-8474-4f52-9c8c-3ab35cc86437.png)

**Comment by aurmeneta** [comment]
El orden de los buildpacks es incorrecto. Debe estar nodejs antes que ruby.

**Comment by aurzuav** [comment]
> 



> El orden de los buildpacks es incorrecto. Debe estar nodejs antes que ruby.

funcionooooooo!! gracias!!
