### ISSUE TITLE
Iniciar sesión

### ISSUE THREAD

**Issue by Washaaaan** [IIC2143/Syllabus#66]
**Descripción:**
Yo, como usuario registrado, quiero poder iniciar sesión en la página, para así poder acceder a mi cuenta.

**Condiciones de aceptación:**

    Escenario:

        - Dado un usuario registrado en la página
        - Cuando el usuario registrado presiona el botón "Iniciar sesión" e inserta su correo y contraseña correctamente
        - Entonces el usuario accede a su cuenta

**Comment by Durmye** [comment]
BASTA WASHAN!
