### ISSUE TITLE
Invitación al github

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2143/Syllabus#67]
Hola, me mandaron la invitación al github a una cuenta que ya no existe, me podrían por favor mandar la invitación a la cuenta correcta que es NicoJGutierrez (esta con la que estoy mandando esta issue)?

Gracias de antemano!

**Comment by JosefaPaz** [comment]
Hola!

Invitación enviada :)

**Comment by NicoJGutierrez** [comment]
hola, no me llegó la invitación que me mandaron

**Comment by NicoJGutierrez** [comment]
nevermind, ahí estaba
