### ISSUE TITLE
Problema al hacer el deploy de la app en Heroku // Error:  Failed to install gems via Bundler.

### ISSUE THREAD

**Issue by roahoki** [IIC2143/Syllabus#67]
Buenas, con mi grupo estoy tratando de hacer el deploy a Heroku pero nos salta un error y no hemos encontrado como solucionarlo:

![error failed to install gems via Bundler](https://user-images.githubusercontent.com/89496233/189271448-43f9465a-7cc4-4b9f-8167-f7df1f59e71e.png)

**Comment by meretamal** [comment]
Hola, por favor corre:
```bash
rails app:update:bin
```
acepta todos los cambios y vuelve a tratar.

**Comment by lutjens-baltazar** [comment]
Hola, yo estoy teniendo exactamente el mismo problema, hice lo que pusieron ahí, pero no se me ha arreglado

**Comment by roahoki** [comment]
hola, acabo de ocupar el comando `rails app:update:bin` pero no me funcionó :(
