### ISSUE TITLE
Error con el servidor

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#68]
Hola, estaba tratando de hacer lo de heroku, y no se por qué ahora ya no me deja ni abrir el servidor. Este es el error que me tira:
![Captura de Pantalla 2022-09-09 a la(s) 12 18 36](https://user-images.githubusercontent.com/89275951/189395912-71edb7d1-48f0-4a84-bb1a-0adef3fb29b8.png)

Y trate de hacer un nuevo proyecto, y me tira este error:
![Captura de Pantalla 2022-09-09 a la(s) 12 21 40](https://user-images.githubusercontent.com/89275951/189396338-7f098882-ad9c-4758-a816-fa51048578ca.png)

**Comment by kunafuego** [comment]
Hola! Qué código estás corriendo para crear la nueva app?
