### ISSUE TITLE
Git Push origin

### ISSUE THREAD

**Issue by rodrigoogalde** [IIC2143/Syllabus#69]
Hola!
Cuando el GIt Push en heroku, no se donde se esta cargando, porque al revisar el origin, aparece correctamente conectado, pero no aparecen los cambios en el repositorio de github. Que puedo hacer?
![image](https://user-images.githubusercontent.com/85193399/189397226-35afca77-adff-4422-8511-f5553aba3fb6.png)
![image](https://user-images.githubusercontent.com/85193399/189397376-1609dcba-1288-4e2e-9f21-f178fb10336d.png)

**Comment by meretamal** [comment]
Hola 😁 , tanto github como heroku funcionan con git. Cuando corres `git push heroku main`, se van a subir los cambios a heroku, pero no a github. Si quieres subir los cambios a github, basta con correr `git push`

**Comment by rodrigoogalde** [comment]
Hola!
Efectivamente hice `git push`, como se muestra en la imagen, pero no me aparecen los cambios en el repositorio personal
Hay algun otro comando que pueda usar?
