### ISSUE TITLE
ERROR AL EJECUTAR COMANDO heroku git:remote -a capsula-uno

### ISSUE THREAD

**Issue by nnovoag** [IIC2143/Syllabus#69]
hola llegué a este paso del video y me tira lo siguiente:

noeminovoa@MacBook-Pro-de-Noemi grupo-75 % heroku git:remote -a capsula-uno
 ›   Error: You do not have access to the app capsula-uno.
 ›
 ›   Error ID: forbidden

ayuda porfaa

**Comment by oretmj** [comment]
Hola, puede ser que no hiciste el heroku login (a la cuenta que tiene la app de heroku). Si no es eso trata viendo este link en stackoverflow:

https://stackoverflow.com/questions/32577459/you-do-not-have-access-to-the-app-when-trying-to-access-heroku-console

**Comment by nnovoag** [comment]
si hice el loggin

**Comment by nnovoag** [comment]
buena el link me sirvio!! :) te pasaste
