### ISSUE TITLE
Problema instalacion mac

### ISSUE THREAD

**Issue by Agustinuc** [IIC2143/Syllabus#7]
hola, estoy tratando de instalar rvm en mac corriendo el siguiente codigo: curl -sSL https://get.rvm.io | bash -s stable.
Pero me dice que hay un error porque el certificado a expirado. Esto me aparece en espefico.
<img width="501" alt="Captura de pantalla 2023-03-17 a la(s) 12 42 01" src="https://user-images.githubusercontent.com/89665265/225953000-a07f7368-ee1f-43b5-9abf-f12e36f6cc24.png">

Gracias

**Comment by jpsandoval** [comment]
probaste las instrucciones que envie por canvas en un anuncio?
https://mac.install.guide/ruby/index.html
utilizando rvm? avisame si lograste solucionar
