### ISSUE TITLE
Problema con versión de rails

### ISSUE THREAD

**Issue by Hellonston** [IIC2143/Syllabus#7]
Hola! Tengo un problema con instalar las versiones requeridas, tenia rails en otra versión instalada anteriormente y la desinstale para estar con la 6.0.4
![image](https://user-images.githubusercontent.com/89171505/184433149-72f862d8-47dd-4a28-a7c5-a2797b2c7a4b.png)
Lo que sucede es que al momento de crear el proyecto se me baja automáticamente la versión de rails 6.0.5.1
![image](https://user-images.githubusercontent.com/89171505/184436372-7e8337b7-d829-4b90-9acb-d1641f8128c0.png)
entonces el proyecto queda con esta versión
![image](https://user-images.githubusercontent.com/89171505/184436046-8102d1ec-f6e0-4d34-bc59-9f0984454a00.png)
No sé como solucionarlo y quedarme con la 6.0.4 que pide el proyecto.
De antemano muchas gracias

**Comment by meretamal** [comment]
Hola 😁 , no te preocupes, con usar algún _release_ de Rails 6 debería estar todo ok. Si después, cuando desarrollen su proyecto, llegan a tener algún error a causa de esto, sube otra issue nomás, pero en teoría no debería pasar.

**Comment by Hellonston** [comment]
Perfecto! Muchas gracias 😊
