### ISSUE TITLE
Comportamiento DELETE a teams

### ISSUE THREAD

**Issue by k0rval4n** [IIC2143/Syllabus#7]
¡Hola! Escribo preguntando sobre el comportamiento cuando se solicita hacer DELETE tanto a un team específico como a todos los teams: ¿se debe eliminar tanto el team correspondiente junto a todos los matches y jugadores asociados al team, o solo se debe elminar el team y no los matches y jugadores que estan asociados a él?

Quedo atento a su respuesta.

**Comment by FelipeMunozMoraga** [comment]
Hola! efectivamente se espera que exista comportamiento en cascada con el DELETE, es decir, al eliminarse un team se eliminan los matches y players asociados a el team eliminado. 
Saludos!

**Comment by k0rval4n** [comment]
¡Muchas gracias! 😄
