### ISSUE TITLE
Problemas con push en Heroku

### ISSUE THREAD

**Issue by Gau04** [IIC2143/Syllabus#70]
Hola! Estoy intentando hacer deploy de la app en Heroku y no puedo hacerlo funcionar. Leí y probé las soluciones de otras issues y sigue sin funcionarme, este es el error que me sale:

![image](https://user-images.githubusercontent.com/80788847/189397551-09a00727-a971-43f6-ad62-8e698e8793a1.png)

verifiqué el orden de los buildpack en heroku, así que de verdad no sé que puede estar fallando.

**Comment by 333k444** [comment]
Mismo error, avisa si lo resuelves!

**Comment by juanfdezg** [comment]
Mismo error también!

**Comment by kunafuego** [comment]
Hola! Por si aun no lo solucionan, encontré esta [issue](https://github.com/rails/webpacker/issues/512) con muchísimas posibles soluciones. 

Ojo que en el error que mandaste tamién te dice que ya subistes la misma versión del código. Acuérdate de siempre indicar la branch (`main` o `master`) a la hora de hacer los push a heroku. 

En muchos sitios salía que una posible solución también era crear una app nueva y que así muchas veces se arreglaba. 

Ojalá les sirva! Si siguen con el error me avisan
