### ISSUE TITLE
error push

### ISSUE THREAD

**Issue by nnovoag** [IIC2143/Syllabus#70]
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
 !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed

esto me aparece al hacer la parte del push de la capsula 1

**Comment by nnovoag** [comment]
<img width="1180" alt="Captura de Pantalla 2022-04-07 a la(s) 10 04 36" src="https://user-images.githubusercontent.com/62225957/162218431-23e7524c-5b92-4954-b587-fd99a5873611.png">
 me tira este error

**Comment by JupaOlivares** [comment]
Revisa si los archivos del repo están correctos, ese error pasa a veces cuando heroku no detecta los archivos de ruby porque por ejemplo metiste todo dentro de una su carpeta

**Comment by DQPalomera** [comment]
> Revisa si los archivos del repo están correctos, ese error pasa a veces cuando heroku no detecta los archivos de ruby porque por ejemplo metiste todo dentro de una su carpeta

Hola!
Me tira este mismo error, pero tengo todo en orden con el repo y mi carpeta

![Captura de pantalla de 2022-04-16 11-36-22](https://user-images.githubusercontent.com/80777199/163681504-c5668017-044a-45ad-8879-86eaa3614110.png)

Y me han salido 3 errores, pero en la marcha este es el único que se mantiene.

**Comment by JupaOlivares** [comment]
> > Revisa si los archivos del repo están correctos, ese error pasa a veces cuando heroku no detecta los archivos de ruby porque por ejemplo metiste todo dentro de una su carpeta
> 
> Hola! Me tira este mismo error, pero tengo todo en orden con el repo y mi carpeta
> 
> ![Captura de pantalla de 2022-04-16 11-36-22](https://user-images.githubusercontent.com/80777199/163681504-c5668017-044a-45ad-8879-86eaa3614110.png)
> 
> Y me han salido 3 errores, pero en la marcha este es el único que se mantiene.

Hola! Creo que a algunos les ha servido esto para ver lo del procfile: https://devcenter.heroku.com/articles/getting-started-with-rails6#create-a-procfile?
