### ISSUE TITLE
Ayuda con Repositorio Tarea

### ISSUE THREAD

**Issue by Matias449** [IIC2143/Syllabus#71]
Me llegó la invitación al repositorio pero venció y ahora tampoco puedo llenar el formulario de la tarea nuevamente, help pls

**Comment by Matias449** [comment]
No tenía idea que podía vencer la invitación plis ayuda :'v

**Comment by cotyahumada** [comment]
Hola! Le tienes que escribir a felipe.munoz.moraga@uc.cl para ver que hacer.
