### ISSUE TITLE
[Tarea] - Duda sobre la carpeta Database Generator

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2143/Syllabus#72]
Hola, viendo los archivos de la tarea me di cuenta que hay una carpeta llamada Database Generator la cual no se menciona nunca en el enunciado de la tarea, y esto me dejo algo confundido, ¿esta carpeta es solo por si nosotros queremos crear una database en vez de usar la que nos dieron de prueba?, ¿o hay que usar obligatoriamente los comandos que aparecen alli?

Ademas tenia la duda de que si hay que subir la carpeta data en nuestro archivo .zip, aunque esta este vacia.

Eso seria, ¡muchas gracias!

**Comment by meretamal** [comment]
Hola, en cuanto a la duda de la carpeta extra, se me fue agregarlo al anuncio, pero es un script para que puedan generar sus propios datasets, para que así puedan probar con distintos archivos y no solo los de prueba (sin embargo, no tendrían la solución correcta para aquellos).

En cuanto al formato de entrega, no deben subir la carpeta data.

**Comment by NicolasOlmosQuiroga** [comment]
Me quedo todo claro, ¡muchas gracias!
