### ISSUE TITLE
error FATAL: role "root" does not exist

### ISSUE THREAD

**Issue by anibalriveros** [IIC2143/Syllabus#72]
Al abrir http://localhost:3000/ me aparece un error FATAL: role "root" does not exsit. Hice todos los pasos para el setup y no lo he podido arreglar

**Comment by giacop002** [comment]
[Ubuntu Windows] me pasó lo mismo.
Al escribir comandos en la consola supongo que te aparece algo como `root@somethingsomething:/mnt/c/Users/TuNombreDeUsuario#`

Prueba creando otro usuario con el nombre _root_ ([paso 7 del setup](https://github.com/IIC2143/Syllabus/wiki/Setup-Ubuntu---Windows#7-postgresql-superuser): "**vamos a crear un usuario con el mismo nombre que el usuario de tu sistema (acá tomaremos como ejemplo que mi usuario se llama myuser)**") 
`CREATE USER root WITH SUPERUSER PASSWORD 'somethingsomething';`

No estoy seguro que sea esa la solución correcta, pero a mí me funcionó ya que al usuario que había creado le había puesto el nombre de mi usuario de Windows de mi pc; pensé que a eso se refería la guía de setup.

**Comment by anibalriveros** [comment]
Ahi se me arregló!! Muchas gracias por la ayuda
