### ISSUE TITLE
Duda Enunciado DELETE /teams/matches/low

### ISSUE THREAD

**Issue by DaniSZ02** [IIC2143/Syllabus#73]
Luego de eliminar el equipo con peor puntaje, se deben borrar los partidos en lo que jugaba ese equipo? Mi duda es si al borrar un equipo, los puntajes de los demás equipos deben ser calculados nuevamente si es que se hace otro DELETE o se usan los puntajes iniciales antes de borrar un equipo (por así decirlo, la tabla inicial).

**Comment by jtvaldivia** [comment]
Se deben volver a calcular.
