### ISSUE TITLE
Heroku: página no existe

### ISSUE THREAD

**Issue by nicolaspoli** [IIC2143/Syllabus#73]
Hola!

Tenemos un problema: cuando subimos la página dice que le builder es exitoso, pero al abrir en Heroku dice que no existe.

Nos muestra el siguiente error:

![imagen](https://user-images.githubusercontent.com/69522096/162325439-62483645-39a5-4792-b9a7-fb9a5075771b.png)

Y este es nuestro log:

![imagen](https://user-images.githubusercontent.com/69522096/162326000-4c9c92e5-bb83-4efc-88f4-988d06fdfc12.png)

Gracias de antemano

**Comment by JosefaPaz** [comment]
Hola!

En heroku tienes los siguientes buildpacks?


<img width="550" alt="Screen Shot 2022-04-07 at 19 36 28" src="https://user-images.githubusercontent.com/41802643/162336266-e9da570f-3c55-412c-b46c-2201fcd6f679.png">

Si no los tienes, intenta agregarlos a heroku, cambiar una linea de codigo en alguna parte del proyecto, y hacer el deploy de nuevo!

**Comment by nicolaspoli** [comment]
gracias ya funcionó :D
