### ISSUE TITLE
Error de deploy Render con webpacker-cli

### ISSUE THREAD

**Issue by VicenteAntonio** [IIC2143/Syllabus#73]
buenas noches, cuando hago deploy a render me tira el siguiente error:

![Captura de pantalla 2023-04-05 022028](https://user-images.githubusercontent.com/89088190/229997574-169847fe-461f-40ad-9664-acd4ab3ba9e2.png)

Posiblemente tenga errores asociados a descargas con yarn. Quiero saber ademas como se arregla el error de arriba.

PD: al correr el servidor con rails server y verlo en localhost:3000 no hay ningún problema.

**Comment by Gtruaan** [comment]
Revise el problema con Vicente y estaban usando Ruby 2.6 / Rails 6. Esto generaba problemas con las dependencias.

Todo solucionado ahora!
