### ISSUE TITLE
La página de heroku no existe

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#73]
Hola, se hizo bien el deployment, pero me tira lo siguiente al ver la app
![Captura de Pantalla 2022-09-09 a la(s) 19 53 50](https://user-images.githubusercontent.com/89275951/189459951-396f1742-38d8-4fdf-9bfd-6ee80aec7f5c.png)

**Comment by kunafuego** [comment]
Hola! Se me ocurren dos posibles opciones:

1. No estás en el link correcto (revisar el link que te da heroku).
2. La app se cae en alguna ruta. Para revisar esto prueba que la app funcione corriéndola local (corriendo `rails server`).

Avísame si era alguno de estos errores!
