### ISSUE TITLE
Error "The page you were looking for doesn't exist" una vez hecho el deploy.

### ISSUE THREAD

**Issue by cfernandek** [IIC2143/Syllabus#74]
Hola!

Tengo un error al **abrir la aplicación por el navegador** me sale (lo de la foto que está adjunta). Me sale en la terminal que el deploy de la aplicación se pudo hacer correctamente sin embargo no se me abre. Revisé los git logs y el error que me sale no se arreglarlo (segunda foto). ¿Cómo puedo arreglar esto?

Gracias!

**Comment by cfernandek** [comment]
<img width="1067" alt="Captura de Pantalla 2022-04-07 a la(s) 17 45 15" src="https://user-images.githubusercontent.com/69773929/162325651-22a6efea-fd33-40a7-8ad4-3844f7eafeab.png">
<img width="832" alt="Captura de Pantalla 2022-04-07 a la(s) 17 50 18" src="https://user-images.githubusercontent.com/69773929/162325727-177d61f5-2c6c-40ef-bdb6-4d501af26eea.png">

**Comment by JupaOlivares** [comment]
Probaste haciendo `yarn add @rails/webpacker`?

**Comment by cfernandek** [comment]
Si, eso lo hice para solucionar el error que me aparecía en la terminal (el de las issue #68) ya no me sale error en el terminal, pero si esto en los logs

**Comment by JosefaPaz** [comment]
Hola!

En heroku tienes los siguientes buildpacks?

<img width="550" alt="Screen Shot 2022-04-07 at 19 36 28" src="https://user-images.githubusercontent.com/41802643/162336244-dc0862ad-7f80-4ea9-b4db-59dd5195606c.png">

**Comment by cfernandek** [comment]
Si, ya los tengo.

**Comment by JosefaPaz** [comment]
y qué logs te entrega la terminal de heroku?

**Comment by cfernandek** [comment]
Me aparecen varios en azul,  pero según yo acá puede estar el problema, no se como arreglarlo eso sí

2022-04-07T23:42:41.413936+00:00 app[web.1]: I, [2022-04-07T23:42:41.413849 #4]  INFO -- : [4d6cd3aa-1260-4a47-a1be-786f66f3389e] Started GET "/" for 201.214.86.224 at 2022-04-07 23:42:41 +0000
2022-04-07T23:42:41.414647+00:00 app[web.1]: F, [2022-04-07T23:42:41.414584 #4] FATAL -- : [4d6cd3aa-1260-4a47-a1be-786f66f3389e]
2022-04-07T23:42:41.414649+00:00 app[web.1]: [4d6cd3aa-1260-4a47-a1be-786f66f3389e] ActionController::RoutingError (No route matches [GET] "/"):

**Comment by cfernandek** [comment]
Este es el log completo por si

<img width="1440" alt="Captura de Pantalla 2022-04-07 a la(s) 19 49 13" src="https://user-images.githubusercontent.com/69773929/162337451-0b215c21-0b9b-4e41-af3c-0ee753e08d2e.png">
<img width="1440" alt="Captura de Pantalla 2022-04-07 a la(s) 19 49 33" src="https://user-images.githubusercontent.com/69773929/162337467-adb65706-b49c-432b-b1ee-679a71382a63.png">
<img width="1440" alt="Captura de Pantalla 2022-04-07 a la(s) 19 49 48" src="https://user-images.githubusercontent.com/69773929/162337477-e152952a-f471-4a78-852c-1b0d14a4a5a9.png">
