### ISSUE TITLE
Duda con archivos a subir Tarea 1

### ISSUE THREAD

**Issue by sbarriag** [IIC2143/Syllabus#74]
Hola tengo 2 consultas sobre la entrega de la T1 en github ; primero para poder tener mi repositorio local tuve que **borrar la carpeta. git** que se crea dentro de la carpeta de la api, puesto que ya se crea un .git afuera, adjunto imagen 
![image](https://github.com/IIC2143/Syllabus/assets/127463084/d3116e6f-448e-4c74-9d3a-4f35a3f38991)
Esta es la carpeta principal de la tarea, dentro de la cual tengo la carpeta con la API de la que tuve que borrar el .git la cual adjunto sus contenidos ahora 
![image](https://github.com/IIC2143/Syllabus/assets/127463084/94eaadf9-1081-4ab9-8074-f861a3cb186b)
No es problema haber tenido que borrar el .git de adentro verdad?

Y mi segunda pregunta es si todos los archivos que están en la segunda imagen son los que se deben subir verdad? 

Muchas gracias

**Comment by jtvaldivia** [comment]
No entendi bien cual .git borraste, pero si debe quedar solo 1. Lo segundo se envio en un anuncio un ejemplo de como se debe subir la tarea en el repo(esta en el telegram la imagen si no la logras ver en canvas.)

**Comment by sbarriag** [comment]
Borré el .git que queda dentro de la carpeta SoccerApi y deje el que venia con el repositorio
