### ISSUE TITLE
Edge cases: ¿Cuál es la respuesta esperada?

### ISSUE THREAD

**Issue by 3rdPix** [IIC2143/Syllabus#75]
Afinando detalles en la tarea me di cuenta que, como es de esperarse, en los test públicos no se abordan todos los casos. El problema que tengo con esto es que en el enunciado no se especifica el resultado (`response`) esperado en tales casos. Y es un detalle importante considerando que en algunos casos se espera `{}`, y en otros `[]` para consultas donde no hay instancias de lo que se solicita, o que se elimina algo. Luego, por ejemplo, si quisiera hacer una consulta de `/players/topCards/:quantity` sin que existan registros de jugadores, no sabría si responder `{}`, `[]`, ó algún *status code* de error para que la respuesta sea considerada correcta. 

¿Qué debería responderse en tales casos? ¿O simplemente podemos asumir que estos casos donde no se explicíta el resultado esperado no se presentarán? Esto último de hecho se deduce de la implementación de las funciones en los *tests* (véase `get_player_top_cards`, en que nunca revisa algún *status code*) pero, de nuevo, no sé si usarán las mismas. Al final la pregunta igual queda: ¿Cuál es el estándar a responder en esos casos?

**Comment by jtvaldivia** [comment]
ese estilo de casos bordes no se abordaran. Se veran mas bien de las request y casos si nombrados en el enunciado. Por ejemplo en casos de validaciones o que pasaria si intentas hacer un get o patch de un partido no existente.
