### ISSUE TITLE
Duda que piden de output para productos 

### ISSUE THREAD

**Issue by nolate26** [IIC2143/Syllabus#75]
Hola!
En la tarea piden que listemos los productos de está manera PRODUCT {NOMBRE} {CANTIDAD}, en esta parte no me queda claro que piden sobre {CANTIDAD}.
Muchas gracias!

**Comment by meretamal** [comment]
Hola 😁 , se refiere al stock total que queda entre todas los supermercados. Por ejemplo, si en el supermercado 1 quedaron 20 manzanas y en el supermercado 2 quedaron 10 manzanas, el stock final (CANTIDAD) es 30.
