### ISSUE TITLE
Error al deploy Heroku webpack not found, posibles soluciones no funcionan

### ISSUE THREAD

**Issue by albertoar1** [IIC2143/Syllabus#75]
![image](https://user-images.githubusercontent.com/80775948/162337069-f9e8cac3-9336-4809-80b3-d376c5f60a59.png)

Llevo dias intentando hacer deploy de Heroku pero siempre me sale el mismo error, e intentado siguiendo las instrucciones de una issue de rails y de las otras issues similares de aca pero o no hacen nada o me causan errores distintos
Los logs de Heroku solo me entregan una pagina que me muestra el mismo error que la terminal

**Comment by sebacarrasco** [comment]
Hola! hoy en la ayudantía un alumno tenía el mismo problema y lo resolvió con lo que se comenta [acá](https://discuss.rubyonrails.org/t/deploying-to-heroku-command-webpack-not-found/76409/7), pero con la versión 4.3.0 del webpacker
