### ISSUE TITLE
Como revisar test 

### ISSUE THREAD

**Issue by nolate26** [IIC2143/Syllabus#76]
Hola!
No entiendo muy bien como revisar algún testcase, para asegurarme que mi tarea está correcta. Existe algún `output.txt` con el resultado de `events.txt `? 
Muchas gracias!

**Comment by meretamal** [comment]
Hola 😁. Les subimos dos cosas para que puedan probar sus tareas:
1. Primero que todo, está la carpeta "Archivos de ejemplo", la cual contiene la data a utilizar junto con un archivo output.txt que corresponde a la solución de ese dataset
2. Segundo, les subimos un script en la carpeta "Dataset generator" que les permite generar sus propios datasets, pero sin la solución.

**Comment by nolate26** [comment]
gracias!
