### ISSUE TITLE
Error Heroku: missing script 

### ISSUE THREAD

**Issue by aiherrera1** [IIC2143/Syllabus#76]
Hola, no logro entender este error que me sale al abrir la pagina en heroku. Que puedo hacer?
![image](https://user-images.githubusercontent.com/67199617/162357085-bbcae2f9-2740-4898-9fc1-285cf719ace3.png)

![Screenshot 2022-04-07 232637](https://user-images.githubusercontent.com/67199617/162356957-274e90e6-13c4-4673-aa8d-5e54fef0ba7f.png)

**Comment by anibalcontreras** [comment]
Tenemos el mismo problema

**Comment by albertoar1** [comment]
Tenemos el mismo problema, y según lo que he encontrado lo que nos falta es el script start, el cual no es difícil de crear pero no se a que tiene que apuntar

**Comment by ctoro05** [comment]
Si alguno lo logra por favor que cuente por acá como lo resolvió

**Comment by albertoar1** [comment]
Logre arreglarlo siguiendo la issue #77

**Comment by ctoro05** [comment]
Gracias! te pasaste
