### ISSUE TITLE
Como se entrega el bonus

### ISSUE THREAD

**Issue by nolate26** [IIC2143/Syllabus#77]
Hola!
Quería saber donde se entrega el bonus, va a haber un buzón/repositorio?
Muchas gracias!

**Comment by meretamal** [comment]
Hola, tal como se indica en el enunciado, se entrega en un buzón de canvas.

Esté se va a crear en la brevedad.

**Comment by nolate26** [comment]
Hola! 
Al final donde se encuentra el buzón que no lo encuentro.
Gracias

**Comment by meretamal** [comment]
Hola 😁 , podrías confirmar si te aparece el buzón?
