### ISSUE TITLE
Heroku -Application error "APP CRASHED"

### ISSUE THREAD

**Issue by MaxWhiting** [IIC2143/Syllabus#77]
Hola pude hacer el git push heroku main sin problema pero ahora tengo este error al abrir la app. Foto 1 es al correr heroku logs
![Captura de Pantalla 2022-04-07 a la(s) 23 26 00](https://user-images.githubusercontent.com/69617525/162357020-970055c8-7e10-4ea4-a47c-ef42bd79418a.png)
![Captura de Pantalla 2022-04-07 a la(s) 23 26 11](https://user-images.githubusercontent.com/69617525/162357040-da9ae17b-78c8-4989-aa5c-2233f848585b.png)

**Comment by a-ck** [comment]
Nos pasa lo mismo

**Comment by naderhadweh** [comment]
A nosotros también nos pasa

**Comment by a-ck** [comment]
Lo arreglamos haciendo un archivo procfile!!!! dejo el link :)
https://devcenter.heroku.com/articles/getting-started-with-rails6#create-a-procfile

**Comment by naderhadweh** [comment]
Buenisima muchas gracias
