### ISSUE TITLE
POST matches

### ISSUE THREAD

**Issue by MartinChaud** [IIC2143/Syllabus#77]
Hola, llevo desde el sabado con el siguiente problema al hacer post matches. Asumo que es porque el codigo espera recibir un teamA y teamB de tipo references y recibe el id. Lo mejor que he logrado hacer es `params.require(:match).permit(:teamA_id, :teamB_id, :state, :result)`, donde funciona si recibe un response body donde :teamA_id y :teamB_id (que claramente no sirve). No se que hacer, llevo desde el sábado con este error.

![imagen](https://github.com/IIC2143/Syllabus/assets/89164489/bd4a2eef-ffe2-4f4b-9725-061f5b0115e6)

**Comment by MathiasPrett** [comment]
Tengo el mismo problema. Al final las columnas se llaman teamA_id y teamB_id pero los tests están hechos para que el request de post matches reciba solo los nombres teamA y teamB. No he podido solucionarlo todavia, pero creo que se podría usando la opción de darle un [alias](https://api.rubyonrails.org/v7.0.8.1/classes/ActiveModel/AttributeMethods/ClassMethods.html#method-i-alias_attribute) a esos atributos, cosa que sea equivalente llenar esos campos por ambos nombres.

**Comment by jtvaldivia** [comment]
Les cuento que se vio este problema en al ayudantia y esta subido el ppt de esta.

**Comment by MartinChaud** [comment]
No que el que se vio en la ayudantía fue PATCH y no POST?

**Comment by jtvaldivia** [comment]
Como tienes definido el teamA? deberia ser una referencia?

**Comment by MartinChaud** [comment]
En la migración lo tengo definido como `t.references :teamA, null: false`, si a eso te refieres.

**Comment by jtvaldivia** [comment]
Ya, creo que ahi esta el problema. Debes de alguna manera entregarle la referencia de ese equipo y no el id. Como hacerlo ahi queda a tu libertad. Como pista en el controller puedes ocupar el id para identificar ese equipo.
