### ISSUE TITLE
Coherencia  ususario contraseña.

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2143/Syllabus#77]
Como usario, quiero que haya una única relación dentro del data set que conecte a mi nombre de usuario con mi contraseña. 

Dado un usario que navegue en la página de inicio, una vez escrito el nombre de usario vinculados ingresen a la página.

**Comment by Alonsito1911** [comment]
Como usuario, quiero que haya una única relación dentro del data set que conecte a mi nombre de usuario con mi contraseña para que así mi cuenta registrada en la pagina sea única y exclusivamente mía, es decir, que la pagina web no me deje entrar a la pagina principal por poner cualquier contraseña .
