### ISSUE TITLE
Error push a heroku

### ISSUE THREAD

**Issue by gonzaga2000** [IIC2143/Syllabus#78]
Hola! cuando queremos hacer push hacia heroku nos sale el siguiente error:
![errorsito](https://user-images.githubusercontent.com/80769344/162450245-1e9fd78a-883f-4471-90cf-86ab1a317bcf.jpg)

Vimos que hay mas personas con el mismo problema por si podrían ayudar a solucionarlo porfaa

**Comment by emiliaup** [comment]
Sii porfa

**Comment by jpsandoval** [comment]
no soy experto, pero parece que ... en algún archivo, tal vez en el gemfile ... tiene un string 'ruby' con un caracter raro al final ... este '\r'... entonces yo borraria ese string y lo volveria a escribir para asi evitar caracteres raros que no se ven ... tal vez funcione...

**Comment by Sebalti** [comment]
Hola lo pudiste solucionar? Estoy con el mismo error

**Comment by amorande1** [comment]
Hola! Estoy con el mismo error. Quedo atento a soluciones, gracias!
