### ISSUE TITLE
”[Tarea] - Número de ID en los distintos archivos”.

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2143/Syllabus#78]
Hola buenas, con respecto al número de ID que tendrán tanto los supermercados, productos y clientes.
Se que en el enunciado mencionan que 'el id es único y no necesariamente será igual a la posición en la que aparezca en el archivo', pero mi duda es si en los archivos habrán saltos de ID, es decir, siempre obtendremos, por ejemplo, input id:1, id:5, id:4, id:3, id:2 o también podemos recibir como input id:1, id:3, id:5. En resumen, mi pregunta es si los ID ordenados siempre serán continuos o habrán id faltantes.

**Comment by meretamal** [comment]
Hola 😁 , sí puede pasar que hayan ids faltantes, es decir, que si hay 5 clientes, estos puedan tener ids 1, 4, 100, 542 y 80
