### ISSUE TITLE
Cambio de contraseña.

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2143/Syllabus#79]
Como usuario, quiero que cambiar mi contraseña por temas de seguridad.

Dado un usuario registrado que navega en la página  principal, cuando pincha la opción 'cambio de contraseña', e ingrese un mail válido, se le pide que ingrese el código enviado a la dirección indicada.

**Comment by Alonsito1911** [comment]
Condiciones de satisfacción: 
Dado un usuario que navega a la pagina de inicio.
∗ Cuando el usuario selecciona la opción “cambio de contraseña” e
ingresa un email valido.
∗ Entonces el sistema debe enviar un enlace al email ingresado.
∗ Cuando el usuario entra al sistema a través del enlace.
∗ Entonces el sistema le permite al usuario establecer su nueva
contraseña
