### ISSUE TITLE
Error Webpacker::Manifest::MissingEntryError in Home#index

### ISSUE THREAD

**Issue by jahernandez2** [IIC2143/Syllabus#79]
Hola! Cree mi primer controlador de la siguiente manera: _rails g controller Home index_ (luego de que en las rutas coloqué _get "/bienvenida", to: "home#index"_ ) 
Busqué el error y no me sirve instalar lo que me pone en stackoverflow. 
Saludos y gracias de antemano.

**Comment by meretamal** [comment]
Hola 😁 , por favor revisa [esta respuesta](https://github.com/IIC2143/Syllabus/issues/28#issuecomment-1236231903) y dime si te sirve.

**Comment by jahernandez2** [comment]
Disculpa no la vi! Muchas gracias!
