### ISSUE TITLE
not delete_team

### ISSUE THREAD

**Issue by rocimarquez** [IIC2143/Syllabus#79]
Tengo una duda de que tiene que suceder cuando las funciones del test_case aparecen llamadas con not adelante. Ya que me tira error (False), pero mi response body es el mismo que el expected

**Comment by jtvaldivia** [comment]
Hola, 
los test que tienen not antes son casos donde tu codigo deberia retornar un error. Por ejemplo, tratar de hacer un patch de un partido que no existe o que no cumple con lo minimo que debe tener el modelo.
