### ISSUE TITLE
[Tarea] - Orden informacion_aldeanos()

### ISSUE THREAD

**Issue by Ajbarros1** [IIC2143/Syllabus#8]
En el enunciado dice que en informacion_aldeanos(), tenemos que ordenar estos según su id, pero en el archivo expected_output.txt los ordenan por tipo (ponen a todos los granjeros primero, luego a los herreros y después a los bibliotecarios). Nos guiamos según el enunciado o el expected_output.txt?

**Comment by maggiemunoz** [comment]
Hola! Disculpa la demora, la idea es ordenar por tipo, y dentro del tipo, ordenar por id. Voy a actualizar en enunciado para que quede más claro
