### ISSUE TITLE
Atributos de tipo references

### ISSUE THREAD

**Issue by martina-abello** [IIC2143/Syllabus#8]
¿Cómo funcionan? No sé si los veremos en clase o algo, pero de momento no tengo idea y _creo_ que me están causando un error al intentar migrar la base de datos, porque me aparece:
_StandardError: An error has occurred, this and all later migrations canceled:_

_PG::UndefinedTable: ERROR:  relation "teamAs" does not exist_

pero en realidad no sé si es eso.

Gracias de antemano.

**Comment by MartinChaud** [comment]
A mi también me esta dando el mismo error :(

**Comment by noamsito** [comment]
Puede estar pasando por algún error de tipeo en la tabla, por lo tanto cuando vas a hacer la migración no encuentra alguno de los atributos o relaciones que creaste en el modelo en cuestión. Entonces trata de revisar los nombres de los atributos, relaciones e incluso el nombre del modelo.

**Comment by martina-abello** [comment]
No encuentro ningún problema con los nombres en los archivos de db/migrate ni en los controllers ni en los models. ¿En qué otros archivos podrían estar?

**Comment by MartinChaud** [comment]
A mi me aparece lo siguiente en la tabla:

``` 
class CreateMatches < ActiveRecord::Migration[7.0]
  def change
    create_table :matches do |t|
      t.references :teamA, null: false, foreign_key: true
      t.references :teamB, null: false, foreign_key: true
      t.boolean :state
      t.string :result

      t.timestamps
    end
  end
end 
```

**Comment by MartinChaud** [comment]
En el archivo de la migración, me aparecen los atributos de tipo references de la siguiente forma:

```
      t.references :teamA, null: false, foreign_key: true
      t.references :teamB, null: false, foreign_key: true
```
No se si esto es lo que se supone que tiene que estar en el documento de migración (esto es lo que a mi se me generó de manera automática), pero no veo porque estaría leyendo "teamAs".

**Comment by martina-abello** [comment]
Me sale igualito.

**Comment by martina-abello** [comment]
Holaa, en la ayudantía de hoy me ayudaron, el problema es _foreign_key: true_, tiene que ser _foreign_key: {to_table: :teams}_ para indicar a dónde apunta la referencia.

**Comment by k0rval4n** [comment]
@noamsito:
> El otro motivo que puede ser es el nombre con el cual generaron el modelo, por que al momento de crear los controladores estos deben tener el nombre en plural, y los modelos deben estar en singular, por lo que es probable que hayan nombrado el modelo plural según lo que aparece en el error. Así que traten de eliminar los controlador y modelo, creándolos nuevamente como les indiqué, y el código que ya tenían escrito lo copian y pegan en los archivos correspondientes.
> 
> Cualquier duda que tengan de como eliminar, crear, controladores y modelos o cualquier cosa por el estilo aquí está la documentación del ruby on rails para que le echen una miradita :)
> 
> https://guides.rubyonrails.org/getting_started.html
> 
> En caso de que el error todavía persista utilicen el shortcut de cmd + shift + F (para mac) o ctrl + shift + F (en windows) esto les permitirá buscar en todos los archivos del proyecto, y deben buscar el "teamAs" en qué parte aparece.

## Noam Tanaka increíble ayudante 😎🔥🔥
