### ISSUE TITLE
Problema paquete RequestAPIPostman

### ISSUE THREAD

**Issue by MaxAl100** [IIC2143/Syllabus#8]
Buenas tardes,

Probando con los requests que nos han subido al syllabus me funcionan todos los requests hasta que se utiliza ``{{firstVaccineID}}``, ya que nunca toma algún valor por alguna razón. Cuando yo relleno los valores manualmente sí me funciona correctamente los requests. ¿Necesito arreglar esto o es un error de los requests que nos han enviado?

**Comment by pablobustose** [comment]
Me pasa lo mismo a mi

**Comment by Balison** [comment]
Hola, si los requests no se modificaron, el valor de {{firstVaccineID}} se asigna cuando se ejecuta el request "create vaccine 1 for person 1", de esta forma puede hacer el request de update y el delete de la vaccine en base a ese ID.

Uno de los factores que puede influir es que no se estan ejecutando en orden los requests, como son request dependientes uno del otro, es importante ejecutarlos en orden. Tambien puedes verificar si se estan asignando los valores de las variables {{firstID}}, {{secondID}} y {{firstVaccineID}} haciendo click en el nombre de la collecion "RequestAPITask" y seleccionando la pestaña variables en el panel de a lado.

![Screenshot 2023-03-22 at 09 49 21](https://user-images.githubusercontent.com/5430825/226909666-d7cd275f-dc0d-4d84-b7d6-f62524fdee24.png)

Por favor, verifica que realmente no se asigne un valor a {{firstVaccineID}} ejecutando los request en orden.
