### ISSUE TITLE
Recuperar contraseña.

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2143/Syllabus#80]
Como usuario, quiero recuperar mi clave en caso de olvidarla.

Dado un usuario ya registrado que navega en la página de inicio, una vez que pincha 'recuperar contraseña' debe escribir su mail de registro para ingresar el código que se le envió a dicho mail.

**Comment by Alonsito1911** [comment]
"Beneficio: de recuperar la clave es para ingresar al sistema en caso de olvidarla" 


Dado un usuario que navega a la pagina de inicio.
∗ Cuando el usuario selecciona la opción “recuperar contraseña” e
ingresa un email valido.
∗ Entonces el sistema debe enviar un enlace al email ingresado.
∗ Cuando el usuario entra al sistema a través del enlace.
∗ Entonces el sistema le permite al usuario establecer su nueva
contraseña
