### ISSUE TITLE
[Rails] Duda rutas

### ISSUE THREAD

**Issue by diegocostares** [IIC2143/Syllabus#80]
Hola, estoy intentando hacer que una clase cambie dependiendo de la ruta del dominio, es decir, me gustaria que se ejecutara algo cuando esta en el inicio y otra cosa cuando no...

El problema es que no se como acceder al path actual, ni como compararlo correctamente

**Comment by diegocostares** [comment]
Se me ocurre que podría cambiar la clase del header cuando no se encuentre en el path de inicio, pero no sé cómo acceder a este con rails

**Comment by diegocostares** [comment]
Lo que intente hacer es lo siguiente:
```ruby
<% if root_path== "/" > # Aca me gustaria verificar que este en la ruta de inicio (puede tener terminacion \en o \es tambien)
     <nav class="navbar1">
<% else %>
     <nav class="navbar2" >
<% end %>
```

**Comment by OrregoSilva** [comment]
Hola!
Quizás lo que estas buscando es el método `current_page?`, puedes ver esta issue donde ven el mismo tema y se explica con mayor detalle.

**Comment by diegocostares** [comment]
Hola @OrregoSilva no entendí como usar el `current_page?`. pero en la misma issue encuentre el comando request.path  que me sirvió! 

Ahora el único problema que estoy teniendo es que estoy hardcodeando los idiomas activos del I18n y no estoy comparando los disponibles... Mi código ahora es:
```ruby
<% if request.path == "/" || request.path == "/en" || request.path == "/es"%>
    ...
```

Pero creo que sería mejor si lograra compararlo con la lista de idiomas que definí con  `I18n.available_locales`
