### ISSUE TITLE
Casos en que no existe el objeto pedido

### ISSUE THREAD

**Issue by juanfra111** [IIC2143/Syllabus#80]
Hola! Estuve leyendo los issues, pero no me logró quedar muy claro. Para los casos que con los test case se pide buscar un objeto que no existe, que se debe retornar? También, para el caso que el equipo no tiene jugadores o no tiene partidos, qué se debe retornar?

**Comment by blampasona18** [comment]
Tengo la misma duda, es necesario manejar estos casos o se asume que siempre se entregarán datos consistentes? De ser el primer caso, qué se debe retornar? O es libre y que sea intuitivo

**Comment by jtvaldivia** [comment]
No siempre seran consistentes y hay casos que se prueban en los tester.
