### ISSUE TITLE
[Tarea] - Duda con respecto al evento ARRIVAL

### ISSUE THREAD

**Issue by paulmacguire** [IIC2143/Syllabus#80]
Hola!
No entiendo muy bien a lo que se refiere con "Si el supermercado se encuentra lleno en ese momento, deberá esperar en una fila
hasta que se desocupe un cupo." Mi pregunta va en el sentido de que si tenemos que imprimir algo en la consola, o algo por el estilo. No entiendo como qué es lo que quieren que hagamos específicamente con ese evento. Lo mismo aplica para los demás eventos, ya que el "output esperado" que sale en el enunciado es exclusivamente de la forma {Entidad} {Nombre} {Dinero/Cantidad} y no muestra ningún tipo de output entremedio o algo por el estilo.

**Comment by meretamal** [comment]
Hola 😁 , no deben imprimir nada en consola. Todo el output esperado va en el archivo de ouput según se especifica en el enunciado. La idea de esperar en la fila es que si, sale un evento PICK con un cliente que no está dentro del supermercado, se debe ignorar, por lo que no cambia el stock de dicho producto, el supermercado no gana dinero y el cliente en cuestión tampoco gasta dinero, lo cual va a influir en el output final.
