### ISSUE TITLE
”[Tarea] - Checkout clientes”.

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2143/Syllabus#81]
Hola, tengo una duda con respecto al checkout de los clientes, cuando dicen que devuelve productos hasta que pueda pagar, se refiere a que si por ejemplo tiene: [[producto_1, cantidad = 5], [producto_2, cantidad = 3]], comienza a devolver uno por uno las cantidades del último producto? o devuelve todas las cantidades del último producto de una? y así sucesivamente hasta que pueda pagar.

**Comment by meretamal** [comment]
Hola 😁 , debe devolver los productos uno por uno. Yendo a tu ejemplo, si el producto_2 fue el último que recogió y devolviendo uno de esos hace que le alcance el dinero, entonces solo debe devolver uno, por lo que termina comprando 5 del producto_1 y 2 del producto_2
