### ISSUE TITLE
Registrar Usuario.

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2143/Syllabus#81]
Como potencial usuario, espero poder crear una cuenta en la página de marketplace.

Dado un potencial usuario que navega por la página de inicio, una vez que pinche 'registrar usuario' el sistema dará la opción de hacer el registro de éste enviando un código al mail escrito. El sistema deberá poder recibir el código de verificación para que la cuenta pueda ser validada.

**Comment by Alonsito1911** [comment]
Beneficio: para poder ingresar al sistema como nuevo usuario
