### ISSUE TITLE
[Rails] Reinicio automático del servidor en modo development

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2143/Syllabus#81]
Hola!

Al usar rails s se renderizan las páginas pero siempre que realizo una modificación a las vistas debo bajar el servidor y volver a subirlo, ya que volver a cargar la página no renderiza los cambios.

¿Hay alguna forma de obligar a rails a que realize un render luego de recargar la página?

Gracias!

PD: Uso Windows y wsl para correr el servidor

**Comment by JupaOlivares** [comment]
Hola! lo que tu buscas es el development mode (cada vez que se guarda un cambio y reinicia el servidor automaticamente), te recomiendo ver los comandos en la pagina de rails

**Comment by Nicolasramos411** [comment]
Hola!

Uso actualmente el modo development pero igual así no se reinicia el servidor.
¿Deberé tener un error con el webpacker?

Envío imagen con información del servidor.

Gracias!

![imagen](https://user-images.githubusercontent.com/80288266/164278775-8db03297-407f-4412-bce3-d1f1e63a549c.png)
