### ISSUE TITLE
Publicar producto.

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2143/Syllabus#82]
Como usuario, quiero poder vender un producto para que el resto de la gente pueda comprarlo.

Dado un usuario navegando en la página principal, cuando selecciona 'vender producto', el sistema lo hace registrar el producto para hacerlo público.

**Comment by Alonsito1911** [comment]
Entonces el sistema le permite al usuario publicar su nuevo producto y así que este sea visible para todo usuario que desee comprarlo.
