### ISSUE TITLE
rails s: Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by felipec14** [IIC2143/Syllabus#82]
![image](https://user-images.githubusercontent.com/101210023/191149918-df4ecbeb-e154-4832-afa4-42850b7e8ab7.png)
Hola.
Tengo este error hace 2 semanas, ya traté reinstalando todo y sigo teniendo el mismo problema.

**Comment by meretamal** [comment]
Hola 😁 , podrías intentar borrar la carpeta de cache (en el path que salé ahí) e intentar de nuevo?

**Comment by felipec14** [comment]
> Hola 😁 , podrías intentar borrar la carpeta de cache (en el path que salé ahí) e intentar de nuevo?

No existe la carpeta cache dentro de tmp, sólo hay una carpeta que se llama pids y un archivo .keeps

**Comment by meretamal** [comment]
podrías correr `sudo chown -R $(whoami) ./tmp` desde la carpeta de tu proyecto?

**Comment by felipec14** [comment]
Lo hice, aparece otro error que pide hacer `yarn` install --check-files` , y al correrlo aparece otro error.
![image](https://user-images.githubusercontent.com/101210023/191318038-ed5d3fe6-71d9-4843-9263-40f8d997cbc0.png)

**Comment by meretamal** [comment]
Yap, parece que tienes problemas de permisos sobre la carpeta del proyecto. Podrías intentar correr el comando anterior, pero ahora otorgando los permisos a toda la app? Si estás en la carpeta "2022-2-grupo-16" sería `sudo chown -R $(whoami) .`

**Comment by felipec14** [comment]
Ahora me funciona, muchas gracias!!
