### ISSUE TITLE
Problema para acceder a http://localhost:3000/users

### ISSUE THREAD

**Issue by icortesc** [IIC2143/Syllabus#82]
Hola, siguiendo las cápsulas llegue hasta la parte en que utilizamos Postman para buscar el controlador "user". Hice todo igual que en la cápsula, me sale el siguiente error:

![issue](https://github.com/IIC2143/Syllabus/assets/106119385/b4928e7e-9409-40fc-8467-5b0036225405)

Alguien sabe como solucionar esto?

Aca esta el resto de cosas q pudiesen ser relevantes;

![image](https://github.com/IIC2143/Syllabus/assets/106119385/52f644d3-3619-4c9a-a75f-6c85cfc3a04a)
![image](https://github.com/IIC2143/Syllabus/assets/106119385/1e23e189-a396-450c-a3c7-bebded2be3be)

**Comment by TheExcel2** [comment]
¿Estás completamente seguro de haber creado un modelo/clase llamado User?

**Comment by jean-Philipe** [comment]
No tienes el modelo User creado en tu schema, cuando hagas rails generate model User, se te crea una migración, pero debes hacer rails db:migrate para asegurarte que esta se guarde (subí la capsula de migraciones ayer por si te confunde).

Como prueba tomé el mismo proyecto de la capsula y creé el metodo prueba que intenta retornar una prueba de la misma forma que lo hacemos con User, pero en este caso para el ejemplo nunca creé el modelo Prueba, mira lo que obtengo:
![image](https://github.com/IIC2143/Syllabus/assets/110950317/6382f852-a32f-41bf-a701-bf42ab94f235)

Es lo mismo que obtienes en tu error, no existe el modelo por lo que el servidor te arroja un error 500. Avisame si el correr la migración (y asegurarte que tienes un modelo User en el schema) te soluciona lo anterior!

**Comment by icortesc** [comment]
No me había dado cuenta de que tenia que crear un controlador para cada modelo, pensaba que era uno general. Muchas gracias.
