### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Simon-Cabrera** [IIC2143/Syllabus#82]

**Comment by waknaudt** [comment]
no entiendo

**Comment by Washaaaan** [comment]
fuersa leona

**Comment by Simon-Cabrera** [comment]
Perdón por el problema ¿Seria posible eliminar mis issues que dicen Error? Pase a subir mis relatos haciendo el project. Elimine el contenido de las issues apenas supe de mi error.

**Comment by Washaaaan** [comment]
> Perdón por el problema ¿Seria posible eliminar mis issues que dicen Error? Pase a subir mis relatos haciendo el project. Elimine el contenido de las issues apenas supe de mi error.

Me había pasado lo mismo, solo tienes que cerrar la issue como "no planeada" y se borra
