### ISSUE TITLE
Problema con el id

### ISSUE THREAD

**Issue by EnriqueVildosola** [IIC2143/Syllabus#83]
Al momento de probar mi código con postman, las cosas que necesito hacer funcionan. Sin embargo cuando corro los test no pasa lo mismo. De manera específica, por ejemplo, cuando se comprueba mi comando post teams, me dice que el resultado esperado es un equipo con id: null. Sin embargo en el enunciado de la tarea me dice que dicho id debe estar con numero. Adjunto pantallazo para que se entienda mejor.
![Captura de pantalla (10)](https://github.com/IIC2143/Syllabus/assets/110938625/4fb14a6f-7897-4fd4-ad4f-2e637cf94354)

**Comment by EnriqueVildosola** [comment]
Alguna sugerencia para poder resolver el problema porfa

**Comment by TheExcel2** [comment]
Fijate que tu capacity devuelve un string y no un entero, debe ser eso
