### ISSUE TITLE
rails g devise:install: Could not find generator 'devise:install'

### ISSUE THREAD

**Issue by piriabud** [IIC2143/Syllabus#83]
Hola, cuando intento ejecutar la línea
`$ rails g devise:install`
utilizada en la ayudantía de devise me arroja el siguiente error
`Could not find generator 'devise:install'.`

Busqué el error y la solución que se proponía era correr `spring stop`, sin embargo me sigue tirando el mismo error que antes.

**Comment by meretamal** [comment]
Hola 😁 , agregaste devise a tu Gemfile y volviste a correr `bundle install`?

**Comment by piriabud** [comment]
sisi

**Comment by meretamal** [comment]
Podrías correr `bundle exec rails generate devise:install`?

**Comment by piriabud** [comment]
lo acabo de correr, me tira el mismo error :c

**Comment by meretamal** [comment]
Podrías intentar borrar tu lockfile (Gemfile.lock), volver a correr `bundle install` y luego `rails g devise:install`?

**Comment by piriabud** [comment]
mismo error :(((

**Comment by meretamal** [comment]
Y al instalar las dependencias (`bundle install`) no te levanta ni un error?

**Comment by piriabud** [comment]
noup, este es el output despues de correr `bundle install`:

`Bundle complete! 17 Gemfile dependencies, 76 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.`

**Comment by meretamal** [comment]
Acabo de hacer el setup con tu proyecto y funcionó sin problemas. Podrías intentar reiniciar tu computador y volver a intentarlo? Estaba en una respuesta de stackoverflow jaja

**Comment by piriabud** [comment]
jajaja yaya, lo intentaré y avisaré qué pasa. Gracias!

**Comment by piriabud** [comment]
Hola, ya reinicié mi pc y sigo teniendo el mismo problema.
Además volví a correr el `bundle install` y el `spring stop` e intenté nuevamente pero sigue arrojando el mismo error.

**Comment by CarloGauss33** [comment]
Que ocurre si utilizas bin/rails en vez de solo rails?

**Comment by piriabud** [comment]
nuevamente me tira el mismo output. Lo voy a pegar textual acá abajo por si a alguien le sirve para orientarme :c

`Running via Spring preloader in process 473
/home/eabud/.rvm/gems/ruby-2.6.6/gems/spring-2.1.1/lib/spring/application.rb:204: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
Could not find generator 'devise:install'.
Run `rails generate --help` for more options.`

porfa aiuda
