### ISSUE TITLE
Webpacker 4.3.0 ya no funciona.

### ISSUE THREAD

**Issue by cncosta** [IIC2143/Syllabus#83]
Hola, estaba corriendo el servidor de manera local pero no funcionaba ya que la versión de webpacker 4.3.0 se quedo sin soporte. Hice el cambio a 5.0.0 y lo arregló y pude actualizar las dependencias correctamente (de manera local). ¿Está bien que haya cambiado de versión de webpacker ?
Por alguna razón mi archivo yarn.Lock cambio de versión de webpacker y no me deja usar la versión 4.3.0.
```shell
Proyecto$ rails s
=> Booting Puma
=> Rails 6.0.4.7 application starting in development 
=> Run `rails server --help` for more startup options
error Lockfile does not contain pattern: "@rails/webpacker@^4.3.0" 
error Couldn't find an integrity file 
error Found 2 errors


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


yarn check v1.22.18
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.


Exiting
```
```shell
Proyecto$ yarn check
error Lockfile does not contain pattern: "@rails/webpacker@^4.3.0"
error Found 1 errors.
```

**Comment by JupaOlivares** [comment]
Hola no deberia haber problema con cambiar la version de webpacker (mientras te funcione la app web todo ok), si presentas problemas siempre puedes devolverte a la version anterior.
