### ISSUE TITLE
No logro correr el tester

### ISSUE THREAD

**Issue by juanfra111** [IIC2143/Syllabus#84]
Estot tratando de correr el tester, pero no logro hacerlo por distintos errores. He intentado poniendo la carpeta tester dentro de mi SoccerApi y correrlo, también poner la carpeta en mi escritorio y correrlo, pero no logro hacerlo correr. Actualmente, cuando corro el archivo test desde mi escritorio con Vsco mediante Powersell me arroja el siguiente error.
![Captura de pantalla 2024-03-26 142542](https://github.com/IIC2143/Syllabus/assets/89438945/8cdc62f2-9ba0-4221-81a0-67e85f6d843c)

**Comment by jtvaldivia** [comment]
pudes abrir la carpeta src?

**Comment by juanfra111** [comment]
Si, desde la consola si puedo abrirla

**Comment by juanfra111** [comment]
![image](https://github.com/IIC2143/Syllabus/assets/89438945/089d1558-4219-486b-95d9-dd911dd5b2c5)
![image](https://github.com/IIC2143/Syllabus/assets/89438945/13adf7ae-b461-4ca1-84bd-4f6e9654cc28)

**Comment by jtvaldivia** [comment]
Que raro, intenta actualizar a 3.10 python

**Comment by juanfra111** [comment]
Eso era, gracias!
