### ISSUE TITLE
 ERROR:  column "email" of relation "users" already exists

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#84]
Hola! Estoy haciendo el crud de usuarios con devise, pero al hacer rails db:migrate me sale el siguiente error. No estoy seguro de cómo arreglarlo.

**Comment by meretamal** [comment]
Hola, podrías mandar el código que tiene las migraciones asociadas a la tabla _users_?

**Comment by simonmb12** [comment]
![Captura de Pantalla 2022-09-25 a la(s) 20 33 07](https://user-images.githubusercontent.com/89275951/192170545-1305be52-09ae-4a34-bc87-17e5770356e8.png)
![Captura de Pantalla 2022-09-25 a la(s) 20 33 28](https://user-images.githubusercontent.com/89275951/192170559-864c7612-2d29-491f-b753-08cafd0c2315.png)

**Comment by simonmb12** [comment]
Estaba siguiendo los pasos, pero se me olvidó guardar un cambio antes de hacer el primer db:migrate, por lo que hice dos veces el generate devise user y la migración, y desde ahí me tira el error. 
![Captura de Pantalla 2022-09-25 a la(s) 20 34 52](https://user-images.githubusercontent.com/89275951/192170640-15f53f5d-a4e9-4dc8-8325-0b438eeede7e.
![Captura de Pantalla 2022-09-25 a la(s) 20 35 01](https://user-images.githubusercontent.com/89275951/192170642-d9990889-aaf9-49ab-ace2-b6e14885ff36.png)
png)

**Comment by simonmb12** [comment]
Estaba siguiendo los pasos, pero se me olvidó guardar un cambio antes de hacer el primer db:migrate, por lo que hice dos veces el generate devise user y la migración, y desde ahí me tira el error.
![Captura de Pantalla 2022-09-25 a la(s) 20 34 52](https://user-images.githubusercontent.com/89275951/192170657-cff3ba62-c2bd-4dc6-8200-65f880f7450c.png)
![Captura de Pantalla 2022-09-25 a la(s) 20 35 01](https://user-images.githubusercontent.com/89275951/192170661-9c2e853b-fc93-49b4-aa23-0cfd09b30535.png)

**Comment by meretamal** [comment]
Por algún motivo tienes una segunda migración que intenta modificar la tabla _users_ agregándole lo necesario para que funcione con `devise`. Esto generalmente pasa cuando ya tiene un modelo `User` (en este caso el creado con `devise`) y vuelves a intentar generar el recurso (esto sí te serviría si hubieras creado al usuario "a mano" antes).

Intenta borrando la segunda migración. No debería afectar, ya que la tabla ya la creó la primera.

**Comment by simonmb12** [comment]
Perfecto! eso lo hago borrando este archivo "20220925230554 add devise to users. rb"? o tengo que hacer un comando especial en la terminal?

**Comment by meretamal** [comment]
Claro, borrando el archivo debería bastar.
