### ISSUE TITLE
Problema ingresar consola PostgreSQL

### ISSUE THREAD

**Issue by pedrocisternas** [IIC2143/Syllabus#85]
Hola, tengo un problema al intentar ingresar a la consola de postgre. Me está pidiendo una clave (que supongo es la que especifiqué al crear el usuario), pero me dice que no es correcta. 

![Image 2022-09-26 at 1 46 06 PM](https://user-images.githubusercontent.com/81447303/192341268-2a38783e-c2aa-4968-8d78-46400882906f.jpeg)

**Comment by meretamal** [comment]
Hola 😁 , podrías ver si tienes este archivo? `/opt/homebrew/var/postgresql@14/pg_hba.conf`

**Comment by pedrocisternas** [comment]
No lo tengo

**Comment by meretamal** [comment]
Cómo instalaste postgres?

**Comment by pedrocisternas** [comment]
Siguiendo los pasos que subieron a la Wiki

**Comment by pedrocisternas** [comment]
![Captura de Pantalla 2022-09-26 a la(s) 3 39 25 p m](https://user-images.githubusercontent.com/81447303/192354816-2e6dc538-b171-4fe4-afa3-f297316d5ca7.png)
 
Ahora tampoco me funciona el comando 'brew services start postgresql'. Intenté borrando algunos paths que me estaba pidiendo, pero apareció otro problema.

**Comment by meretamal** [comment]
Alguna vez instalaste postgres para otro ramo?

**Comment by pedrocisternas** [comment]
Es probable, pero no estoy seguro
