### ISSUE TITLE
Consultas de DELETE /teams

### ISSUE THREAD

**Issue by bugfly1** [IIC2143/Syllabus#85]
Como este es el endpoint de todos los test me quedaron dudas. 
La cosa es que no entiendo si solamente debe de eliminar a los teams o tiene que ser algo como un "reinicio" de la base de datos.
En adición de eliminar los teams, ¿También debe de eliminar los modelos asociados a los teams?
Además ¿Esta bien que no reinicie los ids? Cosa si agrego nuevos teams se me crean con id = 100 en vez de id = 1

**Comment by danilarco** [comment]
Debes eliminar a todos los teams, con todos sus modelos asociados. Para esto basta con tener bien las dependencias en tus modelos y se eliminará todo lo necesario! Los ids dan lo mismo
