### ISSUE TITLE
Rails s: FATAL: database "*" does not exist

### ISSUE THREAD

**Issue by agustindesolminihac** [IIC2143/Syllabus#87]
Hola, al intentar correr el server me tira el siguiente error y no he podido arreglarlo.
![error](https://user-images.githubusercontent.com/49526698/192649727-5715f84d-f42d-46b6-9671-a2d14c1d28cd.png)

**Comment by meretamal** [comment]
Hola 😁 , eso es porque no existe la base de datos del proyecto. Tal como dice el setup, debes configurar tu archivo **database.yml** y correr:
```bash
rails db:create
```

**Comment by agustindesolminihac** [comment]
Hice eso y ahora me arroja lo siguiente:
![error2](https://user-images.githubusercontent.com/49526698/192654404-a16d990d-4118-46eb-88c5-b9151dea619f.png)
