### ISSUE TITLE
Ver calificaciones y opiniones

### ISSUE THREAD

**Issue by Alonsito1911** [IIC2143/Syllabus#87]
Como usuario quiero poder ver las opiniones y calificaciones de otros compradores sobre un producto o del vendedor.

 Dado un usuario que navega a la pagina de productos.
∗ Cuando el usuario selecciona un producto.
∗ Entonces el sistema debe mostrar en algún costado de la pagina tanto la calificación y las opiniones del producto o del vendedor .

**Comment by OrregoSilva** [comment]
Estas issues deben ser creadas en el repositorio de grupo, por lo que tendré que cerrar todas las relacionadas.
