### ISSUE TITLE
No me muestra el resultado show=True

### ISSUE THREAD

**Issue by juanfra111** [IIC2143/Syllabus#88]
Estoy corriendo el tester y pongo el argumento show=True, pero no me escribe en la consola el resultado de la corrida.
![image](https://github.com/IIC2143/Syllabus/assets/89438945/d1bce512-a487-44dc-94e4-520f69d471ad)

**Comment by TheExcel2** [comment]
el show=True va directamente en código, como argumento de la función

**Comment by maromero-21** [comment]
Yo lo modifiqué directamente en los archivos que están en la carpeta src:
![image](https://github.com/IIC2143/Syllabus/assets/89163594/836aeb6c-ef78-4c77-bdd8-4ba123fec1e9)
