### ISSUE TITLE
Webpacker::Manifest::MissingEntryError in Articles#index

### ISSUE THREAD

**Issue by agustindesolminihac** [IIC2143/Syllabus#88]
Hola, al intentar correr el servidor me aparece este error:
![error2](https://user-images.githubusercontent.com/49526698/192659360-b0a9dca0-07b7-4c53-9cfa-5809e219b530.png)

**Comment by meretamal** [comment]
Hola, por favor revisa [esta issue.](https://github.com/IIC2143/Syllabus/issues/28#issuecomment-1236231903)
