### ISSUE TITLE
Agregar etiquetas productos

### ISSUE THREAD

**Issue by Alonsito1911** [IIC2143/Syllabus#89]
Como usuario quiero agregar etiquetas claves  a mis productos que venderé para facilitar y acelerar la búsqueda de los compradores hacia mi producto. 
Dado un usuario que decide publicar un producto para la venta de este.
∗ Cuando el usuario seleccione la opción  “agregar etiquetas".
∗ Entonces el sistema debe permitir agregar las etiquetas que el usuario desee a sus productos.

**Comment by OrregoSilva** [comment]
@Alonsito1911 Ten ojo con donde estás creando esta issues, este es el SYLLABUS, no el repo de tu grupo, eventualmente todo esto lo eliminaré por no estar en el lugar correcto.

**Comment by Alonsito1911** [comment]
sorry, error tonto, acabo de cachar
