### ISSUE TITLE
[Tarea] - Nivel Aldeanos

### ISSUE THREAD

**Issue by Ajbarros1** [IIC2143/Syllabus#9]
En el enunciado nos dicen que la clase padre Aldeano tiene que tener el atributo nivel, pero el nivel de un aldeano depende de su tipo, por lo que  este atributo solo se podría calcular en las subclases, no en la clase padre Aldeano. Que hacemos respecto a esto?

**Comment by kalarconvl** [comment]
El nivel empieza en 1 para cada tipo de aldeano?

**Comment by maggiemunoz** [comment]
Hola! En realidad esto es un poco opcional según cada moderación, pero todos los aldeanos tienen nivel, lo que depende del tipo es cuánta experiencia necesitan para aumentar este, por lo que no habría problemas en tener el atributo nivel en la clase padre.
