### ISSUE TITLE
Controller Update (Tarea 1)

### ISSUE THREAD

**Issue by Zarth912** [IIC2143/Syllabus#9]
Ya asumiendo que el enunciado contiene un error, me ocurrio que cuando uso el .update el orden de los atributos de la vaccine se imprimen en un diferente orden, lo cual me manda error cuando lo corro con postman. ¿Es tan importante que sea un orden especifico al imprimir la vaccine actualizada? y de ser asi, ¿hay alguna manera de arreglar eso que no sea tan invasivo?

**Comment by Zarth912** [comment]
No es la misma pregunta de controller marcada como duplicada, es una duda referida a postman. NO sobre enunciado.

**Comment by Balison** [comment]
Hola, si falla el test correspondiente al "update date of vaccine 1 person 1", es probable que sea porque no estas mostrando las vacunas ordenadas en base al ID y no por el orden de los atributos de las vacunas. Esto significa que la primera vacuna en la que se realiza el update, deberia ser la primera que se muestra y despues la siguiente en base al ID.

Si es que te sigue fallando el test puedes adjuntar el screenshot del body response que tienes para "update date of vaccine 1 person 1", junto con otro screenshot del body response para "show vaccines for person 1" y asi tendria mas informacion para ayudarte.

**Comment by Ferc28** [comment]
Hola, me ocurre el mismo problema. Realice las consultas por separado y el test de PATCH me muestra que si fue actualizada la vacuna. Sin embargo se nota que justamente no esta en orden y que se compara con el parámetro de otra vacuna.

**Comment by Balison** [comment]
Hola, teniendo en cuenta eso, me gustaria saber si (i) todos los tests antes de PATCH son exitosos? y (ii) ejecutaste en orden los requests? 
Si ejecutaste en orden los requests, existe la posibilidad de que algun tests antes de PATCH este fallando. Puede que esto solo suceda por un error en el output, asi que te recomendaria ver el reporte. Caso contrario, me gustaria que adjuntes un screenshot del reporte en general y el body response para "show vaccines for person 1" para obterner mas informacion y ayudarte.

**Comment by Ferc28** [comment]
- En efecto todos los test antes del PATCH son exitosos. 
- Los Request se están ejecutando en orden, según como fueron dados en el archivo de RequestAPITask y según como los va ejecutando Postman. En definitiva si no fuese así creo que arrojaría errores en otros test, y solo tengo un test fallido correspondiente al del Update.

Adjunto Screenshots;

![image](https://user-images.githubusercontent.com/89324156/227812256-b9f008e8-ad79-4fc8-9897-bd5eecf42f90.png)

![image](https://user-images.githubusercontent.com/89324156/227812210-6cd21d4b-b916-4f4a-a0a4-8073f1ecce45.png)

**Comment by Zarth912** [comment]
Hola, yo arregle el problema cuando la profe dijo en clase que se pedia la info de la vacuna y no de la persona a la que se vacunó.  Espero te ayude.

**Comment by Ferc28** [comment]
Muchas gracias por el feedback @Zarth912. Por lo que tengo entendido el enunciado en el Update pide las vacunas de esa persona en particular, donde si ves mis screenshots justamente se ven las dos vacunas junto con la que se actualizo,  y junto con el error (que al parecer compara la fecha de la otra vacuna).

De todas maneras probé lo que me comentaste (entregar la info. de la vacuna) aunque de ahí me arroja otro error. Lo adjunto;

![image](https://user-images.githubusercontent.com/89324156/227813421-379dfabb-5051-4f08-9e3e-8fdbd9c2695d.png)

**Comment by Balison** [comment]
> * En efecto todos los test antes del PATCH son exitosos.
> * Los Request se están ejecutando en orden, según como fueron dados en el archivo de RequestAPITask y según como los va ejecutando Postman. En definitiva si no fuese así creo que arrojaría errores en otros test, y solo tengo un test fallido correspondiente al del Update.
> 
> Adjunto Screenshots;
> 
> ![image](https://user-images.githubusercontent.com/89324156/227812256-b9f008e8-ad79-4fc8-9897-bd5eecf42f90.png)
> 
> ![image](https://user-images.githubusercontent.com/89324156/227812210-6cd21d4b-b916-4f4a-a0a4-8073f1ecce45.png)

En el ultimo screenshot la ruta de PATCH es localhost:3000/persons/104/vaccines/145 y en el response se ve que si bien entregas correctamente todas las vacunas de la persona con ID = 104, las vacunas no estan ordenadas en base al id. 

Es decir, tu response entrega como primera vacuna, la vacuna con ID = 146 (que en realidad es la segunda vacuna para esa persona) y despues entrega la vacuna con ID = 145. Para solucionar el problema debes mostrar las vacunas en orden (el orden por default es en base a ID, donde el primer elemento es el ID menor, es decir la primera vacuna creada para esa persona). Si aun tienes problemas, por favor escribeme para que pueda inspeccionar mejor tu codigo.
