### ISSUE TITLE
Problema parte 8 setup: Bundler cannot continue

### ISSUE THREAD

**Issue by clementestreeter** [IIC2143/Syllabus#9]
Hola! cuando corro bundler install, me aparece esto 
![image](https://user-images.githubusercontent.com/80768814/184451375-e3730850-1d5e-46f4-a8cc-b51e187197f1.png)
Y al instalar lo que sale en el error me retorna esto 
![image](https://user-images.githubusercontent.com/80768814/184451501-62c37d8d-ef4b-4592-9e2d-32d901e12331.png)

**Comment by meretamal** [comment]
Hola 😁 , corriste [Paso 4](https://github.com/IIC2143/Syllabus/wiki/Setup-Ubuntu---Windows#4-postgressql).

Si no, tal vez faltó instalar las herramientas de desarrollador de postgres. Para eso corre:
```bash
sudo apt-get install libpq-dev
```

**Comment by clementestreeter** [comment]
Con eso me corrio!! Muchas Gracias!!!!
