### ISSUE TITLE
Error de sintaxis con las rutas de devise

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2143/Syllabus#90]
En la ayudantía de devise, nos dice que agreguemos las rutas del controlador del usuario. En nuestro proyecto estamos siguiendo un procedimiento muy similar, pero cuando ponemos las rutas en el archivo pedido (literalmente copiadas) nos tira error de sintaxis.
Adjunto las fotos del power point de la ayudantía y de nuestro proyecto.
![image](https://user-images.githubusercontent.com/80768621/166585849-305d2888-78e5-4279-a2b9-353bf9e61930.png)
![image](https://user-images.githubusercontent.com/80768621/166585734-7770d2db-b6f9-4984-a785-77a380cf6d34.png)

**Comment by NicoJGutierrez** [comment]
Se agradece cualquier ayuda

**Comment by ManuelRamirez-M** [comment]
Hola, hay que quitar el primer ":" de controllers
![image](https://user-images.githubusercontent.com/89363500/166612851-5d454cdd-b668-4e17-9a30-dcd918a305bc.png)

**Comment by NicoJGutierrez** [comment]
Ahí me funcionó, muchas gracias!
