### ISSUE TITLE
duda enunciado parte 2 metodo1 y metodo 4

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2143/Syllabus#90]
hola, no veo la diferencia lógica entre el método 1 y el método 4 de la parte 2, el método 1 retorna todos los partidos del equipo segun el id dado, y el método 4 también retorna los partidos según el id dado.
Espero puedan aclarar esta duda.

**Comment by TheExcel2** [comment]
En el método 4 te dan el nombre del equipo, no el id
