### ISSUE TITLE
Rspec: not routes matched "*"

### ISSUE THREAD

**Issue by Juancagp** [IIC2143/Syllabus#90]
Hola, viendo y siguiendo el tutorial de Rspes + Simplecov llegué hasta los últimos 5 minutos donde comienza a crear el archivo game_request_spec.rb y le pone código. Al hacer lo mismo en mi archivo pero cambiandole todas los "game" por "cancha" y/o "Cancha" (segun corresponda) corrí despues Rspec pero me aparecieron los siguientes errores y no encuentro nada en internet que me sirva en específico 

<img width="542" alt="image" src="https://user-images.githubusercontent.com/81201399/192875035-ad7ad63a-4328-43f8-9b93-e65f4f9fbcd1.png">

**Comment by Juancagp** [comment]
al parecer en ves de cancha.save tenía otra cosa (cancha.shared_context_metadatab_behavior) en fin, pero me sigue apareciendo el siguiente error
<img width="667" alt="image" src="https://user-images.githubusercontent.com/81201399/192876100-51f6829e-788f-40de-9287-ace8698f8069.png">

**Comment by meretamal** [comment]
Hola 😁 , en la segunda foto pasa que `canchas_path(@cancha)` esta retornando "/canchas.3", en lugar de "/canchas/3". Prueba usando `cancha_path(@cancha)`.

Ojalá siempre crea los recursos con nombres en inglés, porque pueden haber problemas con las transformaciones que hace rails de singular a plural, entonces me queda la duda si el helper para una cancha específica va a ser el que te dije. Si no funciona, en luagr de usar el helper, escribe directamente `patch #"/canchas/3"`.
