### ISSUE TITLE
Your Yarn packages are out of date! Please run `yarn install --check-files` to update

### ISSUE THREAD

**Issue by Gau04** [IIC2143/Syllabus#91]
Hola! Estamos intentando utilizar devise en el proyecto y nos salta el siguiente error de yarn:

![image](https://user-images.githubusercontent.com/80788847/192875080-e0a41a15-cfac-4e03-8406-2ad163808d7f.png)

Intentamos con yarn install --check-files, revisamos config/webpacker.yml y las versiones de node con nvm, intentamos cambiarlas, s reinstalar los webpackers en distintas versiones y nos sigue saliendo el mismo error :(

**Comment by Gau04** [comment]
Por si alguien más tiene este problema lo solucionamos con spring stop

**Comment by Ikilly0** [comment]
Como usaste spring stop exactamente? es un workaround o lo arregla?
