### ISSUE TITLE
Heroku-Error de carga

### ISSUE THREAD

**Issue by ebenstom** [IIC2143/Syllabus#92]
Hola, la aplicación funciona perfecto en local con rails s pero al subirlo a heroku carga la pantalla principal y al ir a otra pantalla falla
![image](https://user-images.githubusercontent.com/89204796/166846822-f3f38401-1071-44c6-b624-315dc54f1356.png)

**Comment by GabQuiroz** [comment]
Hola, a mi y a mi grupo nos pasó y es porque al parecer Heroku no hace las migraciones en el deploy. Tienes que ejecutar "heroku run rails db:migrate" en la terminal, en tu repositorio. Así por lo menos nuestra aplicación logró partir.

**Comment by ebenstom** [comment]
Gracias! Si, le puse rake en vez de rails y ahora si funciona! Te pasaste!
Mucha suerte!
