### ISSUE TITLE
Error con Test

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#93]
Hola, Estoy siguiendo los pasos de la ayudantía de testing, pero al hacer los test para los modelos, y hacer la parte de factory, me tira el siguiente error al correr el test:
![Captura de Pantalla 2022-09-29 a la(s) 14 33 16](https://user-images.githubusercontent.com/89275951/193102398-fdd69967-f6b5-419b-b7d5-d49cdb62e8a2.png)

**Comment by simonmb12** [comment]
Arreglé el error pasado, pero ahora me tira el siguiente error de sintaxis, siendo que el código lo copie de la ayudantía: 
![Captura de Pantalla 2022-09-29 a la(s) 15 33 02](https://user-images.githubusercontent.com/89275951/193114392-938ec029-05a8-4272-ac7b-3723ddb2369b.png)
La parte del código a la que corresponde seria: 
![Captura de Pantalla 2022-09-29 a la(s) 15 33 55](https://user-images.githubusercontent.com/89275951/193114551-e80f5ddd-29c2-41d4-962f-64f2777252f0.png)

**Comment by simonmb12** [comment]
Ya logré resolver el problema anterior. Sin embargo, ahora que trato de probar mis tests, me dice lo siguiente:
![Captura de Pantalla 2022-09-29 a la(s) 15 56 05](https://user-images.githubusercontent.com/89275951/193118633-bc0ece3b-7f67-4eb3-b642-e3170a3d37d5.png)
Lo que significa que no se está creando la instancia del juego en el test. No entiendo por qué pasa esto. 
Para todos los siguientes tests pasa lo mismo... 
![Captura de Pantalla 2022-09-29 a la(s) 15 58 02](https://user-images.githubusercontent.com/89275951/193118966-b2f0d490-62ba-4d85-991d-bce67a84777d.png)

**Comment by meretamal** [comment]
Hola 😁 , podrías subir tus cambios a alguna rama, con tal de ver el resto del código? Puede pasar que la feature esté mal

**Comment by simonmb12** [comment]
Todos los cambios está en la rama "users" de mi repo (grupo70)

**Comment by meretamal** [comment]
Estuve viendo tu código, y es porque ahora tienes que iniciar sesión para realizar esas acciones. Podrías buscar en google cómo integrar el inicio de sesión de devise en tus tests
