### ISSUE TITLE
RSpec URI Error

### ISSUE THREAD

**Issue by jahernandez2** [IIC2143/Syllabus#96]
hola, al hacer rails spec en la consola de ubuntu, me tira este error que no hemos podido encontrar que significa. Adjunto foto del error y del codigo del testing. 

![image](https://user-images.githubusercontent.com/62116520/193164317-7bcdbb64-9aef-4a5d-8c78-b06cd8ef9ca8.png)

**Comment by JupaOlivares** [comment]
Hola! 

Hay 2 cosas que me generan curiosidad de tu codigo, primero ¿por que estas encapsulando el test dentro de una clase? y segundo deberias poder hacer en la linea 9 get "index" directamente sin necesidad de hacer "publications#index"
