### ISSUE TITLE
Subir tarea a github

### ISSUE THREAD

**Issue by santiago3c** [IIC2143/Syllabus#97]
Hola, que me gustaría poder subir la tarea a github, pero no sé cómo hacerlo. No sé cómo ni desde dónde acceder a mi repositorio

**Comment by santiago3c** [comment]
Hola, acaba de encontrar el lugar donde me llego la invitación para mi repositorio, pero me sale que la invitación expiró y no sé que hacer

**Comment by TheMightyTsar** [comment]
Hola!
para que te reenvien la invitacion al repositorio escribele a este correo: [felipe.munoz.moraga@uc.cl]

Si ya avanzaste ya en tu tarea, puedes mover los archivos al repo clonado, excepto la carpeta .git 😉

**Comment by TheMightyTsar** [comment]
Ojo con como estas subiendo tu tarea.
Cuando abras tu repo deberiamos ver los archivos del proyecto no una carpeta

**Comment by santiago3c** [comment]
a dale, entonces copio todos los archivos, luego los pego en la carpeta y a eso le hago git add commit y push

________________________________
De: Nicolás Fernández ***@***.***>
Enviado: viernes, 29 de marzo de 2024 11:29
Para: IIC2143/Syllabus ***@***.***>
Cc: Santiago Cortes Solari ***@***.***>; Author ***@***.***>
Asunto: Re: [IIC2143/Syllabus] Subir tarea a github (Issue #97)


Ojo con como estas subiendo tu tarea.
Cuando abras tu repo deberiamos ver los archivos del proyecto no una carpeta

**Comment by santiago3c** [comment]
copio y pego todos los archivos excepto el .git?
________________________________
De: Santiago Cortes Solari ***@***.***>
Enviado: viernes, 29 de marzo de 2024 11:31
Para: IIC2143/Syllabus ***@***.***>
Asunto: RE: [IIC2143/Syllabus] Subir tarea a github (Issue #97)

a dale, entonces copio todos los archivos, luego los pego en la carpeta y a eso le hago git add commit y push

________________________________
De: Nicolás Fernández ***@***.***>
Enviado: viernes, 29 de marzo de 2024 11:29
Para: IIC2143/Syllabus ***@***.***>
Cc: Santiago Cortes Solari ***@***.***>; Author ***@***.***>
Asunto: Re: [IIC2143/Syllabus] Subir tarea a github (Issue #97)


Ojo con como estas subiendo tu tarea.
Cuando abras tu repo deberiamos ver los archivos del proyecto no una carpeta

**Comment by TheMightyTsar** [comment]
super! que te vaya bien en tu tarea 😀
