### ISSUE TITLE
PG::DuplicateTable: ERROR: 

### ISSUE THREAD

**Issue by Franbelen** [IIC2143/Syllabus#97]
Hola buenas al parecer una tabla esta ya creada en la base de datos por lo que no me permite hacer db: migrate, buscando en internet dice que puedo borrarla pero tampoco funciona (db: drop nombre_tabla) que puedo hacer?

**Comment by JupaOlivares** [comment]
Hola puedes madar foto? Por otro lado para hacer db:migrate la tabla necesariamente debe estar creada.

Al hacer rails db:drop, debes hacer rails db:create despues nuevamente, si los comandos no te funcionan asegurate que el servicio de postgresql este corriendo
