### ISSUE TITLE
Error al subir a heroku

### ISSUE THREAD

**Issue by simonmb12** [IIC2143/Syllabus#99]
Hola, estoy haciendo el deploy en heroku, pero me tira un error cuando paso a los link de mi aplicación:

![Captura de Pantalla 2022-09-30 a la(s) 12 47 31](https://user-images.githubusercontent.com/89275951/193308243-9c9f5c88-14e0-4c0f-9d21-1237b2baa275.png)
![Captura de Pantalla 2022-09-30 a la(s) 12 47 39](https://user-images.githubusercontent.com/89275951/193308256-d86bad7a-8411-4a42-b8c0-7752d4835179.png)

El deploy está hecho, pero no puedo interactuar en la aplicación.

**Comment by simonmb12** [comment]
Ya resolví el problema con heroku stack:set heroku-20, pero ahora me tira el siguiente error de una gema:
![Captura de Pantalla 2022-09-30 a la(s) 12 36 31](https://user-images.githubusercontent.com/89275951/193306130-e62e7032-df88-427b-80b8-a52dbf610b37.png)

**Comment by JupaOlivares** [comment]
Hola en local te funciona? Prueba correrlo en local en modo incognito (para evitar usar el cache) y si no te funciona puede ser un problema de routing o controladores

**Comment by simonmb12** [comment]
Si, me funciona perfecto en local. Por lo que leí, se podría deber a que no esté creada la bdd en heroku. Estuve viendo videos de cómo hacerlo, pero no lo logro hacer.

**Comment by gonzaloi21** [comment]
tengo el mismo problema

**Comment by belenmatte** [comment]
Yo también

**Comment by gecoli** [comment]
Tengo el mismo problema

**Comment by aurmeneta** [comment]
Hola, en heroku revisen los logs para saber más sobre el problema. Posiblemente no han corrido rails db:create y/o rails db:migrate en el servidor

**Comment by gecoli** [comment]
Al correr rails db:create me aparece `Database '. . .' already exists` y con rails db:migrate no ocurre nada (todas las migraciones están hechas).
Aún así heroku no corre:(

**Comment by victoriaatria** [comment]
A mi se me solucionó corriendo ``` heroku run rake db:migrate ``` 

Acá salen más soluciones posibles:
https://stackoverflow.com/questions/11075450/heroku-were-sorry-but-something-went-wrong

**Comment by simonmb12** [comment]
Buenaaa, también se me solucionó con esto heroku run rake db:migrate
